//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../gig_ios/src/edu/umass/cs/gigapaxos/paxospackets/BatchedCommit.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "edu/umass/cs/gigapaxos/paxospackets/BatchedCommit.h"
#include "edu/umass/cs/gigapaxos/paxospackets/PValuePacket.h"
#include "edu/umass/cs/gigapaxos/paxospackets/PaxosPacket.h"
#include "edu/umass/cs/gigapaxos/paxospackets/ProposalPacket.h"
#include "edu/umass/cs/gigapaxos/paxosutil/Ballot.h"
#include "edu/umass/cs/gigapaxos/paxosutil/IntegerMap.h"
#include "edu/umass/cs/gigapaxos/paxosutil/PaxosMessenger.h"
#include "edu/umass/cs/utils/DelayProfiler.h"
#include "edu/umass/cs/utils/Util.h"
#include "java/io/UnsupportedEncodingException.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/Integer.h"
#include "java/lang/RuntimeException.h"
#include "java/lang/System.h"
#include "java/nio/Buffer.h"
#include "java/nio/ByteBuffer.h"
#include "java/util/HashSet.h"
#include "java/util/Set.h"
#include "java/util/TreeSet.h"
#include "net/minidev/json/JSONObject.h"
#include "org/json/JSONArray.h"
#include "org/json/JSONObject.h"

@interface EduUmassCsGigapaxosPaxospacketsBatchedCommit () {
 @public
  jint medianCheckpointedSlot_;
  JavaUtilTreeSet *slots_;
  id<JavaUtilSet> group_;
  IOSByteArray *byteifiedSelf_;
}

@end

J2OBJC_FIELD_SETTER(EduUmassCsGigapaxosPaxospacketsBatchedCommit, slots_, JavaUtilTreeSet *)
J2OBJC_FIELD_SETTER(EduUmassCsGigapaxosPaxospacketsBatchedCommit, group_, id<JavaUtilSet>)
J2OBJC_FIELD_SETTER(EduUmassCsGigapaxosPaxospacketsBatchedCommit, byteifiedSelf_, IOSByteArray *)

__attribute__((unused)) static void EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields_initWithIOSClass_withNSString_withInt_(EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields *self, IOSClass *type, NSString *__name, jint __ordinal);

J2OBJC_INITIALIZED_DEFN(EduUmassCsGigapaxosPaxospacketsBatchedCommit)

@implementation EduUmassCsGigapaxosPaxospacketsBatchedCommit

- (instancetype)initWithEduUmassCsGigapaxosPaxospacketsPValuePacket:(EduUmassCsGigapaxosPaxospacketsPValuePacket *)pvalue
                                                    withJavaUtilSet:(id<JavaUtilSet>)group {
  EduUmassCsGigapaxosPaxospacketsBatchedCommit_initWithEduUmassCsGigapaxosPaxospacketsPValuePacket_withJavaUtilSet_(self, pvalue, group);
  return self;
}

- (instancetype)initWithOrgJsonJSONObject:(OrgJsonJSONObject *)json {
  EduUmassCsGigapaxosPaxospacketsBatchedCommit_initWithOrgJsonJSONObject_(self, json);
  return self;
}

- (jboolean)addBatchedCommitWithEduUmassCsGigapaxosPaxospacketsBatchedCommit:(EduUmassCsGigapaxosPaxospacketsBatchedCommit *)bCommit {
  if (![((EduUmassCsGigapaxosPaxosutilBallot *) nil_chk(((EduUmassCsGigapaxosPaxospacketsBatchedCommit *) nil_chk(bCommit))->ballot_)) isEqual:self->ballot_] || ![((NSString *) nil_chk(bCommit->paxosID_)) isEqual:self->paxosID_]) @throw create_JavaLangRuntimeException_initWithNSString_(JreStrcat("$@$@", @"Unable to combine ", [bCommit getSummary], @" with ", [self getSummary]));
  if ([bCommit getMedianCheckpointedSlot] - self->medianCheckpointedSlot_ > 0) self->medianCheckpointedSlot_ = [bCommit getMedianCheckpointedSlot];
  return [((JavaUtilTreeSet *) nil_chk(self->slots_)) addAllWithJavaUtilCollection:bCommit->slots_];
}

- (jboolean)addCommitWithEduUmassCsGigapaxosPaxospacketsPValuePacket:(EduUmassCsGigapaxosPaxospacketsPValuePacket *)commit {
  if (![((EduUmassCsGigapaxosPaxosutilBallot *) nil_chk(((EduUmassCsGigapaxosPaxospacketsPValuePacket *) nil_chk(commit))->ballot_)) isEqual:self->ballot_] || ![((NSString *) nil_chk(commit->paxosID_)) isEqual:self->paxosID_]) @throw create_JavaLangRuntimeException_initWithNSString_(JreStrcat("$@$@", @"Unable to combine ", [commit getSummary], @" with ", [self getSummary]));
  if ([commit getMedianCheckpointedSlot] - self->medianCheckpointedSlot_ > 0) self->medianCheckpointedSlot_ = [commit getMedianCheckpointedSlot];
  return [((JavaUtilTreeSet *) nil_chk(self->slots_)) addWithId:JavaLangInteger_valueOfWithInt_(commit->slot_)];
}

- (IOSObjectArray *)getCommittedSlots {
  return [((JavaUtilTreeSet *) nil_chk(self->slots_)) toArrayWithNSObjectArray:[IOSObjectArray arrayWithLength:0 type:JavaLangInteger_class_()]];
}

- (OrgJsonJSONObject *)toJSONObjectImpl {
  OrgJsonJSONObject *json = create_OrgJsonJSONObject_init();
  [json putWithNSString:[((EduUmassCsGigapaxosPaxospacketsPaxosPacket_NodeIDKeys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosPaxospacketsPaxosPacket_NodeIDKeys, B))) description] withId:[((EduUmassCsGigapaxosPaxosutilBallot *) nil_chk(ballot_)) description]];
  [json putWithNSString:[((EduUmassCsGigapaxosPaxospacketsPaxosPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosPaxospacketsPaxosPacket_Keys, GC_S))) description] withInt:self->medianCheckpointedSlot_];
  [json putWithNSString:[((EduUmassCsGigapaxosPaxospacketsPaxosPacket_NodeIDKeys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosPaxospacketsPaxosPacket_NodeIDKeys, GROUP))) description] withJavaUtilCollection:self->group_];
  [json putWithNSString:[((EduUmassCsGigapaxosPaxospacketsPaxosPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosPaxospacketsPaxosPacket_Keys, SLOTS))) description] withJavaUtilCollection:self->slots_];
  return json;
}

- (NetMinidevJsonJSONObject *)toJSONSmartImpl {
  NetMinidevJsonJSONObject *json = create_NetMinidevJsonJSONObject_init();
  [json putWithId:[((EduUmassCsGigapaxosPaxospacketsPaxosPacket_NodeIDKeys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosPaxospacketsPaxosPacket_NodeIDKeys, B))) description] withId:[((EduUmassCsGigapaxosPaxosutilBallot *) nil_chk(ballot_)) description]];
  [json putWithId:[((EduUmassCsGigapaxosPaxospacketsPaxosPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosPaxospacketsPaxosPacket_Keys, GC_S))) description] withId:JavaLangInteger_valueOfWithInt_(self->medianCheckpointedSlot_)];
  [json putWithId:[((EduUmassCsGigapaxosPaxospacketsPaxosPacket_NodeIDKeys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosPaxospacketsPaxosPacket_NodeIDKeys, GROUP))) description] withId:self->group_];
  [json putWithId:[((EduUmassCsGigapaxosPaxospacketsPaxosPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosPaxospacketsPaxosPacket_Keys, SLOTS))) description] withId:self->slots_];
  return json;
}

- (instancetype)initWithJavaNioByteBuffer:(JavaNioByteBuffer *)bbuf {
  EduUmassCsGigapaxosPaxospacketsBatchedCommit_initWithJavaNioByteBuffer_(self, bbuf);
  return self;
}

- (IOSByteArray *)toBytes {
  jlong t = JavaLangSystem_nanoTime();
  if (self->byteifiedSelf_ != nil) return self->byteifiedSelf_;
  if (!(JreLoadStatic(EduUmassCsGigapaxosPaxospacketsPaxosPacket, BYTEIFICATION) && EduUmassCsGigapaxosPaxosutilIntegerMap_allInt())) {
    @try {
      return JreStrongAssign(&self->byteifiedSelf_, [((NSString *) nil_chk([self description])) java_getBytesWithCharsetName:JreLoadStatic(EduUmassCsGigapaxosPaxospacketsPaxosPacket, CHARSET)]);
    }
    @catch (JavaIoUnsupportedEncodingException *e) {
      [((JavaIoUnsupportedEncodingException *) nil_chk(e)) printStackTrace];
      return nil;
    }
  }
  JavaNioByteBuffer *bbuf;
  @try {
    jint paxosIDLength = ((IOSByteArray *) nil_chk([((NSString *) nil_chk([self getPaxosID])) java_getBytesWithCharsetName:JreLoadStatic(EduUmassCsGigapaxosPaxospacketsPaxosPacket, CHARSET)]))->size_;
    bbuf = JavaNioByteBuffer_wrapWithByteArray_([IOSByteArray arrayWithLength:EduUmassCsGigapaxosPaxospacketsPaxosPacket_SIZEOF_PAXOSPACKET_FIXED + paxosIDLength + EduUmassCsGigapaxosPaxospacketsBatchedCommit_SIZEOF_BATCHEDCOMMIT_FIXED + 4 * ([((JavaUtilTreeSet *) nil_chk(self->slots_)) size] + 1 + [((id<JavaUtilSet>) nil_chk(self->group_)) size] + 1)]);
    [super toBytesWithJavaNioByteBuffer:bbuf];
    JreAssert(([((JavaNioByteBuffer *) nil_chk(bbuf)) position] == EduUmassCsGigapaxosPaxospacketsPaxosPacket_SIZEOF_PAXOSPACKET_FIXED + paxosIDLength), (@"edu/umass/cs/gigapaxos/paxospackets/BatchedCommit.java:174 condition failed: assert (bbuf.position() == SIZEOF_PAXOSPACKET_FIXED + paxosIDLength);"));
    [((JavaNioByteBuffer *) nil_chk([((JavaNioByteBuffer *) nil_chk([((JavaNioByteBuffer *) nil_chk([bbuf putIntWithInt:((EduUmassCsGigapaxosPaxosutilBallot *) nil_chk(self->ballot_))->ballotNumber_])) putIntWithInt:self->ballot_->coordinatorID_])) putIntWithInt:self->medianCheckpointedSlot_])) putIntWithInt:[self->slots_ size]];
    for (JavaLangInteger * __strong i in slots_) [bbuf putIntWithInt:[((JavaLangInteger *) nil_chk(i)) intValue]];
    [bbuf putIntWithInt:[self->group_ size]];
    for (JavaLangInteger * __strong i in self->group_) [bbuf putIntWithInt:[((JavaLangInteger *) nil_chk(i)) intValue]];
    JreAssert(((![bbuf hasRemaining])), (@"edu/umass/cs/gigapaxos/paxospackets/BatchedCommit.java:184 condition failed: assert (!bbuf.hasRemaining());"));
    if (JreLoadStatic(EduUmassCsGigapaxosPaxosutilPaxosMessenger, INSTRUMENT_SERIALIZATION) && EduUmassCsUtilsUtil_oneInWithInt_(100)) EduUmassCsUtilsDelayProfiler_updateDelayNanoWithNSString_withLong_withInt_(@"commit->", t, [self->slots_ size]);
    JreAssert(([((JavaNioByteBuffer *) nil_chk(((JavaNioByteBuffer *) cast_chk([bbuf positionWithInt:EduUmassCsGigapaxosPaxospacketsPaxosPacket_SIZEOF_PAXOSPACKET_FIXED + ((IOSByteArray *) nil_chk([((NSString *) nil_chk([self getPaxosID])) java_getBytesWithCharsetName:JreLoadStatic(EduUmassCsGigapaxosPaxospacketsPaxosPacket, CHARSET)]))->size_ + EduUmassCsGigapaxosPaxospacketsBatchedCommit_SIZEOF_BATCHEDCOMMIT_FIXED], [JavaNioByteBuffer class])))) getInt] == [self->slots_ size]), (JreStrcat("I$$$I", [((JavaNioByteBuffer *) nil_chk(JavaNioByteBuffer_wrapWithByteArray_withInt_withInt_([bbuf array], EduUmassCsGigapaxosPaxospacketsPaxosPacket_SIZEOF_PAXOSPACKET_FIXED + ((IOSByteArray *) nil_chk([((NSString *) nil_chk([self getPaxosID])) java_getBytesWithCharsetName:JreLoadStatic(EduUmassCsGigapaxosPaxospacketsPaxosPacket, CHARSET)]))->size_ + EduUmassCsGigapaxosPaxospacketsBatchedCommit_SIZEOF_BATCHEDCOMMIT_FIXED, 4))) getInt], @" != ", [[self java_getClass] getSimpleName], @".slots.size()=", [self->slots_ size])));
    JreAssert(([((JavaNioByteBuffer *) nil_chk(((JavaNioByteBuffer *) cast_chk([bbuf positionWithInt:EduUmassCsGigapaxosPaxospacketsPaxosPacket_SIZEOF_PAXOSPACKET_FIXED + ((IOSByteArray *) nil_chk([((NSString *) nil_chk([self getPaxosID])) java_getBytesWithCharsetName:JreLoadStatic(EduUmassCsGigapaxosPaxospacketsPaxosPacket, CHARSET)]))->size_ + EduUmassCsGigapaxosPaxospacketsBatchedCommit_SIZEOF_BATCHEDCOMMIT_FIXED + 4 + [self->slots_ size] * 4], [JavaNioByteBuffer class])))) getInt] == [self->group_ size]), (JreStrcat("I$$$I", [((JavaNioByteBuffer *) nil_chk(JavaNioByteBuffer_wrapWithByteArray_withInt_withInt_([bbuf array], EduUmassCsGigapaxosPaxospacketsPaxosPacket_SIZEOF_PAXOSPACKET_FIXED + ((IOSByteArray *) nil_chk([((NSString *) nil_chk([self getPaxosID])) java_getBytesWithCharsetName:JreLoadStatic(EduUmassCsGigapaxosPaxospacketsPaxosPacket, CHARSET)]))->size_ + EduUmassCsGigapaxosPaxospacketsBatchedCommit_SIZEOF_BATCHEDCOMMIT_FIXED + 4 + [self->slots_ size] * 4, 4))) getInt], @" != ", [[self java_getClass] getSimpleName], @".group.size()=", [self->group_ size])));
    return [bbuf array];
  }
  @catch (JavaIoUnsupportedEncodingException *e) {
    [((JavaIoUnsupportedEncodingException *) nil_chk(e)) printStackTrace];
  }
  return nil;
}

- (jint)getMedianCheckpointedSlot {
  return self->medianCheckpointedSlot_;
}

- (void)setMedianCheckpointedSlotWithInt:(jint)slot {
  self->medianCheckpointedSlot_ = slot;
}

- (NSString *)getSummaryString {
  return JreStrcat("@C@", self->ballot_, ':', self->slots_);
}

- (IOSIntArray *)getGroup {
  return EduUmassCsUtilsUtil_setToIntArrayWithJavaUtilSet_(self->group_);
}

- (id<JavaUtilSet>)getGroupSet {
  return self->group_;
}

- (jint)size {
  return [((JavaUtilTreeSet *) nil_chk(self->slots_)) size];
}

+ (void)mainWithNSStringArray:(IOSObjectArray *)args {
  EduUmassCsGigapaxosPaxospacketsBatchedCommit_mainWithNSStringArray_(args);
}

- (void)dealloc {
  RELEASE_(ballot_);
  RELEASE_(slots_);
  RELEASE_(group_);
  RELEASE_(byteifiedSelf_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, 1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, 3, -1, -1, -1 },
    { NULL, "Z", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "[LJavaLangInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgJsonJSONObject;", 0x4, -1, -1, 3, -1, -1, -1 },
    { NULL, "LNetMinidevJsonJSONObject;", 0x4, -1, -1, 3, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 8, 9, -1, -1, -1 },
    { NULL, "[B", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 11, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "[I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilSet;", 0x1, -1, -1, -1, 12, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 13, 14, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithEduUmassCsGigapaxosPaxospacketsPValuePacket:withJavaUtilSet:);
  methods[1].selector = @selector(initWithOrgJsonJSONObject:);
  methods[2].selector = @selector(addBatchedCommitWithEduUmassCsGigapaxosPaxospacketsBatchedCommit:);
  methods[3].selector = @selector(addCommitWithEduUmassCsGigapaxosPaxospacketsPValuePacket:);
  methods[4].selector = @selector(getCommittedSlots);
  methods[5].selector = @selector(toJSONObjectImpl);
  methods[6].selector = @selector(toJSONSmartImpl);
  methods[7].selector = @selector(initWithJavaNioByteBuffer:);
  methods[8].selector = @selector(toBytes);
  methods[9].selector = @selector(getMedianCheckpointedSlot);
  methods[10].selector = @selector(setMedianCheckpointedSlotWithInt:);
  methods[11].selector = @selector(getSummaryString);
  methods[12].selector = @selector(getGroup);
  methods[13].selector = @selector(getGroupSet);
  methods[14].selector = @selector(size);
  methods[15].selector = @selector(mainWithNSStringArray:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "ballot_", "LEduUmassCsGigapaxosPaxosutilBallot;", .constantValue.asLong = 0, 0x11, -1, -1, -1, -1 },
    { "medianCheckpointedSlot_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "slots_", "LJavaUtilTreeSet;", .constantValue.asLong = 0, 0x12, -1, -1, 15, -1 },
    { "group_", "LJavaUtilSet;", .constantValue.asLong = 0, 0x12, -1, -1, 16, -1 },
    { "SIZEOF_BATCHEDCOMMIT_FIXED", "I", .constantValue.asInt = EduUmassCsGigapaxosPaxospacketsBatchedCommit_SIZEOF_BATCHEDCOMMIT_FIXED, 0x1c, -1, -1, -1, -1 },
    { "byteifiedSelf_", "[B", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LEduUmassCsGigapaxosPaxospacketsPValuePacket;LJavaUtilSet;", "(Ledu/umass/cs/gigapaxos/paxospackets/PValuePacket;Ljava/util/Set<Ljava/lang/Integer;>;)V", "LOrgJsonJSONObject;", "LOrgJsonJSONException;", "addBatchedCommit", "LEduUmassCsGigapaxosPaxospacketsBatchedCommit;", "addCommit", "LEduUmassCsGigapaxosPaxospacketsPValuePacket;", "LJavaNioByteBuffer;", "LJavaIoUnsupportedEncodingException;LJavaNetUnknownHostException;", "setMedianCheckpointedSlot", "I", "()Ljava/util/Set<Ljava/lang/Integer;>;", "main", "[LNSString;", "Ljava/util/TreeSet<Ljava/lang/Integer;>;", "Ljava/util/Set<Ljava/lang/Integer;>;", "LEduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields;" };
  static const J2ObjcClassInfo _EduUmassCsGigapaxosPaxospacketsBatchedCommit = { "BatchedCommit", "edu.umass.cs.gigapaxos.paxospackets", ptrTable, methods, fields, 7, 0x1, 16, 6, -1, 17, -1, -1, -1 };
  return &_EduUmassCsGigapaxosPaxospacketsBatchedCommit;
}

+ (void)initialize {
  if (self == [EduUmassCsGigapaxosPaxospacketsBatchedCommit class]) {
    {
      EduUmassCsGigapaxosPaxospacketsPaxosPacket_checkFieldsWithIOSClass_withEduUmassCsGigapaxosPaxospacketsPaxosPacket_GetTypeArray_(EduUmassCsGigapaxosPaxospacketsBatchedCommit_class_(), EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields_values());
    }
    J2OBJC_SET_INITIALIZED(EduUmassCsGigapaxosPaxospacketsBatchedCommit)
  }
}

@end

void EduUmassCsGigapaxosPaxospacketsBatchedCommit_initWithEduUmassCsGigapaxosPaxospacketsPValuePacket_withJavaUtilSet_(EduUmassCsGigapaxosPaxospacketsBatchedCommit *self, EduUmassCsGigapaxosPaxospacketsPValuePacket *pvalue, id<JavaUtilSet> group) {
  EduUmassCsGigapaxosPaxospacketsPaxosPacket_initWithEduUmassCsGigapaxosPaxospacketsPaxosPacket_(self, pvalue);
  JreStrongAssignAndConsume(&self->slots_, new_JavaUtilTreeSet_init());
  JreStrongAssign(&self->byteifiedSelf_, nil);
  [self->slots_ addWithId:JavaLangInteger_valueOfWithInt_(((EduUmassCsGigapaxosPaxospacketsProposalPacket *) nil_chk(pvalue))->slot_)];
  JreStrongAssign(&self->ballot_, pvalue->ballot_);
  JreStrongAssign(&self->packetType_, JreLoadEnum(EduUmassCsGigapaxosPaxospacketsPaxosPacket_PaxosPacketType, BATCHED_COMMIT));
  JreStrongAssign(&self->group_, group);
  self->medianCheckpointedSlot_ = [pvalue getMedianCheckpointedSlot];
}

EduUmassCsGigapaxosPaxospacketsBatchedCommit *new_EduUmassCsGigapaxosPaxospacketsBatchedCommit_initWithEduUmassCsGigapaxosPaxospacketsPValuePacket_withJavaUtilSet_(EduUmassCsGigapaxosPaxospacketsPValuePacket *pvalue, id<JavaUtilSet> group) {
  J2OBJC_NEW_IMPL(EduUmassCsGigapaxosPaxospacketsBatchedCommit, initWithEduUmassCsGigapaxosPaxospacketsPValuePacket_withJavaUtilSet_, pvalue, group)
}

EduUmassCsGigapaxosPaxospacketsBatchedCommit *create_EduUmassCsGigapaxosPaxospacketsBatchedCommit_initWithEduUmassCsGigapaxosPaxospacketsPValuePacket_withJavaUtilSet_(EduUmassCsGigapaxosPaxospacketsPValuePacket *pvalue, id<JavaUtilSet> group) {
  J2OBJC_CREATE_IMPL(EduUmassCsGigapaxosPaxospacketsBatchedCommit, initWithEduUmassCsGigapaxosPaxospacketsPValuePacket_withJavaUtilSet_, pvalue, group)
}

void EduUmassCsGigapaxosPaxospacketsBatchedCommit_initWithOrgJsonJSONObject_(EduUmassCsGigapaxosPaxospacketsBatchedCommit *self, OrgJsonJSONObject *json) {
  EduUmassCsGigapaxosPaxospacketsPaxosPacket_initWithOrgJsonJSONObject_(self, json);
  JreStrongAssignAndConsume(&self->slots_, new_JavaUtilTreeSet_init());
  JreStrongAssign(&self->byteifiedSelf_, nil);
  JreStrongAssignAndConsume(&self->ballot_, new_EduUmassCsGigapaxosPaxosutilBallot_initWithNSString_([((OrgJsonJSONObject *) nil_chk(json)) getStringWithNSString:[((EduUmassCsGigapaxosPaxospacketsPaxosPacket_NodeIDKeys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosPaxospacketsPaxosPacket_NodeIDKeys, B))) description]]));
  self->medianCheckpointedSlot_ = [json getIntWithNSString:[((EduUmassCsGigapaxosPaxospacketsPaxosPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosPaxospacketsPaxosPacket_Keys, GC_S))) description]];
  JreStrongAssign(&self->packetType_, EduUmassCsGigapaxosPaxospacketsPaxosPacket_getPaxosPacketTypeWithOrgJsonJSONObject_(json));
  JreStrongAssignAndConsume(&self->group_, new_JavaUtilHashSet_init());
  OrgJsonJSONArray *jsonArray = [json getJSONArrayWithNSString:[((EduUmassCsGigapaxosPaxospacketsPaxosPacket_NodeIDKeys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosPaxospacketsPaxosPacket_NodeIDKeys, GROUP))) description]];
  for (jint i = 0; i < [((OrgJsonJSONArray *) nil_chk(jsonArray)) length]; i++) [self->group_ addWithId:JavaLangInteger_valueOfWithInt_([jsonArray getIntWithInt:i])];
  jsonArray = [json getJSONArrayWithNSString:[((EduUmassCsGigapaxosPaxospacketsPaxosPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosPaxospacketsPaxosPacket_Keys, SLOTS))) description]];
  for (jint i = 0; i < [((OrgJsonJSONArray *) nil_chk(jsonArray)) length]; i++) [self->slots_ addWithId:JavaLangInteger_valueOfWithInt_([jsonArray getIntWithInt:i])];
}

EduUmassCsGigapaxosPaxospacketsBatchedCommit *new_EduUmassCsGigapaxosPaxospacketsBatchedCommit_initWithOrgJsonJSONObject_(OrgJsonJSONObject *json) {
  J2OBJC_NEW_IMPL(EduUmassCsGigapaxosPaxospacketsBatchedCommit, initWithOrgJsonJSONObject_, json)
}

EduUmassCsGigapaxosPaxospacketsBatchedCommit *create_EduUmassCsGigapaxosPaxospacketsBatchedCommit_initWithOrgJsonJSONObject_(OrgJsonJSONObject *json) {
  J2OBJC_CREATE_IMPL(EduUmassCsGigapaxosPaxospacketsBatchedCommit, initWithOrgJsonJSONObject_, json)
}

void EduUmassCsGigapaxosPaxospacketsBatchedCommit_initWithJavaNioByteBuffer_(EduUmassCsGigapaxosPaxospacketsBatchedCommit *self, JavaNioByteBuffer *bbuf) {
  EduUmassCsGigapaxosPaxospacketsPaxosPacket_initWithJavaNioByteBuffer_(self, bbuf);
  JreStrongAssignAndConsume(&self->slots_, new_JavaUtilTreeSet_init());
  JreStrongAssign(&self->byteifiedSelf_, nil);
  JreStrongAssignAndConsume(&self->ballot_, new_EduUmassCsGigapaxosPaxosutilBallot_initWithInt_withInt_([((JavaNioByteBuffer *) nil_chk(bbuf)) getInt], [bbuf getInt]));
  self->medianCheckpointedSlot_ = [bbuf getInt];
  jint numSlots = [bbuf getInt];
  for (jint i = 0; i < numSlots; i++) [self->slots_ addWithId:JavaLangInteger_valueOfWithInt_([bbuf getInt])];
  JreStrongAssignAndConsume(&self->group_, new_JavaUtilHashSet_init());
  jint groupSize = [bbuf getInt];
  for (jint i = 0; i < groupSize; i++) [self->group_ addWithId:JavaLangInteger_valueOfWithInt_([bbuf getInt])];
}

EduUmassCsGigapaxosPaxospacketsBatchedCommit *new_EduUmassCsGigapaxosPaxospacketsBatchedCommit_initWithJavaNioByteBuffer_(JavaNioByteBuffer *bbuf) {
  J2OBJC_NEW_IMPL(EduUmassCsGigapaxosPaxospacketsBatchedCommit, initWithJavaNioByteBuffer_, bbuf)
}

EduUmassCsGigapaxosPaxospacketsBatchedCommit *create_EduUmassCsGigapaxosPaxospacketsBatchedCommit_initWithJavaNioByteBuffer_(JavaNioByteBuffer *bbuf) {
  J2OBJC_CREATE_IMPL(EduUmassCsGigapaxosPaxospacketsBatchedCommit, initWithJavaNioByteBuffer_, bbuf)
}

void EduUmassCsGigapaxosPaxospacketsBatchedCommit_mainWithNSStringArray_(IOSObjectArray *args) {
  EduUmassCsGigapaxosPaxospacketsBatchedCommit_initialize();
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsGigapaxosPaxospacketsBatchedCommit)

J2OBJC_INITIALIZED_DEFN(EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields)

EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields *EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields_values_[4];

@implementation EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields

- (IOSClass *)getType {
  return self->type_;
}

+ (IOSObjectArray *)values {
  return EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields_values();
}

+ (EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields *)valueOfWithNSString:(NSString *)name {
  return EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields_valueOfWithNSString_(name);
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LIOSClass;", 0x1, -1, -1, -1, 0, -1, -1 },
    { NULL, "[LEduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields;", 0x9, 1, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(getType);
  methods[1].selector = @selector(values);
  methods[2].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "ballot", "LEduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields;", .constantValue.asLong = 0, 0x4019, -1, 3, -1, -1 },
    { "medianCheckpointedSlot", "LEduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields;", .constantValue.asLong = 0, 0x4019, -1, 4, -1, -1 },
    { "slots", "LEduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields;", .constantValue.asLong = 0, 0x4019, -1, 5, -1, -1 },
    { "group", "LEduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields;", .constantValue.asLong = 0, 0x4019, -1, 6, -1, -1 },
    { "type_", "LIOSClass;", .constantValue.asLong = 0, 0x10, -1, -1, 7, -1 },
  };
  static const void *ptrTable[] = { "()Ljava/lang/Class<*>;", "valueOf", "LNSString;", &JreEnum(EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields, ballot), &JreEnum(EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields, medianCheckpointedSlot), &JreEnum(EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields, slots), &JreEnum(EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields, group), "Ljava/lang/Class<*>;", "LEduUmassCsGigapaxosPaxospacketsBatchedCommit;", "Ljava/lang/Enum<Ledu/umass/cs/gigapaxos/paxospackets/BatchedCommit$Fields;>;Ledu/umass/cs/gigapaxos/paxospackets/PaxosPacket$GetType;" };
  static const J2ObjcClassInfo _EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields = { "Fields", "edu.umass.cs.gigapaxos.paxospackets", ptrTable, methods, fields, 7, 0x4018, 3, 5, 8, -1, -1, 9, -1 };
  return &_EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields;
}

+ (void)initialize {
  if (self == [EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 4 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    (JreEnum(EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields, ballot) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields_initWithIOSClass_withNSString_withInt_(e, EduUmassCsGigapaxosPaxosutilBallot_class_(), @"ballot", 0);
    (JreEnum(EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields, medianCheckpointedSlot) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields_initWithIOSClass_withNSString_withInt_(e, [IOSClass intClass], @"medianCheckpointedSlot", 1);
    (JreEnum(EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields, slots) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields_initWithIOSClass_withNSString_withInt_(e, JavaUtilTreeSet_class_(), @"slots", 2);
    (JreEnum(EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields, group) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields_initWithIOSClass_withNSString_withInt_(e, JavaUtilSet_class_(), @"group", 3);
    J2OBJC_SET_INITIALIZED(EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields)
  }
}

@end

void EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields_initWithIOSClass_withNSString_withInt_(EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields *self, IOSClass *type, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
  JreStrongAssign(&self->type_, type);
}

IOSObjectArray *EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields_values() {
  EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields_initialize();
  return [IOSObjectArray arrayWithObjects:EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields_values_ count:4 type:EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields_class_()];
}

EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields *EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields_valueOfWithNSString_(NSString *name) {
  EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields_initialize();
  for (int i = 0; i < 4; i++) {
    EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields *e = EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields *EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields_fromOrdinal(NSUInteger ordinal) {
  EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields_initialize();
  if (ordinal >= 4) {
    return nil;
  }
  return EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsGigapaxosPaxospacketsBatchedCommit_Fields)
