# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: Product2
  product: Product2
  version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter

    folderitems:
    - title:
      url: /titlepage/
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage/
      output: pdf
      type: frontmatter

  - title: Introduction
    output: web, pdf
    folderitems:

    - title: Overview
      url: /p2_landing_page/
      output: web

  - title: Simple Workflow
    output: web, pdf
    folderitems:

    - title: Sample 1
      url: /p2_sample1/
      output: web, pdf

    - title: Sample 2
      url: /p2_sample2/
      output: web, pdf

    - title: Sample 3
      url: /p2_sample3/
      output: web, pdf

    - title: Sample 4
      url: /p2_sample4/
      output: web, pdf

    - title: Sample 5
      url: /p2_sample5/
      output: web, pdf

  - title: Complex Workflow
    output: web, pdf
    folderitems:

    - title: Sample 6
      url: /p2_sample6/
      output: web, pdf

    - title: Sample 7
      url: /p2_sample7/
      output: web, pdf

    - title: Sample 8
      url: /p2_sample8/
      output: web, pdf

    - title: Sample 9
      url: /p2_sample9/
      output: web, pdf

    - title: Sample 10
      url: /p2_sample10/
      output: web, pdf

    - title: Sample 11
      url: /p2_sample11/
      output: web, pdf

    - title: Sample 12
      url: /p2_sample12/
      output: web, pdf

    - title: Sample 13
      url: /p2_sample13/
      output: web, pdf

    - title: Sample 14
      url: /p2_sample14/
      output: web, pdf
