//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../src/edu/umass/cs/gnscommon/exceptions/server/InternalRequestException.java
//

#include "J2ObjC_source.h"
#include "edu/umass/cs/gnscommon/ResponseCode.h"
#include "edu/umass/cs/gnscommon/exceptions/server/InternalRequestException.h"
#include "edu/umass/cs/gnscommon/exceptions/server/ServerException.h"

inline jlong EduUmassCsGnscommonExceptionsServerInternalRequestException_get_serialVersionUID();
#define EduUmassCsGnscommonExceptionsServerInternalRequestException_serialVersionUID 6627620787610127842LL
J2OBJC_STATIC_FIELD_CONSTANT(EduUmassCsGnscommonExceptionsServerInternalRequestException, serialVersionUID, jlong)

@implementation EduUmassCsGnscommonExceptionsServerInternalRequestException

- (instancetype)initWithEduUmassCsGnscommonResponseCode:(EduUmassCsGnscommonResponseCode *)code
                                           withNSString:(NSString *)message {
  EduUmassCsGnscommonExceptionsServerInternalRequestException_initWithEduUmassCsGnscommonResponseCode_withNSString_(self, code, message);
  return self;
}

- (instancetype)initWithNSString:(NSString *)message {
  EduUmassCsGnscommonExceptionsServerInternalRequestException_initWithNSString_(self, message);
  return self;
}

- (instancetype)initWithNSException:(NSException *)throwable {
  EduUmassCsGnscommonExceptionsServerInternalRequestException_initWithNSException_(self, throwable);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithEduUmassCsGnscommonResponseCode:withNSString:);
  methods[1].selector = @selector(initWithNSString:);
  methods[2].selector = @selector(initWithNSException:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "J", .constantValue.asLong = EduUmassCsGnscommonExceptionsServerInternalRequestException_serialVersionUID, 0x1a, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LEduUmassCsGnscommonResponseCode;LNSString;", "LNSString;", "LNSException;" };
  static const J2ObjcClassInfo _EduUmassCsGnscommonExceptionsServerInternalRequestException = { "InternalRequestException", "edu.umass.cs.gnscommon.exceptions.server", ptrTable, methods, fields, 7, 0x1, 3, 1, -1, -1, -1, -1, -1 };
  return &_EduUmassCsGnscommonExceptionsServerInternalRequestException;
}

@end

void EduUmassCsGnscommonExceptionsServerInternalRequestException_initWithEduUmassCsGnscommonResponseCode_withNSString_(EduUmassCsGnscommonExceptionsServerInternalRequestException *self, EduUmassCsGnscommonResponseCode *code, NSString *message) {
  EduUmassCsGnscommonExceptionsServerServerException_initWithEduUmassCsGnscommonResponseCode_withNSString_(self, code, message);
}

EduUmassCsGnscommonExceptionsServerInternalRequestException *new_EduUmassCsGnscommonExceptionsServerInternalRequestException_initWithEduUmassCsGnscommonResponseCode_withNSString_(EduUmassCsGnscommonResponseCode *code, NSString *message) {
  J2OBJC_NEW_IMPL(EduUmassCsGnscommonExceptionsServerInternalRequestException, initWithEduUmassCsGnscommonResponseCode_withNSString_, code, message)
}

EduUmassCsGnscommonExceptionsServerInternalRequestException *create_EduUmassCsGnscommonExceptionsServerInternalRequestException_initWithEduUmassCsGnscommonResponseCode_withNSString_(EduUmassCsGnscommonResponseCode *code, NSString *message) {
  J2OBJC_CREATE_IMPL(EduUmassCsGnscommonExceptionsServerInternalRequestException, initWithEduUmassCsGnscommonResponseCode_withNSString_, code, message)
}

void EduUmassCsGnscommonExceptionsServerInternalRequestException_initWithNSString_(EduUmassCsGnscommonExceptionsServerInternalRequestException *self, NSString *message) {
  EduUmassCsGnscommonExceptionsServerServerException_initWithNSString_(self, message);
}

EduUmassCsGnscommonExceptionsServerInternalRequestException *new_EduUmassCsGnscommonExceptionsServerInternalRequestException_initWithNSString_(NSString *message) {
  J2OBJC_NEW_IMPL(EduUmassCsGnscommonExceptionsServerInternalRequestException, initWithNSString_, message)
}

EduUmassCsGnscommonExceptionsServerInternalRequestException *create_EduUmassCsGnscommonExceptionsServerInternalRequestException_initWithNSString_(NSString *message) {
  J2OBJC_CREATE_IMPL(EduUmassCsGnscommonExceptionsServerInternalRequestException, initWithNSString_, message)
}

void EduUmassCsGnscommonExceptionsServerInternalRequestException_initWithNSException_(EduUmassCsGnscommonExceptionsServerInternalRequestException *self, NSException *throwable) {
  EduUmassCsGnscommonExceptionsServerServerException_initWithNSException_(self, throwable);
}

EduUmassCsGnscommonExceptionsServerInternalRequestException *new_EduUmassCsGnscommonExceptionsServerInternalRequestException_initWithNSException_(NSException *throwable) {
  J2OBJC_NEW_IMPL(EduUmassCsGnscommonExceptionsServerInternalRequestException, initWithNSException_, throwable)
}

EduUmassCsGnscommonExceptionsServerInternalRequestException *create_EduUmassCsGnscommonExceptionsServerInternalRequestException_initWithNSException_(NSException *throwable) {
  J2OBJC_CREATE_IMPL(EduUmassCsGnscommonExceptionsServerInternalRequestException, initWithNSException_, throwable)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsGnscommonExceptionsServerInternalRequestException)
