#!/bin/bash
#echo $PWD

# should use matching gigapaxos properties with servers
java -ea -DgigapaxosConfig=conf/gigapaxos.client.singleNode.local.properties \
-Djava.util.logging.config.file=conf/logging.gns.properties \
-Djavax.net.ssl.trustStorePassword=qwerty \
-Djavax.net.ssl.trustStore=conf/trustStore/node100.jks \
-Djavax.net.ssl.keyStorePassword=qwerty \
-Djavax.net.ssl.keyStore=conf/keyStore/node100.jks -cp \
.:build/classes:build/test/classes:jars/GNSClient.jar $*
