#!/bin/bash
#echo $PWD
java -DgigapaxosConfig=conf/gigapaxos.client.local.properties \
-Djavax.net.ssl.trustStorePassword=qwerty  \
-Djavax.net.ssl.trustStore=conf/trustStore/node100.jks  \
-Djavax.net.ssl.keyStorePassword=qwerty  \
-Djavax.net.ssl.keyStore=conf/keyStore/node100.jks  \
-jar jars/GNS-CLI.jar $*