//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../gig_ios/src/edu/umass/cs/reconfiguration/reconfigurationutils/AbstractDemandProfile.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile")
#ifdef RESTRICT_EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile
#define INCLUDE_ALL_EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile 0
#else
#define INCLUDE_ALL_EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile 1
#endif
#undef RESTRICT_EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile

#if !defined (EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_) && (INCLUDE_ALL_EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile || defined(INCLUDE_EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile))
#define EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_

@class IOSClass;
@class JavaNetInetAddress;
@class JavaUtilArrayList;
@class OrgJsonJSONObject;
@protocol EduUmassCsGigapaxosInterfacesRequest;
@protocol EduUmassCsReconfigurationReconfigurationutilsInterfaceGetActiveIPs;

@interface EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile : NSObject {
 @public
  NSString *name_;
}

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)name;

- (EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile *)java_clone;

- (void)combineWithEduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile:(EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile *)update;

+ (EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile *)createDemandProfileWithOrgJsonJSONObject:(OrgJsonJSONObject *)json;

- (NSString *)getName;

- (OrgJsonJSONObject *)getStats;

- (void)justReconfigured;

- (void)register__WithEduUmassCsGigapaxosInterfacesRequest:(id<EduUmassCsGigapaxosInterfacesRequest>)request
                                    withJavaNetInetAddress:(JavaNetInetAddress *)sender
withEduUmassCsReconfigurationReconfigurationutilsInterfaceGetActiveIPs:(id<EduUmassCsReconfigurationReconfigurationutilsInterfaceGetActiveIPs>)nodeConfig;

- (void)reset;

- (JavaUtilArrayList *)shouldReconfigureWithJavaUtilArrayList:(JavaUtilArrayList *)curActives
withEduUmassCsReconfigurationReconfigurationutilsInterfaceGetActiveIPs:(id<EduUmassCsReconfigurationReconfigurationutilsInterfaceGetActiveIPs>)nodeConfig;

- (jboolean)shouldReport;

#pragma mark Protected

+ (EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile *)createDemandProfileWithIOSClass:(IOSClass *)clazz
                                                                                           withNSString:(NSString *)name;

+ (EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile *)createDemandProfileWithNSString:(NSString *)name;

#pragma mark Package-Private

+ (EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile *)createDemandProfileWithIOSClass:(IOSClass *)clazz
                                                                                  withOrgJsonJSONObject:(OrgJsonJSONObject *)json;

@end

J2OBJC_STATIC_INIT(EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile)

J2OBJC_FIELD_SETTER(EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile, name_, NSString *)

inline IOSClass *EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_get_C();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT IOSClass *EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_C;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile, C, IOSClass *)

FOUNDATION_EXPORT void EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_initWithNSString_(EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile *self, NSString *name);

FOUNDATION_EXPORT EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile *EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_createDemandProfileWithNSString_(NSString *name);

FOUNDATION_EXPORT EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile *EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_createDemandProfileWithIOSClass_withNSString_(IOSClass *clazz, NSString *name);

FOUNDATION_EXPORT EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile *EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_createDemandProfileWithOrgJsonJSONObject_(OrgJsonJSONObject *json);

FOUNDATION_EXPORT EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile *EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_createDemandProfileWithIOSClass_withOrgJsonJSONObject_(IOSClass *clazz, OrgJsonJSONObject *json);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile)

#endif

#if !defined (EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_Keys_) && (INCLUDE_ALL_EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile || defined(INCLUDE_EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_Keys))
#define EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_Keys_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_Keys_Enum) {
  EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_Keys_Enum_SERVICE_NAME = 0,
};

@interface EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_Keys : JavaLangEnum < NSCopying >

#pragma mark Public

+ (EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_Keys *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_Keys)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_Keys *EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_Keys_values_[];

inline EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_Keys *EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_Keys_get_SERVICE_NAME();
J2OBJC_ENUM_CONSTANT(EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_Keys, SERVICE_NAME)

FOUNDATION_EXPORT IOSObjectArray *EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_Keys_values();

FOUNDATION_EXPORT EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_Keys *EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_Keys_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_Keys *EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_Keys_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile_Keys)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsReconfigurationReconfigurationutilsAbstractDemandProfile")
