//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../gig_ios/src/org/json/JSONString.java
//

#include "J2ObjC_source.h"
#include "org/json/JSONString.h"

@interface OrgJsonJSONString : NSObject

@end

@implementation OrgJsonJSONString

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(toJSONString);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _OrgJsonJSONString = { "JSONString", "org.json", NULL, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_OrgJsonJSONString;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgJsonJSONString)
