//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../gig_ios/src/edu/umass/cs/nio/interfaces/Byteable.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsNioInterfacesByteable")
#ifdef RESTRICT_EduUmassCsNioInterfacesByteable
#define INCLUDE_ALL_EduUmassCsNioInterfacesByteable 0
#else
#define INCLUDE_ALL_EduUmassCsNioInterfacesByteable 1
#endif
#undef RESTRICT_EduUmassCsNioInterfacesByteable

#if !defined (EduUmassCsNioInterfacesByteable_) && (INCLUDE_ALL_EduUmassCsNioInterfacesByteable || defined(INCLUDE_EduUmassCsNioInterfacesByteable))
#define EduUmassCsNioInterfacesByteable_

@class IOSByteArray;

@protocol EduUmassCsNioInterfacesByteable < JavaObject >

- (IOSByteArray *)toBytes;

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsNioInterfacesByteable)

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsNioInterfacesByteable)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsNioInterfacesByteable")
