//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../gig_ios/src/edu/umass/cs/nio/AbstractJSONPacketDemultiplexer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsNioAbstractJSONPacketDemultiplexer")
#ifdef RESTRICT_EduUmassCsNioAbstractJSONPacketDemultiplexer
#define INCLUDE_ALL_EduUmassCsNioAbstractJSONPacketDemultiplexer 0
#else
#define INCLUDE_ALL_EduUmassCsNioAbstractJSONPacketDemultiplexer 1
#endif
#undef RESTRICT_EduUmassCsNioAbstractJSONPacketDemultiplexer

#if !defined (EduUmassCsNioAbstractJSONPacketDemultiplexer_) && (INCLUDE_ALL_EduUmassCsNioAbstractJSONPacketDemultiplexer || defined(INCLUDE_EduUmassCsNioAbstractJSONPacketDemultiplexer))
#define EduUmassCsNioAbstractJSONPacketDemultiplexer_

#define RESTRICT_EduUmassCsNioAbstractPacketDemultiplexer 1
#define INCLUDE_EduUmassCsNioAbstractPacketDemultiplexer 1
#include "edu/umass/cs/nio/AbstractPacketDemultiplexer.h"

#define RESTRICT_EduUmassCsNioInterfacesPacketDemultiplexer 1
#define INCLUDE_EduUmassCsNioInterfacesPacketDemultiplexer 1
#include "edu/umass/cs/nio/interfaces/PacketDemultiplexer.h"

@class EduUmassCsNioNioutilsNIOHeader;
@class IOSByteArray;
@class JavaLangInteger;
@class OrgJsonJSONObject;

@interface EduUmassCsNioAbstractJSONPacketDemultiplexer : EduUmassCsNioAbstractPacketDemultiplexer < EduUmassCsNioInterfacesPacketDemultiplexer >

#pragma mark Public

+ (OrgJsonJSONObject *)processHeaderStaticWithByteArray:(IOSByteArray *)message
                                                withInt:(jint)offset
                     withEduUmassCsNioNioutilsNIOHeader:(EduUmassCsNioNioutilsNIOHeader *)header
                                            withBoolean:(jboolean)cacheStringified;

#pragma mark Protected

- (instancetype)init;

- (instancetype)initWithInt:(jint)threadPoolSize;

- (JavaLangInteger *)getPacketTypeWithId:(OrgJsonJSONObject *)json;

- (jboolean)isCongestedWithEduUmassCsNioNioutilsNIOHeader:(EduUmassCsNioNioutilsNIOHeader *)header;

- (jboolean)matchesTypeWithId:(id)message;

- (OrgJsonJSONObject *)processHeaderWithByteArray:(IOSByteArray *)message
                                          withInt:(jint)offset
               withEduUmassCsNioNioutilsNIOHeader:(EduUmassCsNioNioutilsNIOHeader *)header
                                      withBoolean:(jboolean)cacheStringified;

- (OrgJsonJSONObject *)processHeaderWithByteArray:(IOSByteArray *)message
               withEduUmassCsNioNioutilsNIOHeader:(EduUmassCsNioNioutilsNIOHeader *)header;

- (OrgJsonJSONObject *)processHeaderWithByteArray:(IOSByteArray *)message
               withEduUmassCsNioNioutilsNIOHeader:(EduUmassCsNioNioutilsNIOHeader *)header
                                      withBoolean:(jboolean)cacheStringified;

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsNioAbstractJSONPacketDemultiplexer)

FOUNDATION_EXPORT void EduUmassCsNioAbstractJSONPacketDemultiplexer_initWithInt_(EduUmassCsNioAbstractJSONPacketDemultiplexer *self, jint threadPoolSize);

FOUNDATION_EXPORT void EduUmassCsNioAbstractJSONPacketDemultiplexer_init(EduUmassCsNioAbstractJSONPacketDemultiplexer *self);

FOUNDATION_EXPORT OrgJsonJSONObject *EduUmassCsNioAbstractJSONPacketDemultiplexer_processHeaderStaticWithByteArray_withInt_withEduUmassCsNioNioutilsNIOHeader_withBoolean_(IOSByteArray *message, jint offset, EduUmassCsNioNioutilsNIOHeader *header, jboolean cacheStringified);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsNioAbstractJSONPacketDemultiplexer)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsNioAbstractJSONPacketDemultiplexer")
