//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../gig_ios/src/edu/umass/cs/gigapaxos/examples/PaxosAppRequest.java
//

#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "edu/umass/cs/gigapaxos/examples/PaxosAppRequest.h"
#include "edu/umass/cs/gigapaxos/interfaces/ClientRequest.h"
#include "edu/umass/cs/gigapaxos/interfaces/Request.h"
#include "edu/umass/cs/nio/JSONPacket.h"
#include "edu/umass/cs/nio/interfaces/IntegerPacketType.h"
#include "edu/umass/cs/utils/Summarizable.h"
#include "edu/umass/cs/utils/Util.h"
#include "java/io/PrintStream.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/Integer.h"
#include "java/lang/Long.h"
#include "java/lang/Math.h"
#include "java/lang/RuntimeException.h"
#include "java/lang/System.h"
#include "java/net/InetSocketAddress.h"
#include "java/util/HashMap.h"
#include "org/json/JSONException.h"
#include "org/json/JSONObject.h"

@interface EduUmassCsGigapaxosExamplesPaxosAppRequest () {
 @public
  NSString *name_;
  jint epoch_;
  jlong id__;
  jboolean stop_;
  NSString *value_;
  NSString *response_;
  JavaNetInetSocketAddress *clientAddress_;
  jboolean coordType_;
}

@end

J2OBJC_FIELD_SETTER(EduUmassCsGigapaxosExamplesPaxosAppRequest, name_, NSString *)
J2OBJC_FIELD_SETTER(EduUmassCsGigapaxosExamplesPaxosAppRequest, value_, NSString *)
J2OBJC_FIELD_SETTER(EduUmassCsGigapaxosExamplesPaxosAppRequest, response_, NSString *)
J2OBJC_FIELD_SETTER(EduUmassCsGigapaxosExamplesPaxosAppRequest, clientAddress_, JavaNetInetSocketAddress *)

@interface EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType () {
 @public
  jint number_;
}

@end

inline JavaUtilHashMap *EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_get_numbers();
inline JavaUtilHashMap *EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_set_numbers(JavaUtilHashMap *value);
static JavaUtilHashMap *EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_numbers;
J2OBJC_STATIC_FIELD_OBJ(EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType, numbers, JavaUtilHashMap *)

__attribute__((unused)) static void EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_initWithInt_withNSString_withInt_(EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType *self, jint t, NSString *__name, jint __ordinal);

__attribute__((unused)) static void EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys_initWithNSString_withInt_(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *self, NSString *__name, jint __ordinal);

@implementation EduUmassCsGigapaxosExamplesPaxosAppRequest

- (instancetype)initWithNSString:(NSString *)name
                         withInt:(jint)epoch
                        withLong:(jlong)id_
                    withNSString:(NSString *)value
withEduUmassCsNioInterfacesIntegerPacketType:(id<EduUmassCsNioInterfacesIntegerPacketType>)type
                     withBoolean:(jboolean)stop {
  EduUmassCsGigapaxosExamplesPaxosAppRequest_initWithNSString_withInt_withLong_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_(self, name, epoch, id_, value, type, stop);
  return self;
}

- (instancetype)initWithNSString:(NSString *)name
                        withLong:(jlong)id_
                    withNSString:(NSString *)value
withEduUmassCsNioInterfacesIntegerPacketType:(id<EduUmassCsNioInterfacesIntegerPacketType>)type
                     withBoolean:(jboolean)stop {
  EduUmassCsGigapaxosExamplesPaxosAppRequest_initWithNSString_withLong_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_(self, name, id_, value, type, stop);
  return self;
}

- (instancetype)initWithNSString:(NSString *)name
                    withNSString:(NSString *)value
withEduUmassCsNioInterfacesIntegerPacketType:(id<EduUmassCsNioInterfacesIntegerPacketType>)type
                     withBoolean:(jboolean)stop {
  EduUmassCsGigapaxosExamplesPaxosAppRequest_initWithNSString_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_(self, name, value, type, stop);
  return self;
}

- (instancetype)initWithOrgJsonJSONObject:(OrgJsonJSONObject *)json {
  EduUmassCsGigapaxosExamplesPaxosAppRequest_initWithOrgJsonJSONObject_(self, json);
  return self;
}

- (id<EduUmassCsNioInterfacesIntegerPacketType>)getRequestType {
  return EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_getPacketTypeWithInt_(self->type_);
}

- (NSString *)getServiceName {
  return self->name_;
}

- (NSString *)getValue {
  return self->value_;
}

- (jlong)getRequestID {
  return self->id__;
}

- (OrgJsonJSONObject *)toJSONObjectImpl {
  OrgJsonJSONObject *json = create_OrgJsonJSONObject_init();
  [json putWithNSString:[((EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, SERVICE_NAME))) description] withId:self->name_];
  [json putWithNSString:[((EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, EPOCH))) description] withInt:self->epoch_];
  [json putWithNSString:[((EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, REQUEST_ID))) description] withLong:self->id__];
  [json putWithNSString:[((EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, STOP))) description] withBoolean:self->stop_];
  [json putWithNSString:[((EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, REQUEST_VALUE))) description] withId:self->value_];
  [json putWithNSString:[((EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, IS_COORDINATION))) description] withBoolean:self->coordType_];
  if (self->clientAddress_ != nil) [json putWithNSString:[((EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, CLIENT_ADDRESS))) description] withId:[((JavaNetInetSocketAddress *) nil_chk(self->clientAddress_)) description]];
  [json putOptWithNSString:[((EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, RESPONSE_VALUE))) description] withId:self->response_];
  return json;
}

- (JavaNetInetSocketAddress *)getSenderAddress {
  return self->clientAddress_;
}

- (jboolean)needsCoordination {
  return self->coordType_;
}

- (void)setNeedsCoordinationWithBoolean:(jboolean)b {
  self->coordType_ = b;
}

- (JavaNetInetSocketAddress *)getClientAddress {
  return self->clientAddress_;
}

- (id<EduUmassCsGigapaxosInterfacesClientRequest>)getResponse {
  return create_EduUmassCsGigapaxosExamplesPaxosAppRequest_initWithNSString_withInt_withLong_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_(self->name_, self->epoch_, self->id__, [((EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, ACK))) description], EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_getPacketTypeWithInt_(type_), self->stop_);
}

+ (void)mainWithNSStringArray:(IOSObjectArray *)args {
  EduUmassCsGigapaxosExamplesPaxosAppRequest_mainWithNSStringArray_(args);
}

- (void)setResponseWithNSString:(NSString *)response {
  JreStrongAssign(&self->response_, response);
}

- (id)getSummary {
  return EduUmassCsGigapaxosInterfacesRequest_getSummary(self);
}

- (IOSByteArray *)toBytes {
  return EduUmassCsGigapaxosInterfacesRequest_toBytes(self);
}

- (id)getSummaryWithBoolean:(jboolean)arg0 {
  return EduUmassCsUtilsSummarizable_getSummaryWithBoolean_(self, arg0);
}

- (void)dealloc {
  RELEASE_(name_);
  RELEASE_(value_);
  RELEASE_(response_);
  RELEASE_(clientAddress_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 3, 4, -1, -1, -1 },
    { NULL, "LEduUmassCsNioInterfacesIntegerPacketType;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "J", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgJsonJSONObject;", 0x1, -1, -1, 4, -1, -1, -1 },
    { NULL, "LJavaNetInetSocketAddress;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 5, 6, -1, -1, -1, -1 },
    { NULL, "LJavaNetInetSocketAddress;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsGigapaxosInterfacesClientRequest;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 7, 8, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 9, 10, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithNSString:withInt:withLong:withNSString:withEduUmassCsNioInterfacesIntegerPacketType:withBoolean:);
  methods[1].selector = @selector(initWithNSString:withLong:withNSString:withEduUmassCsNioInterfacesIntegerPacketType:withBoolean:);
  methods[2].selector = @selector(initWithNSString:withNSString:withEduUmassCsNioInterfacesIntegerPacketType:withBoolean:);
  methods[3].selector = @selector(initWithOrgJsonJSONObject:);
  methods[4].selector = @selector(getRequestType);
  methods[5].selector = @selector(getServiceName);
  methods[6].selector = @selector(getValue);
  methods[7].selector = @selector(getRequestID);
  methods[8].selector = @selector(toJSONObjectImpl);
  methods[9].selector = @selector(getSenderAddress);
  methods[10].selector = @selector(needsCoordination);
  methods[11].selector = @selector(setNeedsCoordinationWithBoolean:);
  methods[12].selector = @selector(getClientAddress);
  methods[13].selector = @selector(getResponse);
  methods[14].selector = @selector(mainWithNSStringArray:);
  methods[15].selector = @selector(setResponseWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "name_", "LNSString;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "epoch_", "I", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "id__", "J", .constantValue.asLong = 0, 0x12, 11, -1, -1, -1 },
    { "stop_", "Z", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "value_", "LNSString;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "response_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "clientAddress_", "LJavaNetInetSocketAddress;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "coordType_", "Z", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;IJLNSString;LEduUmassCsNioInterfacesIntegerPacketType;Z", "LNSString;JLNSString;LEduUmassCsNioInterfacesIntegerPacketType;Z", "LNSString;LNSString;LEduUmassCsNioInterfacesIntegerPacketType;Z", "LOrgJsonJSONObject;", "LOrgJsonJSONException;", "setNeedsCoordination", "Z", "main", "[LNSString;", "setResponse", "LNSString;", "id", "LEduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType;LEduUmassCsGigapaxosExamplesPaxosAppRequest_Keys;" };
  static const J2ObjcClassInfo _EduUmassCsGigapaxosExamplesPaxosAppRequest = { "PaxosAppRequest", "edu.umass.cs.gigapaxos.examples", ptrTable, methods, fields, 7, 0x1, 16, 8, -1, 12, -1, -1, -1 };
  return &_EduUmassCsGigapaxosExamplesPaxosAppRequest;
}

@end

void EduUmassCsGigapaxosExamplesPaxosAppRequest_initWithNSString_withInt_withLong_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_(EduUmassCsGigapaxosExamplesPaxosAppRequest *self, NSString *name, jint epoch, jlong id_, NSString *value, id<EduUmassCsNioInterfacesIntegerPacketType> type, jboolean stop) {
  EduUmassCsNioJSONPacket_initWithEduUmassCsNioInterfacesIntegerPacketType_(self, type);
  JreStrongAssign(&self->response_, nil);
  JreStrongAssign(&self->clientAddress_, nil);
  self->coordType_ = true;
  JreStrongAssign(&self->name_, name);
  self->epoch_ = epoch;
  self->id__ = id_;
  self->stop_ = stop;
  JreStrongAssign(&self->value_, value);
}

EduUmassCsGigapaxosExamplesPaxosAppRequest *new_EduUmassCsGigapaxosExamplesPaxosAppRequest_initWithNSString_withInt_withLong_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_(NSString *name, jint epoch, jlong id_, NSString *value, id<EduUmassCsNioInterfacesIntegerPacketType> type, jboolean stop) {
  J2OBJC_NEW_IMPL(EduUmassCsGigapaxosExamplesPaxosAppRequest, initWithNSString_withInt_withLong_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_, name, epoch, id_, value, type, stop)
}

EduUmassCsGigapaxosExamplesPaxosAppRequest *create_EduUmassCsGigapaxosExamplesPaxosAppRequest_initWithNSString_withInt_withLong_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_(NSString *name, jint epoch, jlong id_, NSString *value, id<EduUmassCsNioInterfacesIntegerPacketType> type, jboolean stop) {
  J2OBJC_CREATE_IMPL(EduUmassCsGigapaxosExamplesPaxosAppRequest, initWithNSString_withInt_withLong_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_, name, epoch, id_, value, type, stop)
}

void EduUmassCsGigapaxosExamplesPaxosAppRequest_initWithNSString_withLong_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_(EduUmassCsGigapaxosExamplesPaxosAppRequest *self, NSString *name, jlong id_, NSString *value, id<EduUmassCsNioInterfacesIntegerPacketType> type, jboolean stop) {
  EduUmassCsGigapaxosExamplesPaxosAppRequest_initWithNSString_withInt_withLong_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_(self, name, 0, id_, value, type, stop);
}

EduUmassCsGigapaxosExamplesPaxosAppRequest *new_EduUmassCsGigapaxosExamplesPaxosAppRequest_initWithNSString_withLong_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_(NSString *name, jlong id_, NSString *value, id<EduUmassCsNioInterfacesIntegerPacketType> type, jboolean stop) {
  J2OBJC_NEW_IMPL(EduUmassCsGigapaxosExamplesPaxosAppRequest, initWithNSString_withLong_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_, name, id_, value, type, stop)
}

EduUmassCsGigapaxosExamplesPaxosAppRequest *create_EduUmassCsGigapaxosExamplesPaxosAppRequest_initWithNSString_withLong_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_(NSString *name, jlong id_, NSString *value, id<EduUmassCsNioInterfacesIntegerPacketType> type, jboolean stop) {
  J2OBJC_CREATE_IMPL(EduUmassCsGigapaxosExamplesPaxosAppRequest, initWithNSString_withLong_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_, name, id_, value, type, stop)
}

void EduUmassCsGigapaxosExamplesPaxosAppRequest_initWithNSString_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_(EduUmassCsGigapaxosExamplesPaxosAppRequest *self, NSString *name, NSString *value, id<EduUmassCsNioInterfacesIntegerPacketType> type, jboolean stop) {
  EduUmassCsGigapaxosExamplesPaxosAppRequest_initWithNSString_withInt_withLong_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_(self, name, 0, JreFpToLong((JavaLangMath_random() * JavaLangLong_MAX_VALUE)), value, type, stop);
}

EduUmassCsGigapaxosExamplesPaxosAppRequest *new_EduUmassCsGigapaxosExamplesPaxosAppRequest_initWithNSString_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_(NSString *name, NSString *value, id<EduUmassCsNioInterfacesIntegerPacketType> type, jboolean stop) {
  J2OBJC_NEW_IMPL(EduUmassCsGigapaxosExamplesPaxosAppRequest, initWithNSString_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_, name, value, type, stop)
}

EduUmassCsGigapaxosExamplesPaxosAppRequest *create_EduUmassCsGigapaxosExamplesPaxosAppRequest_initWithNSString_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_(NSString *name, NSString *value, id<EduUmassCsNioInterfacesIntegerPacketType> type, jboolean stop) {
  J2OBJC_CREATE_IMPL(EduUmassCsGigapaxosExamplesPaxosAppRequest, initWithNSString_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_, name, value, type, stop)
}

void EduUmassCsGigapaxosExamplesPaxosAppRequest_initWithOrgJsonJSONObject_(EduUmassCsGigapaxosExamplesPaxosAppRequest *self, OrgJsonJSONObject *json) {
  EduUmassCsNioJSONPacket_initWithOrgJsonJSONObject_(self, json);
  JreStrongAssign(&self->response_, nil);
  JreStrongAssign(&self->clientAddress_, nil);
  self->coordType_ = true;
  JreStrongAssign(&self->name_, [((OrgJsonJSONObject *) nil_chk(json)) getStringWithNSString:[((EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, SERVICE_NAME))) description]]);
  self->epoch_ = [json getIntWithNSString:[((EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, EPOCH))) description]];
  self->id__ = [json getLongWithNSString:[((EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, REQUEST_ID))) description]];
  self->stop_ = [json getBooleanWithNSString:[((EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, STOP))) description]];
  JreStrongAssign(&self->value_, [json getStringWithNSString:[((EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, REQUEST_VALUE))) description]]);
  self->coordType_ = ([json hasWithNSString:[((EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, IS_COORDINATION))) description]] ? [json getBooleanWithNSString:[JreLoadEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, IS_COORDINATION) description]] : false);
  JreStrongAssign(&self->clientAddress_, [json hasWithNSString:[((EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, CLIENT_ADDRESS))) description]] ? EduUmassCsUtilsUtil_getInetSocketAddressFromStringWithNSString_([json getStringWithNSString:[JreLoadEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, CLIENT_ADDRESS) description]]) : nil);
  JreStrongAssign(&self->response_, [json hasWithNSString:[((EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, RESPONSE_VALUE))) description]] ? [json getStringWithNSString:[JreLoadEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, REQUEST_VALUE) description]] : nil);
}

EduUmassCsGigapaxosExamplesPaxosAppRequest *new_EduUmassCsGigapaxosExamplesPaxosAppRequest_initWithOrgJsonJSONObject_(OrgJsonJSONObject *json) {
  J2OBJC_NEW_IMPL(EduUmassCsGigapaxosExamplesPaxosAppRequest, initWithOrgJsonJSONObject_, json)
}

EduUmassCsGigapaxosExamplesPaxosAppRequest *create_EduUmassCsGigapaxosExamplesPaxosAppRequest_initWithOrgJsonJSONObject_(OrgJsonJSONObject *json) {
  J2OBJC_CREATE_IMPL(EduUmassCsGigapaxosExamplesPaxosAppRequest, initWithOrgJsonJSONObject_, json)
}

void EduUmassCsGigapaxosExamplesPaxosAppRequest_mainWithNSStringArray_(IOSObjectArray *args) {
  EduUmassCsGigapaxosExamplesPaxosAppRequest_initialize();
  EduUmassCsGigapaxosExamplesPaxosAppRequest *request = create_EduUmassCsGigapaxosExamplesPaxosAppRequest_initWithNSString_withInt_withLong_withNSString_withEduUmassCsNioInterfacesIntegerPacketType_withBoolean_(@"name1", 0, 0, @"request1", JreLoadEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType, DEFAULT_APP_REQUEST), false);
  [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, out))) printlnWithId:request];
  @try {
    EduUmassCsGigapaxosExamplesPaxosAppRequest *request2 = (create_EduUmassCsGigapaxosExamplesPaxosAppRequest_initWithOrgJsonJSONObject_([request toJSONObject]));
    JreAssert((([((NSString *) nil_chk([request description])) isEqual:[request2 description]])), (@"edu/umass/cs/gigapaxos/examples/PaxosAppRequest.java:191 condition failed: assert (request.toString().equals(request2.toString()));"));
    [JreLoadStatic(JavaLangSystem, out) printlnWithNSString:@"SUCCESS"];
  }
  @catch (OrgJsonJSONException *je) {
    [((OrgJsonJSONException *) nil_chk(je)) printStackTrace];
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsGigapaxosExamplesPaxosAppRequest)

J2OBJC_INITIALIZED_DEFN(EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType)

EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType *EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_values_[2];

@implementation EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType

+ (EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType *)getPacketTypeWithInt:(jint)type {
  return EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_getPacketTypeWithInt_(type);
}

- (jint)getInt {
  return self->number_;
}

+ (IOSObjectArray *)values {
  return EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_values();
}

+ (EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType *)valueOfWithNSString:(NSString *)name {
  return EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_valueOfWithNSString_(name);
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LEduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType;", 0x9, 0, 1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[LEduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType;", 0x9, 2, 3, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(getPacketTypeWithInt:);
  methods[1].selector = @selector(getInt);
  methods[2].selector = @selector(values);
  methods[3].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "DEFAULT_APP_REQUEST", "LEduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType;", .constantValue.asLong = 0, 0x4019, -1, 4, -1, -1 },
    { "APP_REQUEST_NO_COORDINATION", "LEduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType;", .constantValue.asLong = 0, 0x4019, -1, 5, -1, -1 },
    { "numbers", "LJavaUtilHashMap;", .constantValue.asLong = 0, 0xa, -1, 6, 7, -1 },
    { "number_", "I", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "getPacketType", "I", "valueOf", "LNSString;", &JreEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType, DEFAULT_APP_REQUEST), &JreEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType, APP_REQUEST_NO_COORDINATION), &EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_numbers, "Ljava/util/HashMap<Ljava/lang/Integer;Ledu/umass/cs/gigapaxos/examples/PaxosAppRequest$PacketType;>;", "LEduUmassCsGigapaxosExamplesPaxosAppRequest;", "Ljava/lang/Enum<Ledu/umass/cs/gigapaxos/examples/PaxosAppRequest$PacketType;>;Ledu/umass/cs/nio/interfaces/IntegerPacketType;" };
  static const J2ObjcClassInfo _EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType = { "PacketType", "edu.umass.cs.gigapaxos.examples", ptrTable, methods, fields, 7, 0x4019, 4, 4, 8, -1, -1, 9, -1 };
  return &_EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType;
}

+ (void)initialize {
  if (self == [EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 2 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    (JreEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType, DEFAULT_APP_REQUEST) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_initWithInt_withNSString_withInt_(e, 401, @"DEFAULT_APP_REQUEST", 0);
    (JreEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType, APP_REQUEST_NO_COORDINATION) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_initWithInt_withNSString_withInt_(e, 402, @"APP_REQUEST_NO_COORDINATION", 1);
    JreStrongAssignAndConsume(&EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_numbers, new_JavaUtilHashMap_init());
    {
      {
        IOSObjectArray *a__ = EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_values();
        EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType * const *b__ = ((IOSObjectArray *) nil_chk(a__))->buffer_;
        EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType * const *e__ = b__ + a__->size_;
        while (b__ < e__) {
          EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType *type = *b__++;
          if (![((JavaUtilHashMap *) nil_chk(EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_numbers)) containsKeyWithId:JavaLangInteger_valueOfWithInt_(((EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType *) nil_chk(type))->number_)]) {
            [((JavaUtilHashMap *) nil_chk(EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_numbers)) putWithId:JavaLangInteger_valueOfWithInt_(type->number_) withId:type];
          }
          else {
            JreAssert((false), (@"Duplicate or inconsistent enum type"));
            @throw create_JavaLangRuntimeException_initWithNSString_(@"Duplicate or inconsistent enum type");
          }
        }
      }
    }
    J2OBJC_SET_INITIALIZED(EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType)
  }
}

@end

EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType *EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_getPacketTypeWithInt_(jint type) {
  EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_initialize();
  return [((JavaUtilHashMap *) nil_chk(EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_numbers)) getWithId:JavaLangInteger_valueOfWithInt_(type)];
}

void EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_initWithInt_withNSString_withInt_(EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType *self, jint t, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
  self->number_ = t;
}

IOSObjectArray *EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_values() {
  EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_initialize();
  return [IOSObjectArray arrayWithObjects:EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_values_ count:2 type:EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_class_()];
}

EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType *EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_valueOfWithNSString_(NSString *name) {
  EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_initialize();
  for (int i = 0; i < 2; i++) {
    EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType *e = EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType *EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_fromOrdinal(NSUInteger ordinal) {
  EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_initialize();
  if (ordinal >= 2) {
    return nil;
  }
  return EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsGigapaxosExamplesPaxosAppRequest_PacketType)

J2OBJC_INITIALIZED_DEFN(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys)

EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys_values_[9];

@implementation EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys

+ (IOSObjectArray *)values {
  return EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys_values();
}

+ (EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *)valueOfWithNSString:(NSString *)name {
  return EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys_valueOfWithNSString_(name);
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "[LEduUmassCsGigapaxosExamplesPaxosAppRequest_Keys;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsGigapaxosExamplesPaxosAppRequest_Keys;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(values);
  methods[1].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "SERVICE_NAME", "LEduUmassCsGigapaxosExamplesPaxosAppRequest_Keys;", .constantValue.asLong = 0, 0x4019, -1, 2, -1, -1 },
    { "EPOCH", "LEduUmassCsGigapaxosExamplesPaxosAppRequest_Keys;", .constantValue.asLong = 0, 0x4019, -1, 3, -1, -1 },
    { "REQUEST_ID", "LEduUmassCsGigapaxosExamplesPaxosAppRequest_Keys;", .constantValue.asLong = 0, 0x4019, -1, 4, -1, -1 },
    { "REQUEST_VALUE", "LEduUmassCsGigapaxosExamplesPaxosAppRequest_Keys;", .constantValue.asLong = 0, 0x4019, -1, 5, -1, -1 },
    { "STOP", "LEduUmassCsGigapaxosExamplesPaxosAppRequest_Keys;", .constantValue.asLong = 0, 0x4019, -1, 6, -1, -1 },
    { "IS_COORDINATION", "LEduUmassCsGigapaxosExamplesPaxosAppRequest_Keys;", .constantValue.asLong = 0, 0x4019, -1, 7, -1, -1 },
    { "CLIENT_ADDRESS", "LEduUmassCsGigapaxosExamplesPaxosAppRequest_Keys;", .constantValue.asLong = 0, 0x4019, -1, 8, -1, -1 },
    { "ACK", "LEduUmassCsGigapaxosExamplesPaxosAppRequest_Keys;", .constantValue.asLong = 0, 0x4019, -1, 9, -1, -1 },
    { "RESPONSE_VALUE", "LEduUmassCsGigapaxosExamplesPaxosAppRequest_Keys;", .constantValue.asLong = 0, 0x4019, -1, 10, -1, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "LNSString;", &JreEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, SERVICE_NAME), &JreEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, EPOCH), &JreEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, REQUEST_ID), &JreEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, REQUEST_VALUE), &JreEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, STOP), &JreEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, IS_COORDINATION), &JreEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, CLIENT_ADDRESS), &JreEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, ACK), &JreEnum(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys, RESPONSE_VALUE), "LEduUmassCsGigapaxosExamplesPaxosAppRequest;", "Ljava/lang/Enum<Ledu/umass/cs/gigapaxos/examples/PaxosAppRequest$Keys;>;" };
  static const J2ObjcClassInfo _EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys = { "Keys", "edu.umass.cs.gigapaxos.examples", ptrTable, methods, fields, 7, 0x4019, 2, 9, 11, -1, -1, 12, -1 };
  return &_EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys;
}

+ (void)initialize {
  if (self == [EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 9 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    id names[] = {
      @"SERVICE_NAME", @"EPOCH", @"REQUEST_ID", @"REQUEST_VALUE", @"STOP", @"IS_COORDINATION", @"CLIENT_ADDRESS", @"ACK", @"RESPONSE_VALUE",
    };
    for (jint i = 0; i < 9; i++) {
      (EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys_values_[i] = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
      EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys_initWithNSString_withInt_(e, names[i], i);
    }
    J2OBJC_SET_INITIALIZED(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys)
  }
}

@end

void EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys_initWithNSString_withInt_(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

IOSObjectArray *EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys_values() {
  EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys_initialize();
  return [IOSObjectArray arrayWithObjects:EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys_values_ count:9 type:EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys_class_()];
}

EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys_valueOfWithNSString_(NSString *name) {
  EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys_initialize();
  for (int i = 0; i < 9; i++) {
    EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *e = EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys *EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys_fromOrdinal(NSUInteger ordinal) {
  EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys_initialize();
  if (ordinal >= 9) {
    return nil;
  }
  return EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsGigapaxosExamplesPaxosAppRequest_Keys)
