//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../src/edu/umass/cs/gnscommon/packets/CommandPacket.java
//

#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "edu/umass/cs/gigapaxos/PaxosConfig.h"
#include "edu/umass/cs/gigapaxos/interfaces/ClientRequest.h"
#include "edu/umass/cs/gnsclient/client/CommandUtils.h"
#include "edu/umass/cs/gnsclient/client/GNSClientConfig.h"
#include "edu/umass/cs/gnscommon/CommandType.h"
#include "edu/umass/cs/gnscommon/GNSProtocol.h"
#include "edu/umass/cs/gnscommon/ResponseCode.h"
#include "edu/umass/cs/gnscommon/exceptions/client/ClientException.h"
#include "edu/umass/cs/gnscommon/packets/CommandPacket.h"
#include "edu/umass/cs/gnscommon/packets/ResponsePacket.h"
#include "edu/umass/cs/gnscommon/utils/JSONByteConverter.h"
#include "edu/umass/cs/gnsserver/gnsapp/packet/BasicPacketWithClientAddress.h"
#include "edu/umass/cs/gnsserver/gnsapp/packet/Packet.h"
#include "edu/umass/cs/nio/JSONPacket.h"
#include "edu/umass/cs/nio/MessageNIOTransport.h"
#include "edu/umass/cs/nio/interfaces/IntegerPacketType.h"
#include "edu/umass/cs/reconfiguration/interfaces/ReplicableRequest.h"
#include "edu/umass/cs/reconfiguration/reconfigurationutils/RequestParseException.h"
#include "edu/umass/cs/utils/Config.h"
#include "edu/umass/cs/utils/Summarizable.h"
#include "edu/umass/cs/utils/Util.h"
#include "java/io/IOException.h"
#include "java/io/UnsupportedEncodingException.h"
#include "java/lang/Boolean.h"
#include "java/lang/ClassCastException.h"
#include "java/lang/Double.h"
#include "java/lang/Enum.h"
#include "java/lang/Exception.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/Integer.h"
#include "java/lang/InterruptedException.h"
#include "java/lang/Long.h"
#include "java/lang/RuntimeException.h"
#include "java/net/InetSocketAddress.h"
#include "java/nio/Buffer.h"
#include "java/nio/ByteBuffer.h"
#include "java/util/Arrays.h"
#include "java/util/HashMap.h"
#include "java/util/Iterator.h"
#include "java/util/List.h"
#include "java/util/Map.h"
#include "org/json/JSONArray.h"
#include "org/json/JSONException.h"
#include "org/json/JSONObject.h"

@class EduUmassCsGnscommonPacketsCommandPacket_ByteMode;

@interface EduUmassCsGnscommonPacketsCommandPacket () {
 @public
  jlong clientRequestId_;
  OrgJsonJSONObject *command_;
  jboolean forceCoordination_;
  id result_;
  jboolean executed_;
}

+ (OrgJsonJSONObject *)fromBytesStringerHackWithJavaNioByteBuffer:(JavaNioByteBuffer *)buf;

+ (OrgJsonJSONObject *)getJSONObjectWithJavaNioByteBuffer:(JavaNioByteBuffer *)bbuf
     withEduUmassCsGnscommonPacketsCommandPacket_ByteMode:(EduUmassCsGnscommonPacketsCommandPacket_ByteMode *)mode;

- (JavaNioByteBuffer *)toByteBufferWithOuterFields;

- (IOSByteArray *)appendByteifiedInnerJSONCommandWithJavaNioByteBuffer:(JavaNioByteBuffer *)bbuf
                                                         withByteArray:(IOSByteArray *)inner;

- (IOSByteArray *)toBytesWingItAsStringWithJavaNioByteBuffer:(JavaNioByteBuffer *)buf
                                       withOrgJsonJSONObject:(OrgJsonJSONObject *)json;

- (void)putBackRemovedWithJavaLangInteger:(JavaLangInteger *)commandType;

- (IOSByteArray *)handleSerializationExceptionWithJavaLangException:(JavaLangException *)e
                                                withJavaLangInteger:(JavaLangInteger *)commandType;

- (IOSByteArray *)toJSONBytes;

- (NSString *)getRespStr;

+ (id)getResultValueFromStringWithNSString:(NSString *)str;

@end

J2OBJC_FIELD_SETTER(EduUmassCsGnscommonPacketsCommandPacket, command_, OrgJsonJSONObject *)
J2OBJC_FIELD_SETTER(EduUmassCsGnscommonPacketsCommandPacket, result_, id)

inline NSString *EduUmassCsGnscommonPacketsCommandPacket_get_QID();
static NSString *EduUmassCsGnscommonPacketsCommandPacket_QID;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduUmassCsGnscommonPacketsCommandPacket, QID, NSString *)

inline NSString *EduUmassCsGnscommonPacketsCommandPacket_get_COMMAND();
static NSString *EduUmassCsGnscommonPacketsCommandPacket_COMMAND;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduUmassCsGnscommonPacketsCommandPacket, COMMAND, NSString *)

inline jboolean EduUmassCsGnscommonPacketsCommandPacket_get_SUPPORT_OLD_PROTOCOL();
#define EduUmassCsGnscommonPacketsCommandPacket_SUPPORT_OLD_PROTOCOL true
J2OBJC_STATIC_FIELD_CONSTANT(EduUmassCsGnscommonPacketsCommandPacket, SUPPORT_OLD_PROTOCOL, jboolean)

inline NSString *EduUmassCsGnscommonPacketsCommandPacket_get_OLD_COMMAND_PACKET_REQUESTID();
static NSString *EduUmassCsGnscommonPacketsCommandPacket_OLD_COMMAND_PACKET_REQUESTID = @"clientreqID";
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduUmassCsGnscommonPacketsCommandPacket, OLD_COMMAND_PACKET_REQUESTID, NSString *)

inline NSString *EduUmassCsGnscommonPacketsCommandPacket_get_OLD_COMMAND_PACKET_COMMAND();
static NSString *EduUmassCsGnscommonPacketsCommandPacket_OLD_COMMAND_PACKET_COMMAND = @"command";
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduUmassCsGnscommonPacketsCommandPacket, OLD_COMMAND_PACKET_COMMAND, NSString *)

inline EduUmassCsGnscommonPacketsCommandPacket_ByteMode *EduUmassCsGnscommonPacketsCommandPacket_get_byteMode();
static EduUmassCsGnscommonPacketsCommandPacket_ByteMode *EduUmassCsGnscommonPacketsCommandPacket_byteMode;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduUmassCsGnscommonPacketsCommandPacket, byteMode, EduUmassCsGnscommonPacketsCommandPacket_ByteMode *)

__attribute__((unused)) static OrgJsonJSONObject *EduUmassCsGnscommonPacketsCommandPacket_fromBytesStringerHackWithJavaNioByteBuffer_(JavaNioByteBuffer *buf);

__attribute__((unused)) static OrgJsonJSONObject *EduUmassCsGnscommonPacketsCommandPacket_getJSONObjectWithJavaNioByteBuffer_withEduUmassCsGnscommonPacketsCommandPacket_ByteMode_(JavaNioByteBuffer *bbuf, EduUmassCsGnscommonPacketsCommandPacket_ByteMode *mode);

__attribute__((unused)) static JavaNioByteBuffer *EduUmassCsGnscommonPacketsCommandPacket_toByteBufferWithOuterFields(EduUmassCsGnscommonPacketsCommandPacket *self);

__attribute__((unused)) static IOSByteArray *EduUmassCsGnscommonPacketsCommandPacket_appendByteifiedInnerJSONCommandWithJavaNioByteBuffer_withByteArray_(EduUmassCsGnscommonPacketsCommandPacket *self, JavaNioByteBuffer *bbuf, IOSByteArray *inner);

__attribute__((unused)) static IOSByteArray *EduUmassCsGnscommonPacketsCommandPacket_toBytesWingItAsStringWithJavaNioByteBuffer_withOrgJsonJSONObject_(EduUmassCsGnscommonPacketsCommandPacket *self, JavaNioByteBuffer *buf, OrgJsonJSONObject *json);

__attribute__((unused)) static void EduUmassCsGnscommonPacketsCommandPacket_putBackRemovedWithJavaLangInteger_(EduUmassCsGnscommonPacketsCommandPacket *self, JavaLangInteger *commandType);

__attribute__((unused)) static IOSByteArray *EduUmassCsGnscommonPacketsCommandPacket_handleSerializationExceptionWithJavaLangException_withJavaLangInteger_(EduUmassCsGnscommonPacketsCommandPacket *self, JavaLangException *e, JavaLangInteger *commandType);

__attribute__((unused)) static IOSByteArray *EduUmassCsGnscommonPacketsCommandPacket_toJSONBytes(EduUmassCsGnscommonPacketsCommandPacket *self);

__attribute__((unused)) static NSString *EduUmassCsGnscommonPacketsCommandPacket_getRespStr(EduUmassCsGnscommonPacketsCommandPacket *self);

__attribute__((unused)) static id EduUmassCsGnscommonPacketsCommandPacket_getResultValueFromStringWithNSString_(NSString *str);

typedef NS_ENUM(NSUInteger, EduUmassCsGnscommonPacketsCommandPacket_ByteMode_Enum) {
  EduUmassCsGnscommonPacketsCommandPacket_ByteMode_Enum_ORG_JSON = 0,
  EduUmassCsGnscommonPacketsCommandPacket_ByteMode_Enum_HOMEBREW = 1,
  EduUmassCsGnscommonPacketsCommandPacket_ByteMode_Enum_JACKSON = 2,
  EduUmassCsGnscommonPacketsCommandPacket_ByteMode_Enum_MSGPACK = 3,
  EduUmassCsGnscommonPacketsCommandPacket_ByteMode_Enum_STRING_WING = 4,
};

@interface EduUmassCsGnscommonPacketsCommandPacket_ByteMode : JavaLangEnum < NSCopying > {
 @public
  jint val_;
}

+ (IOSObjectArray *)values;

+ (EduUmassCsGnscommonPacketsCommandPacket_ByteMode *)valueOfWithNSString:(NSString *)name;

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(EduUmassCsGnscommonPacketsCommandPacket_ByteMode)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT EduUmassCsGnscommonPacketsCommandPacket_ByteMode *EduUmassCsGnscommonPacketsCommandPacket_ByteMode_values_[];

inline EduUmassCsGnscommonPacketsCommandPacket_ByteMode *EduUmassCsGnscommonPacketsCommandPacket_ByteMode_get_ORG_JSON();
J2OBJC_ENUM_CONSTANT(EduUmassCsGnscommonPacketsCommandPacket_ByteMode, ORG_JSON)

inline EduUmassCsGnscommonPacketsCommandPacket_ByteMode *EduUmassCsGnscommonPacketsCommandPacket_ByteMode_get_HOMEBREW();
J2OBJC_ENUM_CONSTANT(EduUmassCsGnscommonPacketsCommandPacket_ByteMode, HOMEBREW)

inline EduUmassCsGnscommonPacketsCommandPacket_ByteMode *EduUmassCsGnscommonPacketsCommandPacket_ByteMode_get_JACKSON();
J2OBJC_ENUM_CONSTANT(EduUmassCsGnscommonPacketsCommandPacket_ByteMode, JACKSON)

inline EduUmassCsGnscommonPacketsCommandPacket_ByteMode *EduUmassCsGnscommonPacketsCommandPacket_ByteMode_get_MSGPACK();
J2OBJC_ENUM_CONSTANT(EduUmassCsGnscommonPacketsCommandPacket_ByteMode, MSGPACK)

inline EduUmassCsGnscommonPacketsCommandPacket_ByteMode *EduUmassCsGnscommonPacketsCommandPacket_ByteMode_get_STRING_WING();
J2OBJC_ENUM_CONSTANT(EduUmassCsGnscommonPacketsCommandPacket_ByteMode, STRING_WING)

inline id<JavaUtilMap> EduUmassCsGnscommonPacketsCommandPacket_ByteMode_get_byteModeMap();
static id<JavaUtilMap> EduUmassCsGnscommonPacketsCommandPacket_ByteMode_byteModeMap;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduUmassCsGnscommonPacketsCommandPacket_ByteMode, byteModeMap, id<JavaUtilMap>)

__attribute__((unused)) static void EduUmassCsGnscommonPacketsCommandPacket_ByteMode_initWithInt_withNSString_withInt_(EduUmassCsGnscommonPacketsCommandPacket_ByteMode *self, jint val, NSString *__name, jint __ordinal);

__attribute__((unused)) static IOSObjectArray *EduUmassCsGnscommonPacketsCommandPacket_ByteMode_values();

__attribute__((unused)) static EduUmassCsGnscommonPacketsCommandPacket_ByteMode *EduUmassCsGnscommonPacketsCommandPacket_ByteMode_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT EduUmassCsGnscommonPacketsCommandPacket_ByteMode *EduUmassCsGnscommonPacketsCommandPacket_ByteMode_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsGnscommonPacketsCommandPacket_ByteMode)

@interface EduUmassCsGnscommonPacketsCommandPacket_1 : NSObject {
 @public
  EduUmassCsGnscommonPacketsCommandPacket *this$0_;
}

- (instancetype)initWithEduUmassCsGnscommonPacketsCommandPacket:(EduUmassCsGnscommonPacketsCommandPacket *)outer$;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsGnscommonPacketsCommandPacket_1)

__attribute__((unused)) static void EduUmassCsGnscommonPacketsCommandPacket_1_initWithEduUmassCsGnscommonPacketsCommandPacket_(EduUmassCsGnscommonPacketsCommandPacket_1 *self, EduUmassCsGnscommonPacketsCommandPacket *outer$);

__attribute__((unused)) static EduUmassCsGnscommonPacketsCommandPacket_1 *new_EduUmassCsGnscommonPacketsCommandPacket_1_initWithEduUmassCsGnscommonPacketsCommandPacket_(EduUmassCsGnscommonPacketsCommandPacket *outer$) NS_RETURNS_RETAINED;

__attribute__((unused)) static EduUmassCsGnscommonPacketsCommandPacket_1 *create_EduUmassCsGnscommonPacketsCommandPacket_1_initWithEduUmassCsGnscommonPacketsCommandPacket_(EduUmassCsGnscommonPacketsCommandPacket *outer$);

J2OBJC_INITIALIZED_DEFN(EduUmassCsGnscommonPacketsCommandPacket)

NSString *EduUmassCsGnscommonPacketsCommandPacket_BOGUS_SERVICE_NAME;

@implementation EduUmassCsGnscommonPacketsCommandPacket

- (instancetype)initWithLong:(jlong)requestId
       withOrgJsonJSONObject:(OrgJsonJSONObject *)command {
  EduUmassCsGnscommonPacketsCommandPacket_initWithLong_withOrgJsonJSONObject_(self, requestId, command);
  return self;
}

- (instancetype)initWithLong:(jlong)requestId
       withOrgJsonJSONObject:(OrgJsonJSONObject *)command
                 withBoolean:(jboolean)validate {
  EduUmassCsGnscommonPacketsCommandPacket_initWithLong_withOrgJsonJSONObject_withBoolean_(self, requestId, command, validate);
  return self;
}

- (instancetype)initWithOrgJsonJSONObject:(OrgJsonJSONObject *)json {
  EduUmassCsGnscommonPacketsCommandPacket_initWithOrgJsonJSONObject_(self, json);
  return self;
}

- (instancetype)initWithByteArray:(IOSByteArray *)bytes {
  EduUmassCsGnscommonPacketsCommandPacket_initWithByteArray_(self, bytes);
  return self;
}

- (void)validateCommandType {
  JreAssert(((![((EduUmassCsGnscommonCommandType *) nil_chk([self getCommandType])) isMutualAuth])), (@"edu/umass/cs/gnscommon/packets/CommandPacket.java:131 condition failed: assert (!this.getCommandType().isMutualAuth());"));
}

+ (OrgJsonJSONObject *)fromBytesStringerHackWithJavaNioByteBuffer:(JavaNioByteBuffer *)buf {
  return EduUmassCsGnscommonPacketsCommandPacket_fromBytesStringerHackWithJavaNioByteBuffer_(buf);
}

+ (OrgJsonJSONObject *)getJSONObjectWithJavaNioByteBuffer:(JavaNioByteBuffer *)bbuf
     withEduUmassCsGnscommonPacketsCommandPacket_ByteMode:(EduUmassCsGnscommonPacketsCommandPacket_ByteMode *)mode {
  return EduUmassCsGnscommonPacketsCommandPacket_getJSONObjectWithJavaNioByteBuffer_withEduUmassCsGnscommonPacketsCommandPacket_ByteMode_(bbuf, mode);
}

- (IOSByteArray *)toBytes {
  @try {
    switch ([EduUmassCsGnscommonPacketsCommandPacket_byteMode ordinal]) {
      case EduUmassCsGnscommonPacketsCommandPacket_ByteMode_Enum_ORG_JSON:
      return [((NSString *) nil_chk([((OrgJsonJSONObject *) nil_chk([self toJSONObject])) description])) java_getBytesWithCharsetName:EduUmassCsNioMessageNIOTransport_NIO_CHARSET_ENCODING];
      case EduUmassCsGnscommonPacketsCommandPacket_ByteMode_Enum_HOMEBREW:
      return EduUmassCsGnscommonPacketsCommandPacket_appendByteifiedInnerJSONCommandWithJavaNioByteBuffer_withByteArray_(self, EduUmassCsGnscommonPacketsCommandPacket_toByteBufferWithOuterFields(self), EduUmassCsGnscommonUtilsJSONByteConverter_toBytesHardcodedWithOrgJsonJSONObject_(self->command_));
      case EduUmassCsGnscommonPacketsCommandPacket_ByteMode_Enum_STRING_WING:
      return EduUmassCsGnscommonPacketsCommandPacket_toBytesWingItAsStringWithJavaNioByteBuffer_withOrgJsonJSONObject_(self, EduUmassCsGnscommonPacketsCommandPacket_toByteBufferWithOuterFields(self), self->command_);
      default:
      @throw create_JavaLangRuntimeException_initWithNSString_(@"Unrecognized byteification mode");
    }
  }
  @catch (OrgJsonJSONException *e) {
    [((JavaLangException *) nil_chk(e)) printStackTrace];
    @throw create_JavaLangRuntimeException_initWithNSString_(JreStrcat("$@", @"Unable to byteify ", self));
  }
  @catch (JavaIoIOException *e) {
    [((JavaLangException *) nil_chk(e)) printStackTrace];
    @throw create_JavaLangRuntimeException_initWithNSString_(JreStrcat("$@", @"Unable to byteify ", self));
  }
}

- (JavaNioByteBuffer *)toByteBufferWithOuterFields {
  return EduUmassCsGnscommonPacketsCommandPacket_toByteBufferWithOuterFields(self);
}

- (IOSByteArray *)appendByteifiedInnerJSONCommandWithJavaNioByteBuffer:(JavaNioByteBuffer *)bbuf
                                                         withByteArray:(IOSByteArray *)inner {
  return EduUmassCsGnscommonPacketsCommandPacket_appendByteifiedInnerJSONCommandWithJavaNioByteBuffer_withByteArray_(self, bbuf, inner);
}

- (IOSByteArray *)toBytesWingItAsStringWithJavaNioByteBuffer:(JavaNioByteBuffer *)buf
                                       withOrgJsonJSONObject:(OrgJsonJSONObject *)json {
  return EduUmassCsGnscommonPacketsCommandPacket_toBytesWingItAsStringWithJavaNioByteBuffer_withOrgJsonJSONObject_(self, buf, json);
}

- (void)putBackRemovedWithJavaLangInteger:(JavaLangInteger *)commandType {
  EduUmassCsGnscommonPacketsCommandPacket_putBackRemovedWithJavaLangInteger_(self, commandType);
}

- (IOSByteArray *)handleSerializationExceptionWithJavaLangException:(JavaLangException *)e
                                                withJavaLangInteger:(JavaLangInteger *)commandType {
  return EduUmassCsGnscommonPacketsCommandPacket_handleSerializationExceptionWithJavaLangException_withJavaLangInteger_(self, e, commandType);
}

- (IOSByteArray *)toJSONBytes {
  return EduUmassCsGnscommonPacketsCommandPacket_toJSONBytes(self);
}

- (OrgJsonJSONObject *)toJSONObject {
  OrgJsonJSONObject *json = create_OrgJsonJSONObject_init();
  EduUmassCsGnsserverGnsappPacketPacket_putPacketTypeWithOrgJsonJSONObject_withEduUmassCsGnsserverGnsappPacketPacket_PacketType_(json, [self getType]);
  [json putWithNSString:EduUmassCsGnscommonPacketsCommandPacket_QID withLong:self->clientRequestId_];
  [json putWithNSString:EduUmassCsGnscommonPacketsCommandPacket_COMMAND withId:self->command_];
  if (self->forceCoordination_) {
    [json putWithNSString:[((EduUmassCsGnscommonGNSProtocol *) nil_chk(JreLoadEnum(EduUmassCsGnscommonGNSProtocol, FORCE_COORDINATE_READS))) description] withBoolean:self->forceCoordination_];
  }
  return json;
}

- (jlong)getRequestID {
  return clientRequestId_;
}

- (id<EduUmassCsGigapaxosInterfacesClientRequest>)getResponse {
  return self->response_;
}

- (OrgJsonJSONObject *)getCommand {
  return command_;
}

- (NSString *)getServiceName {
  @try {
    if (command_ != nil) {
      if ([command_ hasWithNSString:[((EduUmassCsGnscommonGNSProtocol *) nil_chk(JreLoadEnum(EduUmassCsGnscommonGNSProtocol, GUID))) description]]) {
        return [command_ getStringWithNSString:[JreLoadEnum(EduUmassCsGnscommonGNSProtocol, GUID) description]];
      }
      if ([command_ hasWithNSString:[((EduUmassCsGnscommonGNSProtocol *) nil_chk(JreLoadEnum(EduUmassCsGnscommonGNSProtocol, NAME))) description]]) {
        return [command_ getStringWithNSString:[JreLoadEnum(EduUmassCsGnscommonGNSProtocol, NAME) description]];
      }
    }
  }
  @catch (OrgJsonJSONException *e) {
  }
  return EduUmassCsGnscommonPacketsCommandPacket_BOGUS_SERVICE_NAME;
}

- (jint)getCommandInteger {
  @try {
    if (command_ != nil) {
      if ([command_ hasWithNSString:[((EduUmassCsGnscommonGNSProtocol *) nil_chk(JreLoadEnum(EduUmassCsGnscommonGNSProtocol, COMMAND_INT))) description]]) {
        return [command_ getIntWithNSString:[JreLoadEnum(EduUmassCsGnscommonGNSProtocol, COMMAND_INT) description]];
      }
    }
  }
  @catch (OrgJsonJSONException *e) {
  }
  return -1;
}

- (jboolean)needsCoordination {
  return self->forceCoordination_ || [((EduUmassCsGnscommonCommandType *) nil_chk([self getCommandType])) isUpdate];
}

- (EduUmassCsGnscommonCommandType *)getCommandType {
  return EduUmassCsGnscommonPacketsCommandPacket_getJSONCommandTypeWithOrgJsonJSONObject_(command_);
}

+ (EduUmassCsGnscommonCommandType *)getJSONCommandTypeWithOrgJsonJSONObject:(OrgJsonJSONObject *)command {
  return EduUmassCsGnscommonPacketsCommandPacket_getJSONCommandTypeWithOrgJsonJSONObject_(command);
}

- (id<EduUmassCsGigapaxosInterfacesClientRequest>)setForceCoordinatedReadsWithBoolean:(jboolean)force {
  if (force && ([((EduUmassCsGnscommonCommandType *) nil_chk([self getCommandType])) isRead])) {
    self->forceCoordination_ = true;
  }
  return self;
}

- (void)finish {
  @synchronized(self) {
    while (!self->executed_) {
      @try {
        [self java_wait];
      }
      @catch (JavaLangInterruptedException *e) {
        [((JavaLangInterruptedException *) nil_chk(e)) printStackTrace];
      }
    }
  }
}

- (NSString *)getRespStr {
  return EduUmassCsGnscommonPacketsCommandPacket_getRespStr(self);
}

- (EduUmassCsGnscommonPacketsCommandPacket *)setResultWithEduUmassCsGnscommonPacketsResponsePacket:(EduUmassCsGnscommonPacketsResponsePacket *)responsePacket {
  @synchronized(self) {
    if (self->result_ == nil) {
      self->executed_ = true;
      JreStrongAssign(&self->result_, responsePacket);
      [self java_notifyAll];
    }
    else {
      @throw create_JavaLangRuntimeException_initWithNSString_(@"Can not set response more than once");
    }
  }
  return self;
}

- (id)getResult {
  NSString *responseStr = EduUmassCsGnscommonPacketsCommandPacket_getRespStr(self);
  @try {
    id retval = responseStr != nil && EduUmassCsNioJSONPacket_couldBeJSONObjectWithNSString_(responseStr) ? create_OrgJsonJSONObject_initWithNSString_(responseStr) : responseStr != nil && EduUmassCsNioJSONPacket_couldBeJSONArrayWithNSString_(responseStr) ? create_OrgJsonJSONArray_initWithNSString_(responseStr) : EduUmassCsGnscommonPacketsCommandPacket_getResultValueFromStringWithNSString_(responseStr);
    return retval;
  }
  @catch (OrgJsonJSONException *e) {
    @throw create_EduUmassCsGnscommonExceptionsClientClientException_initWithEduUmassCsGnscommonResponseCode_withNSString_(JreLoadEnum(EduUmassCsGnscommonResponseCode, JSON_PARSE_ERROR), [((OrgJsonJSONException *) nil_chk(e)) getMessage]);
  }
}

- (NSString *)getResultString {
  return EduUmassCsGnscommonPacketsCommandPacket_getRespStr(self);
}

- (OrgJsonJSONObject *)getResultJSONObject {
  NSString *responseStr = EduUmassCsGnscommonPacketsCommandPacket_getRespStr(self);
  @try {
    OrgJsonJSONObject *json = responseStr != nil ? create_OrgJsonJSONObject_initWithNSString_(responseStr) : create_OrgJsonJSONObject_init();
    return json;
  }
  @catch (OrgJsonJSONException *e) {
    @throw create_EduUmassCsGnscommonExceptionsClientClientException_initWithEduUmassCsGnscommonResponseCode_withNSString_(JreLoadEnum(EduUmassCsGnscommonResponseCode, JSON_PARSE_ERROR), JreStrcat("$$$", [((OrgJsonJSONException *) nil_chk(e)) getMessage], @" while parsing response string ", responseStr));
  }
}

- (id<JavaUtilMap>)getResultMap {
  NSString *responseStr = EduUmassCsGnscommonPacketsCommandPacket_getRespStr(self);
  @try {
    id<JavaUtilMap> map = EduUmassCsUtilsUtil_JSONObjectToMapWithOrgJsonJSONObject_(responseStr != nil ? create_OrgJsonJSONObject_initWithNSString_(responseStr) : create_OrgJsonJSONObject_init());
    return map;
  }
  @catch (OrgJsonJSONException *e) {
    @throw create_EduUmassCsGnscommonExceptionsClientClientException_initWithEduUmassCsGnscommonResponseCode_withNSString_(JreLoadEnum(EduUmassCsGnscommonResponseCode, JSON_PARSE_ERROR), [((OrgJsonJSONException *) nil_chk(e)) getMessage]);
  }
}

- (id<JavaUtilList>)getResultList {
  NSString *responseStr = EduUmassCsGnscommonPacketsCommandPacket_getRespStr(self);
  @try {
    id<JavaUtilList> list = EduUmassCsUtilsUtil_JSONArrayToListWithOrgJsonJSONArray_(responseStr != nil ? create_OrgJsonJSONArray_initWithNSString_(responseStr) : create_OrgJsonJSONArray_init());
    return list;
  }
  @catch (OrgJsonJSONException *e) {
    @throw create_EduUmassCsGnscommonExceptionsClientClientException_initWithEduUmassCsGnscommonResponseCode_withNSString_(JreLoadEnum(EduUmassCsGnscommonResponseCode, JSON_PARSE_ERROR), [((OrgJsonJSONException *) nil_chk(e)) getMessage]);
  }
}

- (OrgJsonJSONArray *)getResultJSONArray {
  NSString *responseStr = EduUmassCsGnscommonPacketsCommandPacket_getRespStr(self);
  @try {
    return responseStr != nil ? create_OrgJsonJSONArray_initWithNSString_(responseStr) : create_OrgJsonJSONArray_init();
  }
  @catch (OrgJsonJSONException *e) {
    @throw create_EduUmassCsGnscommonExceptionsClientClientException_initWithEduUmassCsGnscommonResponseCode_withNSString_(JreLoadEnum(EduUmassCsGnscommonResponseCode, JSON_PARSE_ERROR), [((OrgJsonJSONException *) nil_chk(e)) getMessage]);
  }
}

- (jboolean)getResultBoolean {
  id obj = [self getResult];
  if (obj != nil && [obj isKindOfClass:[JavaLangBoolean class]]) {
    return [(JavaLangBoolean *) cast_chk(obj, [JavaLangBoolean class]) booleanValue];
  }
  @throw create_EduUmassCsGnscommonExceptionsClientClientException_initWithEduUmassCsGnscommonResponseCode_withNSString_(JreLoadEnum(EduUmassCsGnscommonResponseCode, JSON_PARSE_ERROR), @"Unable to parse response as boolean");
}

- (jint)getResultInt {
  id obj = [self getResult];
  if (obj != nil && [obj isKindOfClass:[JavaLangInteger class]]) {
    return [(JavaLangInteger *) cast_chk(obj, [JavaLangInteger class]) intValue];
  }
  @throw create_EduUmassCsGnscommonExceptionsClientClientException_initWithEduUmassCsGnscommonResponseCode_withNSString_(JreLoadEnum(EduUmassCsGnscommonResponseCode, JSON_PARSE_ERROR), @"Unable to parse response as boolean");
}

- (jlong)getResultLong {
  id obj = [self getResult];
  if (obj != nil && [obj isKindOfClass:[JavaLangLong class]]) {
    return [(JavaLangLong *) cast_chk(obj, [JavaLangLong class]) longLongValue];
  }
  @throw create_EduUmassCsGnscommonExceptionsClientClientException_initWithEduUmassCsGnscommonResponseCode_withNSString_(JreLoadEnum(EduUmassCsGnscommonResponseCode, JSON_PARSE_ERROR), @"Unable to parse response as boolean");
}

- (jdouble)getResultDouble {
  id obj = [self getResult];
  if (obj != nil && [obj isKindOfClass:[JavaLangDouble class]]) {
    return [(JavaLangDouble *) cast_chk(obj, [JavaLangDouble class]) doubleValue];
  }
  @throw create_EduUmassCsGnscommonExceptionsClientClientException_initWithEduUmassCsGnscommonResponseCode_withNSString_(JreLoadEnum(EduUmassCsGnscommonResponseCode, JSON_PARSE_ERROR), @"Unable to parse response as boolean");
}

+ (id)getResultValueFromStringWithNSString:(NSString *)str {
  return EduUmassCsGnscommonPacketsCommandPacket_getResultValueFromStringWithNSString_(str);
}

- (jboolean)hasResult {
  return self->result_ != nil;
}

- (id)getSummary {
  return create_EduUmassCsGnscommonPacketsCommandPacket_1_initWithEduUmassCsGnscommonPacketsCommandPacket_(self);
}

- (id)getSummaryWithBoolean:(jboolean)arg0 {
  return EduUmassCsUtilsSummarizable_getSummaryWithBoolean_(self, arg0);
}

- (void)setNeedsCoordinationWithBoolean:(jboolean)arg0 {
  EduUmassCsReconfigurationInterfacesReplicableRequest_setNeedsCoordinationWithBoolean_(self, arg0);
}

- (void)dealloc {
  RELEASE_(command_);
  RELEASE_(result_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, 3, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 4, 5, -1, -1, -1 },
    { NULL, "V", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgJsonJSONObject;", 0xa, 6, 7, 8, -1, -1, -1 },
    { NULL, "LOrgJsonJSONObject;", 0xa, 9, 10, 5, -1, -1, -1 },
    { NULL, "[B", 0x11, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaNioByteBuffer;", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "[B", 0x2, 11, 12, -1, -1, -1, -1 },
    { NULL, "[B", 0x2, 13, 14, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 15, 16, 3, -1, -1, -1 },
    { NULL, "[B", 0x2, 17, 18, -1, -1, -1, -1 },
    { NULL, "[B", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgJsonJSONObject;", 0x1, -1, -1, 3, -1, -1, -1 },
    { NULL, "J", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsGigapaxosInterfacesClientRequest;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgJsonJSONObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsGnscommonCommandType;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsGnscommonCommandType;", 0x9, 19, 2, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsGigapaxosInterfacesClientRequest;", 0x1, 20, 21, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x2, -1, -1, 22, -1, -1, -1 },
    { NULL, "LEduUmassCsGnscommonPacketsCommandPacket;", 0x0, 23, 24, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, 22, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, 22, -1, -1, -1 },
    { NULL, "LOrgJsonJSONObject;", 0x1, -1, -1, 22, -1, -1, -1 },
    { NULL, "LJavaUtilMap;", 0x1, -1, -1, 22, 25, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, -1, -1, 22, 26, -1, -1 },
    { NULL, "LOrgJsonJSONArray;", 0x1, -1, -1, 22, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, 22, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, 22, -1, -1, -1 },
    { NULL, "J", 0x1, -1, -1, 22, -1, -1, -1 },
    { NULL, "D", 0x1, -1, -1, 22, -1, -1, -1 },
    { NULL, "LNSObject;", 0xa, 27, 28, 22, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithLong:withOrgJsonJSONObject:);
  methods[1].selector = @selector(initWithLong:withOrgJsonJSONObject:withBoolean:);
  methods[2].selector = @selector(initWithOrgJsonJSONObject:);
  methods[3].selector = @selector(initWithByteArray:);
  methods[4].selector = @selector(validateCommandType);
  methods[5].selector = @selector(fromBytesStringerHackWithJavaNioByteBuffer:);
  methods[6].selector = @selector(getJSONObjectWithJavaNioByteBuffer:withEduUmassCsGnscommonPacketsCommandPacket_ByteMode:);
  methods[7].selector = @selector(toBytes);
  methods[8].selector = @selector(toByteBufferWithOuterFields);
  methods[9].selector = @selector(appendByteifiedInnerJSONCommandWithJavaNioByteBuffer:withByteArray:);
  methods[10].selector = @selector(toBytesWingItAsStringWithJavaNioByteBuffer:withOrgJsonJSONObject:);
  methods[11].selector = @selector(putBackRemovedWithJavaLangInteger:);
  methods[12].selector = @selector(handleSerializationExceptionWithJavaLangException:withJavaLangInteger:);
  methods[13].selector = @selector(toJSONBytes);
  methods[14].selector = @selector(toJSONObject);
  methods[15].selector = @selector(getRequestID);
  methods[16].selector = @selector(getResponse);
  methods[17].selector = @selector(getCommand);
  methods[18].selector = @selector(getServiceName);
  methods[19].selector = @selector(getCommandInteger);
  methods[20].selector = @selector(needsCoordination);
  methods[21].selector = @selector(getCommandType);
  methods[22].selector = @selector(getJSONCommandTypeWithOrgJsonJSONObject:);
  methods[23].selector = @selector(setForceCoordinatedReadsWithBoolean:);
  methods[24].selector = @selector(finish);
  methods[25].selector = @selector(getRespStr);
  methods[26].selector = @selector(setResultWithEduUmassCsGnscommonPacketsResponsePacket:);
  methods[27].selector = @selector(getResult);
  methods[28].selector = @selector(getResultString);
  methods[29].selector = @selector(getResultJSONObject);
  methods[30].selector = @selector(getResultMap);
  methods[31].selector = @selector(getResultList);
  methods[32].selector = @selector(getResultJSONArray);
  methods[33].selector = @selector(getResultBoolean);
  methods[34].selector = @selector(getResultInt);
  methods[35].selector = @selector(getResultLong);
  methods[36].selector = @selector(getResultDouble);
  methods[37].selector = @selector(getResultValueFromStringWithNSString:);
  methods[38].selector = @selector(hasResult);
  methods[39].selector = @selector(getSummary);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "QID", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 29, -1, -1 },
    { "COMMAND", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 30, -1, -1 },
    { "SUPPORT_OLD_PROTOCOL", "Z", .constantValue.asBOOL = EduUmassCsGnscommonPacketsCommandPacket_SUPPORT_OLD_PROTOCOL, 0x1a, -1, -1, -1, -1 },
    { "OLD_COMMAND_PACKET_REQUESTID", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 31, -1, -1 },
    { "OLD_COMMAND_PACKET_COMMAND", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 32, -1, -1 },
    { "BOGUS_SERVICE_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 33, -1, -1 },
    { "clientRequestId_", "J", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "command_", "LOrgJsonJSONObject;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "forceCoordination_", "Z", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "result_", "LNSObject;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "byteMode", "LEduUmassCsGnscommonPacketsCommandPacket_ByteMode;", .constantValue.asLong = 0, 0x1a, -1, 34, -1, -1 },
    { "executed_", "Z", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "JLOrgJsonJSONObject;", "JLOrgJsonJSONObject;Z", "LOrgJsonJSONObject;", "LOrgJsonJSONException;", "[B", "LEduUmassCsReconfigurationReconfigurationutilsRequestParseException;", "fromBytesStringerHack", "LJavaNioByteBuffer;", "LJavaIoUnsupportedEncodingException;LOrgJsonJSONException;", "getJSONObject", "LJavaNioByteBuffer;LEduUmassCsGnscommonPacketsCommandPacket_ByteMode;", "appendByteifiedInnerJSONCommand", "LJavaNioByteBuffer;[B", "toBytesWingItAsString", "LJavaNioByteBuffer;LOrgJsonJSONObject;", "putBackRemoved", "LJavaLangInteger;", "handleSerializationException", "LJavaLangException;LJavaLangInteger;", "getJSONCommandType", "setForceCoordinatedReads", "Z", "LEduUmassCsGnscommonExceptionsClientClientException;", "setResult", "LEduUmassCsGnscommonPacketsResponsePacket;", "()Ljava/util/Map<Ljava/lang/String;*>;", "()Ljava/util/List<*>;", "getResultValueFromString", "LNSString;", &EduUmassCsGnscommonPacketsCommandPacket_QID, &EduUmassCsGnscommonPacketsCommandPacket_COMMAND, &EduUmassCsGnscommonPacketsCommandPacket_OLD_COMMAND_PACKET_REQUESTID, &EduUmassCsGnscommonPacketsCommandPacket_OLD_COMMAND_PACKET_COMMAND, &EduUmassCsGnscommonPacketsCommandPacket_BOGUS_SERVICE_NAME, &EduUmassCsGnscommonPacketsCommandPacket_byteMode, "LEduUmassCsGnscommonPacketsCommandPacket_ByteMode;" };
  static const J2ObjcClassInfo _EduUmassCsGnscommonPacketsCommandPacket = { "CommandPacket", "edu.umass.cs.gnscommon.packets", ptrTable, methods, fields, 7, 0x1, 40, 12, -1, 35, -1, -1, -1 };
  return &_EduUmassCsGnscommonPacketsCommandPacket;
}

+ (void)initialize {
  if (self == [EduUmassCsGnscommonPacketsCommandPacket class]) {
    JreStrongAssign(&EduUmassCsGnscommonPacketsCommandPacket_QID, [((EduUmassCsGnscommonGNSProtocol *) nil_chk(JreLoadEnum(EduUmassCsGnscommonGNSProtocol, REQUEST_ID))) description]);
    JreStrongAssign(&EduUmassCsGnscommonPacketsCommandPacket_COMMAND, [((EduUmassCsGnscommonGNSProtocol *) nil_chk(JreLoadEnum(EduUmassCsGnscommonGNSProtocol, COMMAND_QUERY))) description]);
    JreStrongAssign(&EduUmassCsGnscommonPacketsCommandPacket_BOGUS_SERVICE_NAME, [((EduUmassCsGnscommonGNSProtocol *) nil_chk(JreLoadEnum(EduUmassCsGnscommonGNSProtocol, UNKNOWN_NAME))) description]);
    JreStrongAssign(&EduUmassCsGnscommonPacketsCommandPacket_byteMode, [((id<JavaUtilMap>) nil_chk(JreLoadStatic(EduUmassCsGnscommonPacketsCommandPacket_ByteMode, byteModeMap))) getWithId:JavaLangInteger_valueOfWithInt_(EduUmassCsUtilsConfig_getGlobalIntWithJavaLangEnum_(JreLoadEnum(EduUmassCsGnsclientClientGNSClientConfig_GNSCC, BYTE_MODE)))]);
    J2OBJC_SET_INITIALIZED(EduUmassCsGnscommonPacketsCommandPacket)
  }
}

@end

void EduUmassCsGnscommonPacketsCommandPacket_initWithLong_withOrgJsonJSONObject_(EduUmassCsGnscommonPacketsCommandPacket *self, jlong requestId, OrgJsonJSONObject *command) {
  EduUmassCsGnscommonPacketsCommandPacket_initWithLong_withOrgJsonJSONObject_withBoolean_(self, requestId, command, true);
}

EduUmassCsGnscommonPacketsCommandPacket *new_EduUmassCsGnscommonPacketsCommandPacket_initWithLong_withOrgJsonJSONObject_(jlong requestId, OrgJsonJSONObject *command) {
  J2OBJC_NEW_IMPL(EduUmassCsGnscommonPacketsCommandPacket, initWithLong_withOrgJsonJSONObject_, requestId, command)
}

EduUmassCsGnscommonPacketsCommandPacket *create_EduUmassCsGnscommonPacketsCommandPacket_initWithLong_withOrgJsonJSONObject_(jlong requestId, OrgJsonJSONObject *command) {
  J2OBJC_CREATE_IMPL(EduUmassCsGnscommonPacketsCommandPacket, initWithLong_withOrgJsonJSONObject_, requestId, command)
}

void EduUmassCsGnscommonPacketsCommandPacket_initWithLong_withOrgJsonJSONObject_withBoolean_(EduUmassCsGnscommonPacketsCommandPacket *self, jlong requestId, OrgJsonJSONObject *command, jboolean validate) {
  EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress_init(self);
  self->forceCoordination_ = false;
  JreStrongAssign(&self->result_, nil);
  self->executed_ = false;
  [self setTypeWithEduUmassCsGnsserverGnsappPacketPacket_PacketType:JreLoadEnum(EduUmassCsGnsserverGnsappPacketPacket_PacketType, COMMAND)];
  self->clientRequestId_ = requestId;
  JreStrongAssign(&self->command_, command);
  if (validate) {
    [self validateCommandType];
  }
}

EduUmassCsGnscommonPacketsCommandPacket *new_EduUmassCsGnscommonPacketsCommandPacket_initWithLong_withOrgJsonJSONObject_withBoolean_(jlong requestId, OrgJsonJSONObject *command, jboolean validate) {
  J2OBJC_NEW_IMPL(EduUmassCsGnscommonPacketsCommandPacket, initWithLong_withOrgJsonJSONObject_withBoolean_, requestId, command, validate)
}

EduUmassCsGnscommonPacketsCommandPacket *create_EduUmassCsGnscommonPacketsCommandPacket_initWithLong_withOrgJsonJSONObject_withBoolean_(jlong requestId, OrgJsonJSONObject *command, jboolean validate) {
  J2OBJC_CREATE_IMPL(EduUmassCsGnscommonPacketsCommandPacket, initWithLong_withOrgJsonJSONObject_withBoolean_, requestId, command, validate)
}

void EduUmassCsGnscommonPacketsCommandPacket_initWithOrgJsonJSONObject_(EduUmassCsGnscommonPacketsCommandPacket *self, OrgJsonJSONObject *json) {
  EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress_init(self);
  self->forceCoordination_ = false;
  JreStrongAssign(&self->result_, nil);
  self->executed_ = false;
  JreStrongAssign(&self->type_, EduUmassCsGnsserverGnsappPacketPacket_getPacketTypeWithOrgJsonJSONObject_(json));
  {
    if ([((OrgJsonJSONObject *) nil_chk(json)) hasWithNSString:EduUmassCsGnscommonPacketsCommandPacket_QID]) {
      self->clientRequestId_ = [json getLongWithNSString:EduUmassCsGnscommonPacketsCommandPacket_QID];
    }
    else if ([json hasWithNSString:EduUmassCsGnscommonPacketsCommandPacket_OLD_COMMAND_PACKET_REQUESTID]) {
      self->clientRequestId_ = [json getLongWithNSString:EduUmassCsGnscommonPacketsCommandPacket_OLD_COMMAND_PACKET_REQUESTID];
    }
    else {
      @throw create_OrgJsonJSONException_initWithNSString_(JreStrcat("$$", @"Packet missing field ", EduUmassCsGnscommonPacketsCommandPacket_QID));
    }
    if ([json hasWithNSString:EduUmassCsGnscommonPacketsCommandPacket_COMMAND]) {
      JreStrongAssign(&self->command_, [json getJSONObjectWithNSString:EduUmassCsGnscommonPacketsCommandPacket_COMMAND]);
    }
    else if ([json hasWithNSString:EduUmassCsGnscommonPacketsCommandPacket_OLD_COMMAND_PACKET_COMMAND]) {
      JreStrongAssign(&self->command_, [json getJSONObjectWithNSString:EduUmassCsGnscommonPacketsCommandPacket_OLD_COMMAND_PACKET_COMMAND]);
    }
    else {
      @throw create_OrgJsonJSONException_initWithNSString_(JreStrcat("$$", @"Packet missing field ", EduUmassCsGnscommonPacketsCommandPacket_COMMAND));
    }
  }
  self->forceCoordination_ = [json hasWithNSString:[((EduUmassCsGnscommonGNSProtocol *) nil_chk(JreLoadEnum(EduUmassCsGnscommonGNSProtocol, FORCE_COORDINATE_READS))) description]] ? [json getBooleanWithNSString:[JreLoadEnum(EduUmassCsGnscommonGNSProtocol, FORCE_COORDINATE_READS) description]] : false;
  [self validateCommandType];
}

EduUmassCsGnscommonPacketsCommandPacket *new_EduUmassCsGnscommonPacketsCommandPacket_initWithOrgJsonJSONObject_(OrgJsonJSONObject *json) {
  J2OBJC_NEW_IMPL(EduUmassCsGnscommonPacketsCommandPacket, initWithOrgJsonJSONObject_, json)
}

EduUmassCsGnscommonPacketsCommandPacket *create_EduUmassCsGnscommonPacketsCommandPacket_initWithOrgJsonJSONObject_(OrgJsonJSONObject *json) {
  J2OBJC_CREATE_IMPL(EduUmassCsGnscommonPacketsCommandPacket, initWithOrgJsonJSONObject_, json)
}

void EduUmassCsGnscommonPacketsCommandPacket_initWithByteArray_(EduUmassCsGnscommonPacketsCommandPacket *self, IOSByteArray *bytes) {
  EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress_init(self);
  self->forceCoordination_ = false;
  JreStrongAssign(&self->result_, nil);
  self->executed_ = false;
  JavaNioByteBuffer *buf = JavaNioByteBuffer_wrapWithByteArray_(bytes);
  [self setTypeWithEduUmassCsGnsserverGnsappPacketPacket_PacketType:EduUmassCsGnsserverGnsappPacketPacket_getPacketTypeWithInt_([((JavaNioByteBuffer *) nil_chk(buf)) getInt])];
  self->clientRequestId_ = [buf getLong];
  self->forceCoordination_ = ([buf get] == 1);
  EduUmassCsGnscommonPacketsCommandPacket_ByteMode *mode = [((id<JavaUtilMap>) nil_chk(JreLoadStatic(EduUmassCsGnscommonPacketsCommandPacket_ByteMode, byteModeMap))) getWithId:JavaLangInteger_valueOfWithInt_((jint) [buf get])];
  JreStrongAssign(&self->command_, EduUmassCsGnscommonPacketsCommandPacket_getJSONObjectWithJavaNioByteBuffer_withEduUmassCsGnscommonPacketsCommandPacket_ByteMode_(buf, mode));
  [self validateCommandType];
}

EduUmassCsGnscommonPacketsCommandPacket *new_EduUmassCsGnscommonPacketsCommandPacket_initWithByteArray_(IOSByteArray *bytes) {
  J2OBJC_NEW_IMPL(EduUmassCsGnscommonPacketsCommandPacket, initWithByteArray_, bytes)
}

EduUmassCsGnscommonPacketsCommandPacket *create_EduUmassCsGnscommonPacketsCommandPacket_initWithByteArray_(IOSByteArray *bytes) {
  J2OBJC_CREATE_IMPL(EduUmassCsGnscommonPacketsCommandPacket, initWithByteArray_, bytes)
}

OrgJsonJSONObject *EduUmassCsGnscommonPacketsCommandPacket_fromBytesStringerHackWithJavaNioByteBuffer_(JavaNioByteBuffer *buf) {
  EduUmassCsGnscommonPacketsCommandPacket_initialize();
  OrgJsonJSONObject *json = create_OrgJsonJSONObject_init();
  [json putWithNSString:[((EduUmassCsGnscommonGNSProtocol *) nil_chk(JreLoadEnum(EduUmassCsGnscommonGNSProtocol, COMMAND_INT))) description] withInt:[((JavaNioByteBuffer *) nil_chk(buf)) getInt]];
  while ([buf hasRemaining]) {
    jint keyLength = [buf getInt];
    IOSByteArray *keyBytes = [IOSByteArray arrayWithLength:keyLength];
    [buf getWithByteArray:keyBytes];
    NSString *key = [NSString java_stringWithBytes:keyBytes charsetName:EduUmassCsNioMessageNIOTransport_NIO_CHARSET_ENCODING];
    jint valueLength = [buf getInt];
    IOSByteArray *valueBytes = [IOSByteArray arrayWithLength:valueLength];
    [buf getWithByteArray:valueBytes];
    NSString *value = [NSString java_stringWithBytes:valueBytes charsetName:EduUmassCsNioMessageNIOTransport_NIO_CHARSET_ENCODING];
    [json putWithNSString:key withId:value];
  }
  return json;
}

OrgJsonJSONObject *EduUmassCsGnscommonPacketsCommandPacket_getJSONObjectWithJavaNioByteBuffer_withEduUmassCsGnscommonPacketsCommandPacket_ByteMode_(JavaNioByteBuffer *bbuf, EduUmassCsGnscommonPacketsCommandPacket_ByteMode *mode) {
  EduUmassCsGnscommonPacketsCommandPacket_initialize();
  @try {
    switch ([mode ordinal]) {
      case EduUmassCsGnscommonPacketsCommandPacket_ByteMode_Enum_ORG_JSON:
      @throw create_JavaLangRuntimeException_initWithNSString_(@"Should never come here");
      case EduUmassCsGnscommonPacketsCommandPacket_ByteMode_Enum_HOMEBREW:
      return EduUmassCsGnscommonUtilsJSONByteConverter_fromBytesHardcodedWithJavaNioByteBuffer_(bbuf);
      case EduUmassCsGnscommonPacketsCommandPacket_ByteMode_Enum_STRING_WING:
      return EduUmassCsGnscommonPacketsCommandPacket_fromBytesStringerHackWithJavaNioByteBuffer_(bbuf);
      default:
      @throw create_JavaLangRuntimeException_initWithNSString_(@"Unrecognized byteification mode");
    }
  }
  @catch (JavaIoIOException *e) {
    @throw create_EduUmassCsReconfigurationReconfigurationutilsRequestParseException_initWithJavaLangException_(e);
  }
  @catch (OrgJsonJSONException *e) {
    @throw create_EduUmassCsReconfigurationReconfigurationutilsRequestParseException_initWithJavaLangException_(e);
  }
}

JavaNioByteBuffer *EduUmassCsGnscommonPacketsCommandPacket_toByteBufferWithOuterFields(EduUmassCsGnscommonPacketsCommandPacket *self) {
  @synchronized(self->command_) {
    return [((JavaNioByteBuffer *) nil_chk([((JavaNioByteBuffer *) nil_chk([((JavaNioByteBuffer *) nil_chk([((JavaNioByteBuffer *) nil_chk(JavaNioByteBuffer_allocateWithInt_(512))) putIntWithInt:[((EduUmassCsGnsserverGnsappPacketPacket_PacketType *) nil_chk([self getType])) getInt]])) putLongWithLong:self->clientRequestId_])) putWithByte:self->forceCoordination_ ? (jbyte) 1 : (jbyte) 0])) putWithByte:(jbyte) ((EduUmassCsGnscommonPacketsCommandPacket_ByteMode *) nil_chk(EduUmassCsGnscommonPacketsCommandPacket_byteMode))->val_];
  }
}

IOSByteArray *EduUmassCsGnscommonPacketsCommandPacket_appendByteifiedInnerJSONCommandWithJavaNioByteBuffer_withByteArray_(EduUmassCsGnscommonPacketsCommandPacket *self, JavaNioByteBuffer *bbuf, IOSByteArray *inner) {
  return [((JavaNioByteBuffer *) nil_chk(bbuf)) remaining] >= ((IOSByteArray *) nil_chk(inner))->size_ ? JavaUtilArrays_copyOfRangeWithByteArray_withInt_withInt_([((JavaNioByteBuffer *) nil_chk([bbuf putWithByteArray:inner])) array], 0, [bbuf position]) : [((JavaNioByteBuffer *) nil_chk([((JavaNioByteBuffer *) nil_chk([((JavaNioByteBuffer *) nil_chk(JavaNioByteBuffer_allocateWithInt_([bbuf position] + inner->size_))) putWithByteArray:[bbuf array] withInt:0 withInt:[bbuf position]])) putWithByteArray:inner])) array];
}

IOSByteArray *EduUmassCsGnscommonPacketsCommandPacket_toBytesWingItAsStringWithJavaNioByteBuffer_withOrgJsonJSONObject_(EduUmassCsGnscommonPacketsCommandPacket *self, JavaNioByteBuffer *buf, OrgJsonJSONObject *json) {
  JavaLangInteger *commandType = (JavaLangInteger *) cast_chk([((OrgJsonJSONObject *) nil_chk(self->command_)) removeWithNSString:[((EduUmassCsGnscommonGNSProtocol *) nil_chk(JreLoadEnum(EduUmassCsGnscommonGNSProtocol, COMMAND_INT))) description]], [JavaLangInteger class]);
  JreAssert(((commandType != nil)), (@"edu/umass/cs/gnscommon/packets/CommandPacket.java:250 condition failed: assert (commandType != null);"));
  [((JavaNioByteBuffer *) nil_chk(buf)) putIntWithInt:commandType != nil ? [commandType intValue] : -1];
  id<JavaUtilIterator> keys = [self->command_ keys];
  id objVal = nil;
  NSString *key = nil;
  @try {
    while ([((id<JavaUtilIterator>) nil_chk(keys)) hasNext]) {
      key = [keys next];
      IOSByteArray *keyBytes = [((NSString *) nil_chk(key)) java_getBytesWithCharsetName:EduUmassCsNioMessageNIOTransport_NIO_CHARSET_ENCODING];
      objVal = [self->command_ getWithNSString:key];
      IOSByteArray *valueBytes = [((NSString *) nil_chk(((NSString *) cast_chk(objVal, [NSString class])))) java_getBytesWithCharsetName:EduUmassCsNioMessageNIOTransport_NIO_CHARSET_ENCODING];
      if ([buf remaining] < (JavaLangInteger_BYTES + ((IOSByteArray *) nil_chk(keyBytes))->size_ + JavaLangInteger_BYTES + ((IOSByteArray *) nil_chk(valueBytes))->size_)) {
        buf = [((JavaNioByteBuffer *) nil_chk(JavaNioByteBuffer_allocateWithInt_([buf capacity] * 2 + JavaLangInteger_BYTES + keyBytes->size_ + JavaLangInteger_BYTES + valueBytes->size_))) putWithJavaNioByteBuffer:(JavaNioByteBuffer *) cast_chk([buf flip], [JavaNioByteBuffer class])];
      }
      [((JavaNioByteBuffer *) nil_chk([((JavaNioByteBuffer *) nil_chk([((JavaNioByteBuffer *) nil_chk([((JavaNioByteBuffer *) nil_chk(buf)) putIntWithInt:keyBytes->size_])) putWithByteArray:keyBytes])) putIntWithInt:valueBytes->size_])) putWithByteArray:valueBytes];
    }
    return [((JavaNioByteBuffer *) nil_chk([((JavaNioByteBuffer *) nil_chk(JavaNioByteBuffer_wrapWithByteArray_([IOSByteArray arrayWithLength:[buf position]]))) putWithByteArray:[buf array] withInt:0 withInt:[buf position]])) array];
  }
  @catch (JavaIoUnsupportedEncodingException *e) {
    return EduUmassCsGnscommonPacketsCommandPacket_handleSerializationExceptionWithJavaLangException_withJavaLangInteger_(self, e, commandType);
  }
  @catch (OrgJsonJSONException *e) {
    return EduUmassCsGnscommonPacketsCommandPacket_handleSerializationExceptionWithJavaLangException_withJavaLangInteger_(self, e, commandType);
  }
  @catch (JavaLangClassCastException *e) {
    return EduUmassCsGnscommonPacketsCommandPacket_handleSerializationExceptionWithJavaLangException_withJavaLangInteger_(self, e, commandType);
  }
  @finally {
    @try {
      EduUmassCsGnscommonPacketsCommandPacket_putBackRemovedWithJavaLangInteger_(self, commandType);
    }
    @catch (OrgJsonJSONException *e) {
      return EduUmassCsGnscommonPacketsCommandPacket_handleSerializationExceptionWithJavaLangException_withJavaLangInteger_(self, e, commandType);
    }
  }
}

void EduUmassCsGnscommonPacketsCommandPacket_putBackRemovedWithJavaLangInteger_(EduUmassCsGnscommonPacketsCommandPacket *self, JavaLangInteger *commandType) {
  if (commandType != nil) {
    [((OrgJsonJSONObject *) nil_chk(self->command_)) putWithNSString:[((EduUmassCsGnscommonGNSProtocol *) nil_chk(JreLoadEnum(EduUmassCsGnscommonGNSProtocol, COMMAND_INT))) description] withId:commandType];
  }
  ;
}

IOSByteArray *EduUmassCsGnscommonPacketsCommandPacket_handleSerializationExceptionWithJavaLangException_withJavaLangInteger_(EduUmassCsGnscommonPacketsCommandPacket *self, JavaLangException *e, JavaLangInteger *commandType) {
  if (EduUmassCsUtilsConfig_getGlobalBooleanWithJavaLangEnum_(JreLoadEnum(EduUmassCsGigapaxosPaxosConfig_PC, ENABLE_INSTRUMENTATION))) {
    @throw create_JavaLangRuntimeException_initWithNSException_(e);
  }
  @try {
    [((OrgJsonJSONObject *) nil_chk(self->command_)) putWithNSString:[((EduUmassCsGnscommonGNSProtocol *) nil_chk(JreLoadEnum(EduUmassCsGnscommonGNSProtocol, COMMAND_INT))) description] withId:commandType];
  }
  @catch (OrgJsonJSONException *e1) {
    @throw create_JavaLangRuntimeException_initWithNSException_(e1);
  }
  return EduUmassCsGnscommonPacketsCommandPacket_toJSONBytes(self);
}

IOSByteArray *EduUmassCsGnscommonPacketsCommandPacket_toJSONBytes(EduUmassCsGnscommonPacketsCommandPacket *self) {
  @try {
    return [((NSString *) nil_chk([self description])) java_getBytesWithCharsetName:EduUmassCsNioMessageNIOTransport_NIO_CHARSET_ENCODING];
  }
  @catch (JavaIoUnsupportedEncodingException *e) {
    @throw create_JavaLangRuntimeException_initWithNSException_(e);
  }
}

EduUmassCsGnscommonCommandType *EduUmassCsGnscommonPacketsCommandPacket_getJSONCommandTypeWithOrgJsonJSONObject_(OrgJsonJSONObject *command) {
  EduUmassCsGnscommonPacketsCommandPacket_initialize();
  @try {
    if (command != nil) {
      if ([command hasWithNSString:[((EduUmassCsGnscommonGNSProtocol *) nil_chk(JreLoadEnum(EduUmassCsGnscommonGNSProtocol, COMMAND_INT))) description]]) {
        return EduUmassCsGnscommonCommandType_getCommandTypeWithInt_([command getIntWithNSString:[JreLoadEnum(EduUmassCsGnscommonGNSProtocol, COMMAND_INT) description]]);
      }
      if ([command hasWithNSString:[((EduUmassCsGnscommonGNSProtocol *) nil_chk(JreLoadEnum(EduUmassCsGnscommonGNSProtocol, COMMANDNAME))) description]]) {
        return EduUmassCsGnscommonCommandType_valueOfWithNSString_([command getStringWithNSString:[JreLoadEnum(EduUmassCsGnscommonGNSProtocol, COMMANDNAME) description]]);
      }
    }
  }
  @catch (JavaLangIllegalArgumentException *e) {
  }
  @catch (OrgJsonJSONException *e) {
  }
  return JreLoadEnum(EduUmassCsGnscommonCommandType, Unknown);
}

NSString *EduUmassCsGnscommonPacketsCommandPacket_getRespStr(EduUmassCsGnscommonPacketsCommandPacket *self) {
  [self finish];
  if (self->result_ != nil) {
    EduUmassCsGnscommonPacketsResponsePacket *responsePacket = EduUmassCsGnsclientClientCommandUtils_checkResponseWithEduUmassCsGnscommonPacketsResponsePacket_withEduUmassCsGnscommonPacketsCommandPacket_((EduUmassCsGnscommonPacketsResponsePacket *) cast_chk(self->result_, [EduUmassCsGnscommonPacketsResponsePacket class]), self);
    if (responsePacket == nil) {
      return nil;
    }
    else {
      return [responsePacket getReturnValue];
    }
  }
  else {
    return nil;
  }
}

id EduUmassCsGnscommonPacketsCommandPacket_getResultValueFromStringWithNSString_(NSString *str) {
  EduUmassCsGnscommonPacketsCommandPacket_initialize();
  return OrgJsonJSONObject_stringToValueWithNSString_(str);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsGnscommonPacketsCommandPacket)

J2OBJC_INITIALIZED_DEFN(EduUmassCsGnscommonPacketsCommandPacket_ByteMode)

EduUmassCsGnscommonPacketsCommandPacket_ByteMode *EduUmassCsGnscommonPacketsCommandPacket_ByteMode_values_[5];

@implementation EduUmassCsGnscommonPacketsCommandPacket_ByteMode

+ (IOSObjectArray *)values {
  return EduUmassCsGnscommonPacketsCommandPacket_ByteMode_values();
}

+ (EduUmassCsGnscommonPacketsCommandPacket_ByteMode *)valueOfWithNSString:(NSString *)name {
  return EduUmassCsGnscommonPacketsCommandPacket_ByteMode_valueOfWithNSString_(name);
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "[LEduUmassCsGnscommonPacketsCommandPacket_ByteMode;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsGnscommonPacketsCommandPacket_ByteMode;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(values);
  methods[1].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "ORG_JSON", "LEduUmassCsGnscommonPacketsCommandPacket_ByteMode;", .constantValue.asLong = 0, 0x4019, -1, 2, -1, -1 },
    { "HOMEBREW", "LEduUmassCsGnscommonPacketsCommandPacket_ByteMode;", .constantValue.asLong = 0, 0x4019, -1, 3, -1, -1 },
    { "JACKSON", "LEduUmassCsGnscommonPacketsCommandPacket_ByteMode;", .constantValue.asLong = 0, 0x4019, -1, 4, -1, -1 },
    { "MSGPACK", "LEduUmassCsGnscommonPacketsCommandPacket_ByteMode;", .constantValue.asLong = 0, 0x4019, -1, 5, -1, -1 },
    { "STRING_WING", "LEduUmassCsGnscommonPacketsCommandPacket_ByteMode;", .constantValue.asLong = 0, 0x4019, -1, 6, -1, -1 },
    { "val_", "I", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "byteModeMap", "LJavaUtilMap;", .constantValue.asLong = 0, 0x1a, -1, 7, 8, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "LNSString;", &JreEnum(EduUmassCsGnscommonPacketsCommandPacket_ByteMode, ORG_JSON), &JreEnum(EduUmassCsGnscommonPacketsCommandPacket_ByteMode, HOMEBREW), &JreEnum(EduUmassCsGnscommonPacketsCommandPacket_ByteMode, JACKSON), &JreEnum(EduUmassCsGnscommonPacketsCommandPacket_ByteMode, MSGPACK), &JreEnum(EduUmassCsGnscommonPacketsCommandPacket_ByteMode, STRING_WING), &EduUmassCsGnscommonPacketsCommandPacket_ByteMode_byteModeMap, "Ljava/util/Map<Ljava/lang/Integer;Ledu/umass/cs/gnscommon/packets/CommandPacket$ByteMode;>;", "LEduUmassCsGnscommonPacketsCommandPacket;", "Ljava/lang/Enum<Ledu/umass/cs/gnscommon/packets/CommandPacket$ByteMode;>;" };
  static const J2ObjcClassInfo _EduUmassCsGnscommonPacketsCommandPacket_ByteMode = { "ByteMode", "edu.umass.cs.gnscommon.packets", ptrTable, methods, fields, 7, 0x401a, 2, 7, 9, -1, -1, 10, -1 };
  return &_EduUmassCsGnscommonPacketsCommandPacket_ByteMode;
}

+ (void)initialize {
  if (self == [EduUmassCsGnscommonPacketsCommandPacket_ByteMode class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 5 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    (JreEnum(EduUmassCsGnscommonPacketsCommandPacket_ByteMode, ORG_JSON) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    EduUmassCsGnscommonPacketsCommandPacket_ByteMode_initWithInt_withNSString_withInt_(e, 0, @"ORG_JSON", 0);
    (JreEnum(EduUmassCsGnscommonPacketsCommandPacket_ByteMode, HOMEBREW) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    EduUmassCsGnscommonPacketsCommandPacket_ByteMode_initWithInt_withNSString_withInt_(e, 1, @"HOMEBREW", 1);
    (JreEnum(EduUmassCsGnscommonPacketsCommandPacket_ByteMode, JACKSON) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    EduUmassCsGnscommonPacketsCommandPacket_ByteMode_initWithInt_withNSString_withInt_(e, 2, @"JACKSON", 2);
    (JreEnum(EduUmassCsGnscommonPacketsCommandPacket_ByteMode, MSGPACK) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    EduUmassCsGnscommonPacketsCommandPacket_ByteMode_initWithInt_withNSString_withInt_(e, 3, @"MSGPACK", 3);
    (JreEnum(EduUmassCsGnscommonPacketsCommandPacket_ByteMode, STRING_WING) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    EduUmassCsGnscommonPacketsCommandPacket_ByteMode_initWithInt_withNSString_withInt_(e, 4, @"STRING_WING", 4);
    JreStrongAssignAndConsume(&EduUmassCsGnscommonPacketsCommandPacket_ByteMode_byteModeMap, new_JavaUtilHashMap_init());
    {
      {
        IOSObjectArray *a__ = EduUmassCsGnscommonPacketsCommandPacket_ByteMode_values();
        EduUmassCsGnscommonPacketsCommandPacket_ByteMode * const *b__ = ((IOSObjectArray *) nil_chk(a__))->buffer_;
        EduUmassCsGnscommonPacketsCommandPacket_ByteMode * const *e__ = b__ + a__->size_;
        while (b__ < e__) {
          EduUmassCsGnscommonPacketsCommandPacket_ByteMode *mode = *b__++;
          [EduUmassCsGnscommonPacketsCommandPacket_ByteMode_byteModeMap putWithId:JavaLangInteger_valueOfWithInt_(((EduUmassCsGnscommonPacketsCommandPacket_ByteMode *) nil_chk(mode))->val_) withId:mode];
        }
      }
    }
    J2OBJC_SET_INITIALIZED(EduUmassCsGnscommonPacketsCommandPacket_ByteMode)
  }
}

@end

void EduUmassCsGnscommonPacketsCommandPacket_ByteMode_initWithInt_withNSString_withInt_(EduUmassCsGnscommonPacketsCommandPacket_ByteMode *self, jint val, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
  self->val_ = val;
}

IOSObjectArray *EduUmassCsGnscommonPacketsCommandPacket_ByteMode_values() {
  EduUmassCsGnscommonPacketsCommandPacket_ByteMode_initialize();
  return [IOSObjectArray arrayWithObjects:EduUmassCsGnscommonPacketsCommandPacket_ByteMode_values_ count:5 type:EduUmassCsGnscommonPacketsCommandPacket_ByteMode_class_()];
}

EduUmassCsGnscommonPacketsCommandPacket_ByteMode *EduUmassCsGnscommonPacketsCommandPacket_ByteMode_valueOfWithNSString_(NSString *name) {
  EduUmassCsGnscommonPacketsCommandPacket_ByteMode_initialize();
  for (int i = 0; i < 5; i++) {
    EduUmassCsGnscommonPacketsCommandPacket_ByteMode *e = EduUmassCsGnscommonPacketsCommandPacket_ByteMode_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

EduUmassCsGnscommonPacketsCommandPacket_ByteMode *EduUmassCsGnscommonPacketsCommandPacket_ByteMode_fromOrdinal(NSUInteger ordinal) {
  EduUmassCsGnscommonPacketsCommandPacket_ByteMode_initialize();
  if (ordinal >= 5) {
    return nil;
  }
  return EduUmassCsGnscommonPacketsCommandPacket_ByteMode_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsGnscommonPacketsCommandPacket_ByteMode)

@implementation EduUmassCsGnscommonPacketsCommandPacket_1

- (instancetype)initWithEduUmassCsGnscommonPacketsCommandPacket:(EduUmassCsGnscommonPacketsCommandPacket *)outer$ {
  EduUmassCsGnscommonPacketsCommandPacket_1_initWithEduUmassCsGnscommonPacketsCommandPacket_(self, outer$);
  return self;
}

- (NSString *)description {
  return JreStrcat("@C$CIC$CJ$", [this$0_ getRequestType], ':', [((EduUmassCsGnscommonCommandType *) nil_chk([this$0_ getCommandType])) description], ':', [this$0_ getCommandInteger], ':', [this$0_ getServiceName], ':', [this$0_ getRequestID], ([this$0_ getClientAddress] != nil ? JreStrcat("C@C", '[', [this$0_ getClientAddress], ']') : @""));
}

- (void)dealloc {
  RELEASE_(this$0_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 0, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithEduUmassCsGnscommonPacketsCommandPacket:);
  methods[1].selector = @selector(description);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LEduUmassCsGnscommonPacketsCommandPacket;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "toString", "LEduUmassCsGnscommonPacketsCommandPacket;", "getSummary" };
  static const J2ObjcClassInfo _EduUmassCsGnscommonPacketsCommandPacket_1 = { "", "edu.umass.cs.gnscommon.packets", ptrTable, methods, fields, 7, 0x8008, 2, 1, 1, -1, 2, -1, -1 };
  return &_EduUmassCsGnscommonPacketsCommandPacket_1;
}

@end

void EduUmassCsGnscommonPacketsCommandPacket_1_initWithEduUmassCsGnscommonPacketsCommandPacket_(EduUmassCsGnscommonPacketsCommandPacket_1 *self, EduUmassCsGnscommonPacketsCommandPacket *outer$) {
  JreStrongAssign(&self->this$0_, outer$);
  NSObject_init(self);
}

EduUmassCsGnscommonPacketsCommandPacket_1 *new_EduUmassCsGnscommonPacketsCommandPacket_1_initWithEduUmassCsGnscommonPacketsCommandPacket_(EduUmassCsGnscommonPacketsCommandPacket *outer$) {
  J2OBJC_NEW_IMPL(EduUmassCsGnscommonPacketsCommandPacket_1, initWithEduUmassCsGnscommonPacketsCommandPacket_, outer$)
}

EduUmassCsGnscommonPacketsCommandPacket_1 *create_EduUmassCsGnscommonPacketsCommandPacket_1_initWithEduUmassCsGnscommonPacketsCommandPacket_(EduUmassCsGnscommonPacketsCommandPacket *outer$) {
  J2OBJC_CREATE_IMPL(EduUmassCsGnscommonPacketsCommandPacket_1, initWithEduUmassCsGnscommonPacketsCommandPacket_, outer$)
}
