//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../src/edu/umass/cs/gnscommon/packets/ResponsePacket.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsGnscommonPacketsResponsePacket")
#ifdef RESTRICT_EduUmassCsGnscommonPacketsResponsePacket
#define INCLUDE_ALL_EduUmassCsGnscommonPacketsResponsePacket 0
#else
#define INCLUDE_ALL_EduUmassCsGnscommonPacketsResponsePacket 1
#endif
#undef RESTRICT_EduUmassCsGnscommonPacketsResponsePacket

#if !defined (EduUmassCsGnscommonPacketsResponsePacket_) && (INCLUDE_ALL_EduUmassCsGnscommonPacketsResponsePacket || defined(INCLUDE_EduUmassCsGnscommonPacketsResponsePacket))
#define EduUmassCsGnscommonPacketsResponsePacket_

#define RESTRICT_EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress 1
#define INCLUDE_EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress 1
#include "edu/umass/cs/gnsserver/gnsapp/packet/BasicPacketWithClientAddress.h"

#define RESTRICT_EduUmassCsGigapaxosInterfacesClientRequest 1
#define INCLUDE_EduUmassCsGigapaxosInterfacesClientRequest 1
#include "edu/umass/cs/gigapaxos/interfaces/ClientRequest.h"

@class EduUmassCsGnscommonResponseCode;
@class EduUmassCsGnsserverGnsappClientCommandProcessorCommandSupportCommandResponse;
@class IOSByteArray;
@class OrgJsonJSONObject;

@interface EduUmassCsGnscommonPacketsResponsePacket : EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress < EduUmassCsGigapaxosInterfacesClientRequest >

#pragma mark Public

- (instancetype)initWithOrgJsonJSONObject:(OrgJsonJSONObject *)json;

- (instancetype)initWithLong:(jlong)requestId
                     withInt:(jint)errorNumber
                withNSString:(NSString *)serviceName
                withNSString:(NSString *)responseValue;

- (instancetype)initWithLong:(jlong)requestId
                withNSString:(NSString *)serviceName
withEduUmassCsGnsserverGnsappClientCommandProcessorCommandSupportCommandResponse:(EduUmassCsGnsserverGnsappClientCommandProcessorCommandSupportCommandResponse *)response
                    withLong:(jlong)requestCnt
                     withInt:(jint)requestRate
                    withLong:(jlong)cppProccessingTime;

- (instancetype)initWithNSString:(NSString *)serviceName
                        withLong:(jlong)requestId
withEduUmassCsGnscommonResponseCode:(EduUmassCsGnscommonResponseCode *)code
                    withNSString:(NSString *)returnValue;

+ (EduUmassCsGnscommonPacketsResponsePacket *)fromBytesWithByteArray:(IOSByteArray *)bytes;

- (jlong)getClientRequestId;

- (EduUmassCsGnscommonResponseCode *)getErrorCode;

- (jlong)getRequestID;

- (id<EduUmassCsGigapaxosInterfacesClientRequest>)getResponse;

- (NSString *)getReturnValue;

- (NSString *)getServiceName;

- (id)getSummary;

- (id<EduUmassCsGigapaxosInterfacesClientRequest>)setClientRequestAndLNSIdsWithLong:(jlong)requestID;

- (IOSByteArray *)toBytes;

- (OrgJsonJSONObject *)toJSONObject;

@end

J2OBJC_STATIC_INIT(EduUmassCsGnscommonPacketsResponsePacket)

FOUNDATION_EXPORT void EduUmassCsGnscommonPacketsResponsePacket_initWithLong_withNSString_withEduUmassCsGnsserverGnsappClientCommandProcessorCommandSupportCommandResponse_withLong_withInt_withLong_(EduUmassCsGnscommonPacketsResponsePacket *self, jlong requestId, NSString *serviceName, EduUmassCsGnsserverGnsappClientCommandProcessorCommandSupportCommandResponse *response, jlong requestCnt, jint requestRate, jlong cppProccessingTime);

FOUNDATION_EXPORT EduUmassCsGnscommonPacketsResponsePacket *new_EduUmassCsGnscommonPacketsResponsePacket_initWithLong_withNSString_withEduUmassCsGnsserverGnsappClientCommandProcessorCommandSupportCommandResponse_withLong_withInt_withLong_(jlong requestId, NSString *serviceName, EduUmassCsGnsserverGnsappClientCommandProcessorCommandSupportCommandResponse *response, jlong requestCnt, jint requestRate, jlong cppProccessingTime) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGnscommonPacketsResponsePacket *create_EduUmassCsGnscommonPacketsResponsePacket_initWithLong_withNSString_withEduUmassCsGnsserverGnsappClientCommandProcessorCommandSupportCommandResponse_withLong_withInt_withLong_(jlong requestId, NSString *serviceName, EduUmassCsGnsserverGnsappClientCommandProcessorCommandSupportCommandResponse *response, jlong requestCnt, jint requestRate, jlong cppProccessingTime);

FOUNDATION_EXPORT void EduUmassCsGnscommonPacketsResponsePacket_initWithNSString_withLong_withEduUmassCsGnscommonResponseCode_withNSString_(EduUmassCsGnscommonPacketsResponsePacket *self, NSString *serviceName, jlong requestId, EduUmassCsGnscommonResponseCode *code, NSString *returnValue);

FOUNDATION_EXPORT EduUmassCsGnscommonPacketsResponsePacket *new_EduUmassCsGnscommonPacketsResponsePacket_initWithNSString_withLong_withEduUmassCsGnscommonResponseCode_withNSString_(NSString *serviceName, jlong requestId, EduUmassCsGnscommonResponseCode *code, NSString *returnValue) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGnscommonPacketsResponsePacket *create_EduUmassCsGnscommonPacketsResponsePacket_initWithNSString_withLong_withEduUmassCsGnscommonResponseCode_withNSString_(NSString *serviceName, jlong requestId, EduUmassCsGnscommonResponseCode *code, NSString *returnValue);

FOUNDATION_EXPORT void EduUmassCsGnscommonPacketsResponsePacket_initWithOrgJsonJSONObject_(EduUmassCsGnscommonPacketsResponsePacket *self, OrgJsonJSONObject *json);

FOUNDATION_EXPORT EduUmassCsGnscommonPacketsResponsePacket *new_EduUmassCsGnscommonPacketsResponsePacket_initWithOrgJsonJSONObject_(OrgJsonJSONObject *json) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGnscommonPacketsResponsePacket *create_EduUmassCsGnscommonPacketsResponsePacket_initWithOrgJsonJSONObject_(OrgJsonJSONObject *json);

FOUNDATION_EXPORT void EduUmassCsGnscommonPacketsResponsePacket_initWithLong_withInt_withNSString_withNSString_(EduUmassCsGnscommonPacketsResponsePacket *self, jlong requestId, jint errorNumber, NSString *serviceName, NSString *responseValue);

FOUNDATION_EXPORT EduUmassCsGnscommonPacketsResponsePacket *new_EduUmassCsGnscommonPacketsResponsePacket_initWithLong_withInt_withNSString_withNSString_(jlong requestId, jint errorNumber, NSString *serviceName, NSString *responseValue) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGnscommonPacketsResponsePacket *create_EduUmassCsGnscommonPacketsResponsePacket_initWithLong_withInt_withNSString_withNSString_(jlong requestId, jint errorNumber, NSString *serviceName, NSString *responseValue);

FOUNDATION_EXPORT EduUmassCsGnscommonPacketsResponsePacket *EduUmassCsGnscommonPacketsResponsePacket_fromBytesWithByteArray_(IOSByteArray *bytes);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsGnscommonPacketsResponsePacket)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsGnscommonPacketsResponsePacket")
