//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../src/edu/umass/cs/gnsclient/client/util/keystorage/AbstractKeyStorage.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "edu/umass/cs/gnsclient/client/util/keystorage/AbstractKeyStorage.h"

@implementation EduUmassCsGnsclientClientUtilKeystorageAbstractKeyStorage

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  EduUmassCsGnsclientClientUtilKeystorageAbstractKeyStorage_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (NSString *)getWithNSString:(NSString *)key
                 withNSString:(NSString *)def {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (void)removeWithNSString:(NSString *)key {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

- (void)putWithNSString:(NSString *)key
           withNSString:(NSString *)value {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

- (IOSObjectArray *)keys {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (void)clear {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

- (NSString *)description {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 2, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 4, 1, -1, -1, -1, -1 },
    { NULL, "[LNSString;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, 5, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getWithNSString:withNSString:);
  methods[2].selector = @selector(removeWithNSString:);
  methods[3].selector = @selector(putWithNSString:withNSString:);
  methods[4].selector = @selector(keys);
  methods[5].selector = @selector(clear);
  methods[6].selector = @selector(description);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "get", "LNSString;LNSString;", "remove", "LNSString;", "put", "toString" };
  static const J2ObjcClassInfo _EduUmassCsGnsclientClientUtilKeystorageAbstractKeyStorage = { "AbstractKeyStorage", "edu.umass.cs.gnsclient.client.util.keystorage", ptrTable, methods, NULL, 7, 0x401, 7, 0, -1, -1, -1, -1, -1 };
  return &_EduUmassCsGnsclientClientUtilKeystorageAbstractKeyStorage;
}

@end

void EduUmassCsGnsclientClientUtilKeystorageAbstractKeyStorage_init(EduUmassCsGnsclientClientUtilKeystorageAbstractKeyStorage *self) {
  NSObject_init(self);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsGnsclientClientUtilKeystorageAbstractKeyStorage)
