//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../gig_ios/src/edu/umass/cs/gigapaxos/interfaces/RequestCallback.java
//

#include "J2ObjC_source.h"
#include "edu/umass/cs/gigapaxos/interfaces/Request.h"
#include "edu/umass/cs/gigapaxos/interfaces/RequestCallback.h"

@interface EduUmassCsGigapaxosInterfacesRequestCallback : NSObject

@end

@implementation EduUmassCsGigapaxosInterfacesRequestCallback

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsGigapaxosInterfacesRequest;", 0x1, 2, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(handleResponseWithEduUmassCsGigapaxosInterfacesRequest:);
  methods[1].selector = @selector(processResponseWithId:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "handleResponse", "LEduUmassCsGigapaxosInterfacesRequest;", "processResponse", "Ljava/lang/Object;Ledu/umass/cs/gigapaxos/interfaces/Callback<Ledu/umass/cs/gigapaxos/interfaces/Request;Ledu/umass/cs/gigapaxos/interfaces/Request;>;" };
  static const J2ObjcClassInfo _EduUmassCsGigapaxosInterfacesRequestCallback = { "RequestCallback", "edu.umass.cs.gigapaxos.interfaces", ptrTable, methods, NULL, 7, 0x609, 2, 0, -1, -1, -1, 3, -1 };
  return &_EduUmassCsGigapaxosInterfacesRequestCallback;
}

@end

id<EduUmassCsGigapaxosInterfacesRequest> EduUmassCsGigapaxosInterfacesRequestCallback_processResponseWithEduUmassCsGigapaxosInterfacesRequest_(id<EduUmassCsGigapaxosInterfacesRequestCallback> self, id<EduUmassCsGigapaxosInterfacesRequest> response) {
  [self handleResponseWithEduUmassCsGigapaxosInterfacesRequest:response];
  return nil;
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(EduUmassCsGigapaxosInterfacesRequestCallback)
