//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../gig_ios/src/edu/umass/cs/reconfiguration/reconfigurationpackets/AckStopEpoch.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "edu/umass/cs/nio/interfaces/IntegerPacketType.h"
#include "edu/umass/cs/nio/interfaces/Stringifiable.h"
#include "edu/umass/cs/reconfiguration/reconfigurationpackets/AckStopEpoch.h"
#include "edu/umass/cs/reconfiguration/reconfigurationpackets/BasicReconfigurationPacket.h"
#include "edu/umass/cs/reconfiguration/reconfigurationpackets/ReconfigurationPacket.h"
#include "edu/umass/cs/reconfiguration/reconfigurationpackets/StopEpoch.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "org/json/JSONObject.h"

#pragma clang diagnostic ignored "-Wincomplete-implementation"

@interface EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch () {
 @public
  NSString *finalState_;
}

@end

J2OBJC_FIELD_SETTER(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch, finalState_, NSString *)

typedef NS_ENUM(NSUInteger, EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_Enum) {
  EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_Enum_FINAL_STATE = 0,
};

@interface EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys : JavaLangEnum < NSCopying >

+ (IOSObjectArray *)values;

+ (EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys *)valueOfWithNSString:(NSString *)name;

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys *EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_values_[];

inline EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys *EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_get_FINAL_STATE();
J2OBJC_ENUM_CONSTANT(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys, FINAL_STATE)

__attribute__((unused)) static void EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_initWithNSString_withInt_(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static IOSObjectArray *EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_values();

__attribute__((unused)) static EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys *EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys *EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys)

@implementation EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch

- (instancetype)initWithId:(id)sender
withEduUmassCsReconfigurationReconfigurationpacketsStopEpoch:(EduUmassCsReconfigurationReconfigurationpacketsStopEpoch *)stopEpoch
              withNSString:(NSString *)finalState {
  EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_initWithId_withEduUmassCsReconfigurationReconfigurationpacketsStopEpoch_withNSString_(self, sender, stopEpoch, finalState);
  return self;
}

- (instancetype)initWithId:(id)sender
withEduUmassCsReconfigurationReconfigurationpacketsStopEpoch:(EduUmassCsReconfigurationReconfigurationpacketsStopEpoch *)stopEpoch {
  EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_initWithId_withEduUmassCsReconfigurationReconfigurationpacketsStopEpoch_(self, sender, stopEpoch);
  return self;
}

- (instancetype)initWithOrgJsonJSONObject:(OrgJsonJSONObject *)json
 withEduUmassCsNioInterfacesStringifiable:(id<EduUmassCsNioInterfacesStringifiable>)unstringer {
  EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_(self, json, unstringer);
  return self;
}

- (OrgJsonJSONObject *)toJSONObjectImpl {
  OrgJsonJSONObject *json = [super toJSONObjectImpl];
  [((OrgJsonJSONObject *) nil_chk(json)) putWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys, FINAL_STATE))) description] withId:self->finalState_];
  return json;
}

- (id<EduUmassCsNioInterfacesIntegerPacketType>)getRequestType {
  return [self getType];
}

- (NSString *)getFinalState {
  return self->finalState_;
}

- (void)dealloc {
  RELEASE_(finalState_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, 1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, 3, -1, -1 },
    { NULL, NULL, 0x1, -1, 4, 5, 6, -1, -1 },
    { NULL, "LOrgJsonJSONObject;", 0x1, -1, -1, 5, -1, -1, -1 },
    { NULL, "LEduUmassCsNioInterfacesIntegerPacketType;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithId:withEduUmassCsReconfigurationReconfigurationpacketsStopEpoch:withNSString:);
  methods[1].selector = @selector(initWithId:withEduUmassCsReconfigurationReconfigurationpacketsStopEpoch:);
  methods[2].selector = @selector(initWithOrgJsonJSONObject:withEduUmassCsNioInterfacesStringifiable:);
  methods[3].selector = @selector(toJSONObjectImpl);
  methods[4].selector = @selector(getRequestType);
  methods[5].selector = @selector(getFinalState);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "finalState_", "LNSString;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSObject;LEduUmassCsReconfigurationReconfigurationpacketsStopEpoch;LNSString;", "(TNodeIDType;Ledu/umass/cs/reconfiguration/reconfigurationpackets/StopEpoch<TNodeIDType;>;Ljava/lang/String;)V", "LNSObject;LEduUmassCsReconfigurationReconfigurationpacketsStopEpoch;", "(TNodeIDType;Ledu/umass/cs/reconfiguration/reconfigurationpackets/StopEpoch<TNodeIDType;>;)V", "LOrgJsonJSONObject;LEduUmassCsNioInterfacesStringifiable;", "LOrgJsonJSONException;", "(Lorg/json/JSONObject;Ledu/umass/cs/nio/interfaces/Stringifiable<TNodeIDType;>;)V", "LEduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys;", "<NodeIDType:Ljava/lang/Object;>Ledu/umass/cs/reconfiguration/reconfigurationpackets/BasicReconfigurationPacket<TNodeIDType;>;Ledu/umass/cs/gigapaxos/interfaces/Request;" };
  static const J2ObjcClassInfo _EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch = { "AckStopEpoch", "edu.umass.cs.reconfiguration.reconfigurationpackets", ptrTable, methods, fields, 7, 0x1, 6, 1, -1, 7, -1, 8, -1 };
  return &_EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch;
}

@end

void EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_initWithId_withEduUmassCsReconfigurationReconfigurationpacketsStopEpoch_withNSString_(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch *self, id sender, EduUmassCsReconfigurationReconfigurationpacketsStopEpoch *stopEpoch, NSString *finalState) {
  EduUmassCsReconfigurationReconfigurationpacketsBasicReconfigurationPacket_initWithId_withEduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType_withNSString_withInt_(self, [((EduUmassCsReconfigurationReconfigurationpacketsStopEpoch *) nil_chk(stopEpoch)) getInitiator], JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType, ACK_STOP_EPOCH), [stopEpoch getServiceName], [stopEpoch getEpochNumber]);
  [self setKeyWithId:[stopEpoch getKey]];
  [self setSenderWithId:sender];
  JreStrongAssign(&self->finalState_, finalState);
}

EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch *new_EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_initWithId_withEduUmassCsReconfigurationReconfigurationpacketsStopEpoch_withNSString_(id sender, EduUmassCsReconfigurationReconfigurationpacketsStopEpoch *stopEpoch, NSString *finalState) {
  J2OBJC_NEW_IMPL(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch, initWithId_withEduUmassCsReconfigurationReconfigurationpacketsStopEpoch_withNSString_, sender, stopEpoch, finalState)
}

EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch *create_EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_initWithId_withEduUmassCsReconfigurationReconfigurationpacketsStopEpoch_withNSString_(id sender, EduUmassCsReconfigurationReconfigurationpacketsStopEpoch *stopEpoch, NSString *finalState) {
  J2OBJC_CREATE_IMPL(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch, initWithId_withEduUmassCsReconfigurationReconfigurationpacketsStopEpoch_withNSString_, sender, stopEpoch, finalState)
}

void EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_initWithId_withEduUmassCsReconfigurationReconfigurationpacketsStopEpoch_(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch *self, id sender, EduUmassCsReconfigurationReconfigurationpacketsStopEpoch *stopEpoch) {
  EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_initWithId_withEduUmassCsReconfigurationReconfigurationpacketsStopEpoch_withNSString_(self, sender, stopEpoch, nil);
}

EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch *new_EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_initWithId_withEduUmassCsReconfigurationReconfigurationpacketsStopEpoch_(id sender, EduUmassCsReconfigurationReconfigurationpacketsStopEpoch *stopEpoch) {
  J2OBJC_NEW_IMPL(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch, initWithId_withEduUmassCsReconfigurationReconfigurationpacketsStopEpoch_, sender, stopEpoch)
}

EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch *create_EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_initWithId_withEduUmassCsReconfigurationReconfigurationpacketsStopEpoch_(id sender, EduUmassCsReconfigurationReconfigurationpacketsStopEpoch *stopEpoch) {
  J2OBJC_CREATE_IMPL(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch, initWithId_withEduUmassCsReconfigurationReconfigurationpacketsStopEpoch_, sender, stopEpoch)
}

void EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch *self, OrgJsonJSONObject *json, id<EduUmassCsNioInterfacesStringifiable> unstringer) {
  EduUmassCsReconfigurationReconfigurationpacketsBasicReconfigurationPacket_initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_(self, json, unstringer);
  JreStrongAssign(&self->finalState_, [((OrgJsonJSONObject *) nil_chk(json)) hasWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys, FINAL_STATE))) description]] ? [json getStringWithNSString:[JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys, FINAL_STATE) description]] : nil);
}

EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch *new_EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_(OrgJsonJSONObject *json, id<EduUmassCsNioInterfacesStringifiable> unstringer) {
  J2OBJC_NEW_IMPL(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch, initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_, json, unstringer)
}

EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch *create_EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_(OrgJsonJSONObject *json, id<EduUmassCsNioInterfacesStringifiable> unstringer) {
  J2OBJC_CREATE_IMPL(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch, initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_, json, unstringer)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch)

J2OBJC_INITIALIZED_DEFN(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys)

EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys *EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_values_[1];

@implementation EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys

+ (IOSObjectArray *)values {
  return EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_values();
}

+ (EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys *)valueOfWithNSString:(NSString *)name {
  return EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_valueOfWithNSString_(name);
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "[LEduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(values);
  methods[1].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "FINAL_STATE", "LEduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys;", .constantValue.asLong = 0, 0x4019, -1, 2, -1, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "LNSString;", &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys, FINAL_STATE), "LEduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch;", "Ljava/lang/Enum<Ledu/umass/cs/reconfiguration/reconfigurationpackets/AckStopEpoch$Keys;>;" };
  static const J2ObjcClassInfo _EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys = { "Keys", "edu.umass.cs.reconfiguration.reconfigurationpackets", ptrTable, methods, fields, 7, 0x401a, 2, 1, 3, -1, -1, 4, -1 };
  return &_EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys;
}

+ (void)initialize {
  if (self == [EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 1 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    id names[] = {
      @"FINAL_STATE",
    };
    for (jint i = 0; i < 1; i++) {
      (EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_values_[i] = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
      EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_initWithNSString_withInt_(e, names[i], i);
    }
    J2OBJC_SET_INITIALIZED(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys)
  }
}

@end

void EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_initWithNSString_withInt_(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

IOSObjectArray *EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_values() {
  EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_initialize();
  return [IOSObjectArray arrayWithObjects:EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_values_ count:1 type:EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_class_()];
}

EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys *EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_valueOfWithNSString_(NSString *name) {
  EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_initialize();
  for (int i = 0; i < 1; i++) {
    EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys *e = EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys *EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_fromOrdinal(NSUInteger ordinal) {
  EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_initialize();
  if (ordinal >= 1) {
    return nil;
  }
  return EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsReconfigurationReconfigurationpacketsAckStopEpoch_Keys)
