//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../gig_ios/src/edu/umass/cs/reconfiguration/reconfigurationpackets/ActiveReplicaError.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "edu/umass/cs/nio/interfaces/Stringifiable.h"
#include "edu/umass/cs/reconfiguration/reconfigurationpackets/ActiveReplicaError.h"
#include "edu/umass/cs/reconfiguration/reconfigurationpackets/ClientReconfigurationPacket.h"
#include "edu/umass/cs/reconfiguration/reconfigurationpackets/ReconfigurationPacket.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/net/InetSocketAddress.h"
#include "org/json/JSONObject.h"

#pragma clang diagnostic ignored "-Wincomplete-implementation"

@interface EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError () {
 @public
  jlong requestID_;
  EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes *code_;
}

@end

J2OBJC_FIELD_SETTER(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError, code_, EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes *)

typedef NS_ENUM(NSUInteger, EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_Enum) {
  EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_Enum_REQUEST_ID = 0,
  EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_Enum_ERROR_CODE = 1,
};

@interface EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys : JavaLangEnum < NSCopying >

+ (IOSObjectArray *)values;

+ (EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys *)valueOfWithNSString:(NSString *)name;

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys *EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_values_[];

inline EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys *EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_get_REQUEST_ID();
J2OBJC_ENUM_CONSTANT(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys, REQUEST_ID)

inline EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys *EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_get_ERROR_CODE();
J2OBJC_ENUM_CONSTANT(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys, ERROR_CODE)

__attribute__((unused)) static void EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_initWithNSString_withInt_(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static IOSObjectArray *EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_values();

__attribute__((unused)) static EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys *EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys *EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys)

@implementation EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError

- (instancetype)initWithJavaNetInetSocketAddress:(JavaNetInetSocketAddress *)initiator
                                    withNSString:(NSString *)name
                                        withLong:(jlong)requestID {
  EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_initWithJavaNetInetSocketAddress_withNSString_withLong_(self, initiator, name, requestID);
  return self;
}

- (instancetype)initWithNSString:(NSString *)name
                        withLong:(jlong)requestID
withEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket:(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket *)crp {
  EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_initWithNSString_withLong_withEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_(self, name, requestID, crp);
  return self;
}

- (instancetype)initWithOrgJsonJSONObject:(OrgJsonJSONObject *)json {
  EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_initWithOrgJsonJSONObject_(self, json);
  return self;
}

- (instancetype)initWithOrgJsonJSONObject:(OrgJsonJSONObject *)json
 withEduUmassCsNioInterfacesStringifiable:(id<EduUmassCsNioInterfacesStringifiable>)unstringer {
  EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_(self, json, unstringer);
  return self;
}

- (OrgJsonJSONObject *)toJSONObjectImpl {
  OrgJsonJSONObject *json = [super toJSONObjectImpl];
  [((OrgJsonJSONObject *) nil_chk(json)) putWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys, REQUEST_ID))) description] withLong:self->requestID_];
  [json putWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys, ERROR_CODE))) description] withId:self->code_];
  return json;
}

- (jlong)getRequestID {
  return self->requestID_;
}

- (NSString *)getSummary {
  return JreStrcat("@C$CJ", self->code_, ':', [super getSummary], ':', self->requestID_);
}

- (void)dealloc {
  RELEASE_(code_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, 3, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 4, 3, 5, -1, -1 },
    { NULL, "LOrgJsonJSONObject;", 0x1, -1, -1, 3, -1, -1, -1 },
    { NULL, "J", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithJavaNetInetSocketAddress:withNSString:withLong:);
  methods[1].selector = @selector(initWithNSString:withLong:withEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket:);
  methods[2].selector = @selector(initWithOrgJsonJSONObject:);
  methods[3].selector = @selector(initWithOrgJsonJSONObject:withEduUmassCsNioInterfacesStringifiable:);
  methods[4].selector = @selector(toJSONObjectImpl);
  methods[5].selector = @selector(getRequestID);
  methods[6].selector = @selector(getSummary);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "requestID_", "J", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "code_", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LJavaNetInetSocketAddress;LNSString;J", "LNSString;JLEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket;", "LOrgJsonJSONObject;", "LOrgJsonJSONException;", "LOrgJsonJSONObject;LEduUmassCsNioInterfacesStringifiable;", "(Lorg/json/JSONObject;Ledu/umass/cs/nio/interfaces/Stringifiable<*>;)V", "LEduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys;" };
  static const J2ObjcClassInfo _EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError = { "ActiveReplicaError", "edu.umass.cs.reconfiguration.reconfigurationpackets", ptrTable, methods, fields, 7, 0x1, 7, 2, -1, 6, -1, -1, -1 };
  return &_EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError;
}

@end

void EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_initWithJavaNetInetSocketAddress_withNSString_withLong_(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError *self, JavaNetInetSocketAddress *initiator, NSString *name, jlong requestID) {
  EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_initWithJavaNetInetSocketAddress_withEduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType_withNSString_withInt_(self, initiator, JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType, ACTIVE_REPLICA_ERROR), name, 0);
  self->requestID_ = requestID;
  [self makeResponse];
  JreStrongAssign(&self->code_, JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes, ACTIVE_REPLICA_EXCEPTION));
}

EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError *new_EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_initWithJavaNetInetSocketAddress_withNSString_withLong_(JavaNetInetSocketAddress *initiator, NSString *name, jlong requestID) {
  J2OBJC_NEW_IMPL(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError, initWithJavaNetInetSocketAddress_withNSString_withLong_, initiator, name, requestID)
}

EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError *create_EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_initWithJavaNetInetSocketAddress_withNSString_withLong_(JavaNetInetSocketAddress *initiator, NSString *name, jlong requestID) {
  J2OBJC_CREATE_IMPL(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError, initWithJavaNetInetSocketAddress_withNSString_withLong_, initiator, name, requestID)
}

void EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_initWithNSString_withLong_withEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError *self, NSString *name, jlong requestID, EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket *crp) {
  EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_initWithNSString_withEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_(self, name, crp);
  JreStrongAssign(&self->type_, JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType, ACTIVE_REPLICA_ERROR));
  self->requestID_ = requestID;
  [self makeResponse];
  JreStrongAssign(&self->code_, JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes, NONEXISTENT_NAME_ERROR));
}

EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError *new_EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_initWithNSString_withLong_withEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_(NSString *name, jlong requestID, EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket *crp) {
  J2OBJC_NEW_IMPL(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError, initWithNSString_withLong_withEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_, name, requestID, crp)
}

EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError *create_EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_initWithNSString_withLong_withEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_(NSString *name, jlong requestID, EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket *crp) {
  J2OBJC_CREATE_IMPL(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError, initWithNSString_withLong_withEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_, name, requestID, crp)
}

void EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_initWithOrgJsonJSONObject_(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError *self, OrgJsonJSONObject *json) {
  EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_initWithOrgJsonJSONObject_(self, json);
  [self makeResponse];
  self->requestID_ = [((OrgJsonJSONObject *) nil_chk(json)) getLongWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys, REQUEST_ID))) description]];
  JreStrongAssign(&self->code_, EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes_valueOfWithNSString_([json getStringWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys, ERROR_CODE))) description]]));
}

EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError *new_EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_initWithOrgJsonJSONObject_(OrgJsonJSONObject *json) {
  J2OBJC_NEW_IMPL(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError, initWithOrgJsonJSONObject_, json)
}

EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError *create_EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_initWithOrgJsonJSONObject_(OrgJsonJSONObject *json) {
  J2OBJC_CREATE_IMPL(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError, initWithOrgJsonJSONObject_, json)
}

void EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError *self, OrgJsonJSONObject *json, id<EduUmassCsNioInterfacesStringifiable> unstringer) {
  EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_(self, json, unstringer);
  [self makeResponse];
  self->requestID_ = [((OrgJsonJSONObject *) nil_chk(json)) getLongWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys, REQUEST_ID))) description]];
  JreStrongAssign(&self->code_, EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes_valueOfWithNSString_([json getStringWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys, ERROR_CODE))) description]]));
}

EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError *new_EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_(OrgJsonJSONObject *json, id<EduUmassCsNioInterfacesStringifiable> unstringer) {
  J2OBJC_NEW_IMPL(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError, initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_, json, unstringer)
}

EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError *create_EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_(OrgJsonJSONObject *json, id<EduUmassCsNioInterfacesStringifiable> unstringer) {
  J2OBJC_CREATE_IMPL(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError, initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_, json, unstringer)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError)

J2OBJC_INITIALIZED_DEFN(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys)

EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys *EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_values_[2];

@implementation EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys

+ (IOSObjectArray *)values {
  return EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_values();
}

+ (EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys *)valueOfWithNSString:(NSString *)name {
  return EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_valueOfWithNSString_(name);
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "[LEduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(values);
  methods[1].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "REQUEST_ID", "LEduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys;", .constantValue.asLong = 0, 0x4019, -1, 2, -1, -1 },
    { "ERROR_CODE", "LEduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys;", .constantValue.asLong = 0, 0x4019, -1, 3, -1, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "LNSString;", &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys, REQUEST_ID), &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys, ERROR_CODE), "LEduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError;", "Ljava/lang/Enum<Ledu/umass/cs/reconfiguration/reconfigurationpackets/ActiveReplicaError$Keys;>;" };
  static const J2ObjcClassInfo _EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys = { "Keys", "edu.umass.cs.reconfiguration.reconfigurationpackets", ptrTable, methods, fields, 7, 0x401a, 2, 2, 4, -1, -1, 5, -1 };
  return &_EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys;
}

+ (void)initialize {
  if (self == [EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 2 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    id names[] = {
      @"REQUEST_ID", @"ERROR_CODE",
    };
    for (jint i = 0; i < 2; i++) {
      (EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_values_[i] = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
      EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_initWithNSString_withInt_(e, names[i], i);
    }
    J2OBJC_SET_INITIALIZED(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys)
  }
}

@end

void EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_initWithNSString_withInt_(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

IOSObjectArray *EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_values() {
  EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_initialize();
  return [IOSObjectArray arrayWithObjects:EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_values_ count:2 type:EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_class_()];
}

EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys *EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_valueOfWithNSString_(NSString *name) {
  EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_initialize();
  for (int i = 0; i < 2; i++) {
    EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys *e = EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys *EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_fromOrdinal(NSUInteger ordinal) {
  EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_initialize();
  if (ordinal >= 2) {
    return nil;
  }
  return EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsReconfigurationReconfigurationpacketsActiveReplicaError_Keys)
