//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../gig_ios/src/edu/umass/cs/reconfiguration/reconfigurationpackets/ClientReconfigurationPacket.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "edu/umass/cs/nio/MessageNIOTransport.h"
#include "edu/umass/cs/nio/interfaces/IntegerPacketType.h"
#include "edu/umass/cs/nio/interfaces/Stringifiable.h"
#include "edu/umass/cs/nio/nioutils/StringifiableDefault.h"
#include "edu/umass/cs/reconfiguration/reconfigurationpackets/BasicReconfigurationPacket.h"
#include "edu/umass/cs/reconfiguration/reconfigurationpackets/ClientReconfigurationPacket.h"
#include "edu/umass/cs/reconfiguration/reconfigurationpackets/ReconfigurationPacket.h"
#include "edu/umass/cs/reconfiguration/reconfigurationpackets/RequestActiveReplicas.h"
#include "edu/umass/cs/utils/Util.h"
#include "java/io/Serializable.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/System.h"
#include "java/net/InetAddress.h"
#include "java/net/InetSocketAddress.h"
#include "java/util/HashSet.h"
#include "java/util/Set.h"
#include "org/json/JSONArray.h"
#include "org/json/JSONObject.h"

#pragma clang diagnostic ignored "-Wincomplete-implementation"

@interface EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket () {
 @public
  jboolean failed_;
  id<JavaUtilSet> hashRCs_;
  NSString *responseMessage_;
  jboolean recursiveRedirect_;
  JavaNetInetSocketAddress *creator_;
  JavaNetInetSocketAddress *forwarder_;
  JavaNetInetSocketAddress *myReceiver_;
  JavaNetInetSocketAddress *forwardee_;
  jboolean isRequest_;
  jlong createTime_;
  EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes *responseCode_;
}

@end

J2OBJC_FIELD_SETTER(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket, hashRCs_, id<JavaUtilSet>)
J2OBJC_FIELD_SETTER(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket, responseMessage_, NSString *)
J2OBJC_FIELD_SETTER(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket, creator_, JavaNetInetSocketAddress *)
J2OBJC_FIELD_SETTER(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket, forwarder_, JavaNetInetSocketAddress *)
J2OBJC_FIELD_SETTER(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket, myReceiver_, JavaNetInetSocketAddress *)
J2OBJC_FIELD_SETTER(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket, forwardee_, JavaNetInetSocketAddress *)
J2OBJC_FIELD_SETTER(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket, responseCode_, EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes *)

__attribute__((unused)) static void EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys_initWithNSString_withInt_(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static void EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes_initWithNSString_withInt_(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes *self, NSString *__name, jint __ordinal);

J2OBJC_INITIALIZED_DEFN(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket)

id<EduUmassCsNioInterfacesStringifiable> EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_unstringer;

@implementation EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket

- (instancetype)initWithJavaNetInetSocketAddress:(JavaNetInetSocketAddress *)initiator
withEduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType:(EduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType *)type
                                    withNSString:(NSString *)name
                                         withInt:(jint)epochNumber {
  EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_initWithJavaNetInetSocketAddress_withEduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType_withNSString_withInt_(self, initiator, type, name, epochNumber);
  return self;
}

- (instancetype)initWithJavaNetInetSocketAddress:(JavaNetInetSocketAddress *)initiator
withEduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType:(EduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType *)type
                                    withNSString:(NSString *)name
                                         withInt:(jint)epochNumber
                    withJavaNetInetSocketAddress:(JavaNetInetSocketAddress *)myReceiver {
  EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_initWithJavaNetInetSocketAddress_withEduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType_withNSString_withInt_withJavaNetInetSocketAddress_(self, initiator, type, name, epochNumber, myReceiver);
  return self;
}

- (instancetype)initWithNSString:(NSString *)name
withEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket:(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket *)crp {
  EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_initWithNSString_withEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_(self, name, crp);
  return self;
}

- (instancetype)initWithOrgJsonJSONObject:(OrgJsonJSONObject *)json
 withEduUmassCsNioInterfacesStringifiable:(id<EduUmassCsNioInterfacesStringifiable>)unstringer {
  EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_(self, json, unstringer);
  return self;
}

- (instancetype)initWithOrgJsonJSONObject:(OrgJsonJSONObject *)json {
  EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_initWithOrgJsonJSONObject_(self, json);
  return self;
}

- (OrgJsonJSONObject *)toJSONObjectImpl {
  OrgJsonJSONObject *json = [super toJSONObjectImpl];
  if (self->hashRCs_ != nil) [((OrgJsonJSONObject *) nil_chk(json)) putWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, RECONFIGURATORS))) description] withId:create_OrgJsonJSONArray_initWithJavaUtilCollection_(self->hashRCs_)];
  if (failed_) [((OrgJsonJSONObject *) nil_chk(json)) putWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, FAILED))) description] withBoolean:self->failed_];
  if (self->recursiveRedirect_) [((OrgJsonJSONObject *) nil_chk(json)) putWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, RECURSIVE_REDIRECT))) description] withBoolean:self->recursiveRedirect_];
  [((OrgJsonJSONObject *) nil_chk(json)) putWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, RESPONSE_MESSAGE))) description] withId:self->responseMessage_];
  if (self->forwarder_ != nil) [json putWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, FORWARDER))) description] withId:[((JavaNetInetSocketAddress *) nil_chk(self->forwarder_)) description]];
  if (self->forwardee_ != nil) [json putWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, FORWARDEE))) description] withId:[((JavaNetInetSocketAddress *) nil_chk(self->forwardee_)) description]];
  if (self->myReceiver_ != nil) [json putWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, MY_RECEIVER))) description] withId:[((JavaNetInetSocketAddress *) nil_chk(self->myReceiver_)) description]];
  if (self->creator_ != nil) [json putWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, CREATOR))) description] withId:[((JavaNetInetSocketAddress *) nil_chk(self->creator_)) description]];
  [json putWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, IS_QUERY))) description] withBoolean:self->isRequest_];
  [json putWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, CREATE_TIME))) description] withLong:self->createTime_];
  if (self->responseCode_ != nil) [json putWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, RESPONSE_CODE))) description] withId:self->responseCode_];
  return json;
}

- (id<EduUmassCsNioInterfacesIntegerPacketType>)getRequestType {
  return self->type_;
}

- (EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket *)setFailedWithEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes:(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes *)code {
  self->failed_ = true;
  self->isRequest_ = false;
  if (code != nil) JreStrongAssign(&self->responseCode_, code);
  return self;
}

- (EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket *)setFailed {
  return [self setFailedWithEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes:nil];
}

- (jboolean)isFailed {
  return self->failed_;
}

- (EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket *)setResponseMessageWithNSString:(NSString *)msg {
  JreStrongAssign(&self->responseMessage_, msg);
  self->isRequest_ = false;
  return self;
}

- (NSString *)getResponseMessage {
  return self->responseMessage_;
}

- (EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes *)getResponseCode {
  return self->responseCode_;
}

- (EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket *)setHashRCsWithJavaUtilSet:(id<JavaUtilSet>)RCs {
  JreStrongAssign(&self->hashRCs_, RCs);
  return self;
}

- (id<JavaUtilSet>)getHashRCs {
  return self->hashRCs_;
}

- (void)setRecursiveRedirectWithBoolean:(jboolean)b {
  self->recursiveRedirect_ = b;
}

- (jboolean)isRecursiveRedirectEnabled {
  return self->recursiveRedirect_;
}

- (jboolean)isRequest {
  return self->isRequest_;
}

- (EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket *)makeResponse {
  self->isRequest_ = false;
  return self;
}

- (JavaNetInetSocketAddress *)getForwader {
  return self->forwarder_;
}

- (JavaNetInetSocketAddress *)getForwardee {
  return self->forwardee_;
}

- (JavaNetInetSocketAddress *)getMyReceiver {
  return self->myReceiver_;
}

- (JavaNetInetSocketAddress *)getCreator {
  return self->creator_;
}

- (EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket *)setForwaderWithJavaNetInetSocketAddress:(JavaNetInetSocketAddress *)isa_ {
  JreStrongAssign(&self->forwarder_, isa_);
  return self;
}

- (EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket *)setForwardeeWithJavaNetInetSocketAddress:(JavaNetInetSocketAddress *)isa_ {
  JreStrongAssign(&self->forwardee_, isa_);
  return self;
}

- (jboolean)isForwardable {
  return [self isRecursiveRedirectEnabled] && [self getForwader] == nil;
}

- (jboolean)isForwarded {
  return self->forwarder_ != nil;
}

- (jboolean)isRedirectedResponse {
  return self->forwarder_ != nil && ![self isRequest];
}

- (jlong)getCreateTime {
  return self->createTime_;
}

- (NSString *)getSummary {
  return JreStrcat("$C$C@C@$", [super getSummary], ':', ([self isRequest] ? @"Q" : @"R"), ':', [self getCreator], ':', ([self getForwader] != nil ? [self getForwader] : (id) @""), ([self isFailed] ? @":FAILED" : @""));
}

- (void)dealloc {
  RELEASE_(hashRCs_);
  RELEASE_(responseMessage_);
  RELEASE_(creator_);
  RELEASE_(forwarder_);
  RELEASE_(myReceiver_);
  RELEASE_(forwardee_);
  RELEASE_(responseCode_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 3, 4, 5, -1, -1 },
    { NULL, NULL, 0x1, -1, 6, 4, -1, -1, -1 },
    { NULL, "LOrgJsonJSONObject;", 0x1, -1, -1, 4, -1, -1, -1 },
    { NULL, "LEduUmassCsNioInterfacesIntegerPacketType;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket;", 0x1, 7, 8, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket;", 0x1, 9, 10, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket;", 0x1, 11, 12, -1, 13, -1, -1 },
    { NULL, "LJavaUtilSet;", 0x1, -1, -1, -1, 14, -1, -1 },
    { NULL, "V", 0x1, 15, 16, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaNetInetSocketAddress;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaNetInetSocketAddress;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaNetInetSocketAddress;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaNetInetSocketAddress;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket;", 0x1, 17, 18, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket;", 0x1, 19, 18, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "J", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithJavaNetInetSocketAddress:withEduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType:withNSString:withInt:);
  methods[1].selector = @selector(initWithJavaNetInetSocketAddress:withEduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType:withNSString:withInt:withJavaNetInetSocketAddress:);
  methods[2].selector = @selector(initWithNSString:withEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket:);
  methods[3].selector = @selector(initWithOrgJsonJSONObject:withEduUmassCsNioInterfacesStringifiable:);
  methods[4].selector = @selector(initWithOrgJsonJSONObject:);
  methods[5].selector = @selector(toJSONObjectImpl);
  methods[6].selector = @selector(getRequestType);
  methods[7].selector = @selector(setFailedWithEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes:);
  methods[8].selector = @selector(setFailed);
  methods[9].selector = @selector(isFailed);
  methods[10].selector = @selector(setResponseMessageWithNSString:);
  methods[11].selector = @selector(getResponseMessage);
  methods[12].selector = @selector(getResponseCode);
  methods[13].selector = @selector(setHashRCsWithJavaUtilSet:);
  methods[14].selector = @selector(getHashRCs);
  methods[15].selector = @selector(setRecursiveRedirectWithBoolean:);
  methods[16].selector = @selector(isRecursiveRedirectEnabled);
  methods[17].selector = @selector(isRequest);
  methods[18].selector = @selector(makeResponse);
  methods[19].selector = @selector(getForwader);
  methods[20].selector = @selector(getForwardee);
  methods[21].selector = @selector(getMyReceiver);
  methods[22].selector = @selector(getCreator);
  methods[23].selector = @selector(setForwaderWithJavaNetInetSocketAddress:);
  methods[24].selector = @selector(setForwardeeWithJavaNetInetSocketAddress:);
  methods[25].selector = @selector(isForwardable);
  methods[26].selector = @selector(isForwarded);
  methods[27].selector = @selector(isRedirectedResponse);
  methods[28].selector = @selector(getCreateTime);
  methods[29].selector = @selector(getSummary);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "unstringer", "LEduUmassCsNioInterfacesStringifiable;", .constantValue.asLong = 0, 0x19, -1, 20, 21, -1 },
    { "failed_", "Z", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "hashRCs_", "LJavaUtilSet;", .constantValue.asLong = 0, 0x2, -1, -1, 22, -1 },
    { "responseMessage_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "recursiveRedirect_", "Z", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "creator_", "LJavaNetInetSocketAddress;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "forwarder_", "LJavaNetInetSocketAddress;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "myReceiver_", "LJavaNetInetSocketAddress;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "forwardee_", "LJavaNetInetSocketAddress;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "isRequest_", "Z", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "createTime_", "J", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "responseCode_", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LJavaNetInetSocketAddress;LEduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType;LNSString;I", "LJavaNetInetSocketAddress;LEduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType;LNSString;ILJavaNetInetSocketAddress;", "LNSString;LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket;", "LOrgJsonJSONObject;LEduUmassCsNioInterfacesStringifiable;", "LOrgJsonJSONException;", "(Lorg/json/JSONObject;Ledu/umass/cs/nio/interfaces/Stringifiable<*>;)V", "LOrgJsonJSONObject;", "setFailed", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes;", "setResponseMessage", "LNSString;", "setHashRCs", "LJavaUtilSet;", "(Ljava/util/Set<Ljava/net/InetSocketAddress;>;)Ledu/umass/cs/reconfiguration/reconfigurationpackets/ClientReconfigurationPacket;", "()Ljava/util/Set<Ljava/net/InetSocketAddress;>;", "setRecursiveRedirect", "Z", "setForwader", "LJavaNetInetSocketAddress;", "setForwardee", &EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_unstringer, "Ledu/umass/cs/nio/interfaces/Stringifiable<Ljava/net/InetSocketAddress;>;", "Ljava/util/Set<Ljava/net/InetSocketAddress;>;", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys;LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes;", "Ledu/umass/cs/reconfiguration/reconfigurationpackets/BasicReconfigurationPacket<Ljava/net/InetSocketAddress;>;Ledu/umass/cs/reconfiguration/interfaces/ReconfiguratorRequest;" };
  static const J2ObjcClassInfo _EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket = { "ClientReconfigurationPacket", "edu.umass.cs.reconfiguration.reconfigurationpackets", ptrTable, methods, fields, 7, 0x401, 30, 12, -1, 23, -1, 24, -1 };
  return &_EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket;
}

+ (void)initialize {
  if (self == [EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket class]) {
    JreStrongAssignAndConsume(&EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_unstringer, new_EduUmassCsNioNioutilsStringifiableDefault_initWithId_(create_JavaNetInetSocketAddress_initWithJavaNetInetAddress_withInt_(JavaNetInetAddress_getLoopbackAddress(), 0)));
    J2OBJC_SET_INITIALIZED(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket)
  }
}

@end

void EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_initWithJavaNetInetSocketAddress_withEduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType_withNSString_withInt_(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket *self, JavaNetInetSocketAddress *initiator, EduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType *type, NSString *name, jint epochNumber) {
  EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_initWithJavaNetInetSocketAddress_withEduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType_withNSString_withInt_withJavaNetInetSocketAddress_(self, initiator, type, name, epochNumber, nil);
}

void EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_initWithJavaNetInetSocketAddress_withEduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType_withNSString_withInt_withJavaNetInetSocketAddress_(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket *self, JavaNetInetSocketAddress *initiator, EduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType *type, NSString *name, jint epochNumber, JavaNetInetSocketAddress *myReceiver) {
  EduUmassCsReconfigurationReconfigurationpacketsBasicReconfigurationPacket_initWithId_withEduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType_withNSString_withInt_(self, initiator, type, name, epochNumber);
  self->failed_ = false;
  JreStrongAssign(&self->hashRCs_, nil);
  JreStrongAssign(&self->responseMessage_, nil);
  self->recursiveRedirect_ = true;
  JreStrongAssign(&self->creator_, nil);
  JreStrongAssign(&self->forwarder_, nil);
  JreStrongAssign(&self->myReceiver_, nil);
  JreStrongAssign(&self->forwardee_, nil);
  self->isRequest_ = true;
  self->createTime_ = JavaLangSystem_currentTimeMillis();
  JreStrongAssign(&self->responseCode_, nil);
  JreStrongAssign(&self->creator_, initiator);
  JreStrongAssign(&self->myReceiver_, myReceiver);
}

void EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_initWithNSString_withEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket *self, NSString *name, EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket *crp) {
  EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_initWithJavaNetInetSocketAddress_withEduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType_withNSString_withInt_(self, [((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket *) nil_chk(crp)) getInitiator], [crp getType], name, crp->epochNumber_);
  JreStrongAssign(&self->creator_, [crp getCreator]);
  JreStrongAssign(&self->forwarder_, [crp getForwader]);
  JreStrongAssign(&self->myReceiver_, crp->myReceiver_);
}

void EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket *self, OrgJsonJSONObject *json, id<EduUmassCsNioInterfacesStringifiable> unstringer) {
  EduUmassCsReconfigurationReconfigurationpacketsBasicReconfigurationPacket_initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_(self, json, EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_unstringer);
  self->failed_ = false;
  JreStrongAssign(&self->hashRCs_, nil);
  JreStrongAssign(&self->responseMessage_, nil);
  self->recursiveRedirect_ = true;
  JreStrongAssign(&self->creator_, nil);
  JreStrongAssign(&self->forwarder_, nil);
  JreStrongAssign(&self->myReceiver_, nil);
  JreStrongAssign(&self->forwardee_, nil);
  self->isRequest_ = true;
  self->createTime_ = JavaLangSystem_currentTimeMillis();
  JreStrongAssign(&self->responseCode_, nil);
  [self setSenderWithId:EduUmassCsNioMessageNIOTransport_getSenderAddressWithOrgJsonJSONObject_(json)];
  JreStrongAssign(&self->myReceiver_, [((OrgJsonJSONObject *) nil_chk(json)) hasWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, MY_RECEIVER))) description]] ? EduUmassCsUtilsUtil_getInetSocketAddressFromStringWithNSString_([json getStringWithNSString:[JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, MY_RECEIVER) description]]) : (EduUmassCsNioMessageNIOTransport_getReceiverAddressWithOrgJsonJSONObject_(json)));
  self->failed_ = [json optBooleanWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, FAILED))) description]];
  self->recursiveRedirect_ = [json optBooleanWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, RECURSIVE_REDIRECT))) description]];
  JreStrongAssign(&self->responseMessage_, [json hasWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, RESPONSE_MESSAGE))) description]] ? [json getStringWithNSString:[JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, RESPONSE_MESSAGE) description]] : nil);
  OrgJsonJSONArray *jsonArray = [json hasWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, RECONFIGURATORS))) description]] ? [json getJSONArrayWithNSString:[JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, RECONFIGURATORS) description]] : nil;
  if (jsonArray != nil) {
    JreStrongAssignAndConsume(&self->hashRCs_, new_JavaUtilHashSet_init());
    for (jint i = 0; jsonArray != nil && i < [jsonArray length]; i++) [((id<JavaUtilSet>) nil_chk(self->hashRCs_)) addWithId:[((id<EduUmassCsNioInterfacesStringifiable>) nil_chk(JreLoadStatic(EduUmassCsReconfigurationReconfigurationpacketsRequestActiveReplicas, unstringer))) valueOfWithNSString:[nil_chk([jsonArray getWithInt:i]) description]]];
  }
  JreStrongAssign(&self->forwarder_, [json hasWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, FORWARDER))) description]] ? EduUmassCsUtilsUtil_getInetSocketAddressFromStringWithNSString_([json getStringWithNSString:[JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, FORWARDER) description]]) : nil);
  JreStrongAssign(&self->forwardee_, [json hasWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, FORWARDEE))) description]] ? EduUmassCsUtilsUtil_getInetSocketAddressFromStringWithNSString_([json getStringWithNSString:[JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, FORWARDEE) description]]) : nil);
  JreStrongAssign(&self->creator_, [json hasWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, CREATOR))) description]] ? EduUmassCsUtilsUtil_getInetSocketAddressFromStringWithNSString_([json getStringWithNSString:[JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, CREATOR) description]]) : nil);
  if (self->creator_ == nil) JreStrongAssign(&self->creator_, [self getSender]);
  self->isRequest_ = [json getBooleanWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, IS_QUERY))) description]];
  self->createTime_ = [json hasWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, CREATE_TIME))) description]] ? [json getLongWithNSString:[JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, CREATE_TIME) description]] : JavaLangSystem_currentTimeMillis();
  JreStrongAssign(&self->responseCode_, [json hasWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, RESPONSE_CODE))) description]] ? EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes_valueOfWithNSString_([json getStringWithNSString:[JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, RESPONSE_CODE) description]]) : nil);
}

void EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_initWithOrgJsonJSONObject_(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket *self, OrgJsonJSONObject *json) {
  EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_(self, json, EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_unstringer);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket)

J2OBJC_INITIALIZED_DEFN(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys)

EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys_values_[12];

@implementation EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys

+ (IOSObjectArray *)values {
  return EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys_values();
}

+ (EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *)valueOfWithNSString:(NSString *)name {
  return EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys_valueOfWithNSString_(name);
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "[LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(values);
  methods[1].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "INITIAL_STATE", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys;", .constantValue.asLong = 0, 0x4019, -1, 2, -1, -1 },
    { "RECONFIGURATORS", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys;", .constantValue.asLong = 0, 0x4019, -1, 3, -1, -1 },
    { "RESPONSE_MESSAGE", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys;", .constantValue.asLong = 0, 0x4019, -1, 4, -1, -1 },
    { "FAILED", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys;", .constantValue.asLong = 0, 0x4019, -1, 5, -1, -1 },
    { "RECURSIVE_REDIRECT", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys;", .constantValue.asLong = 0, 0x4019, -1, 6, -1, -1 },
    { "CREATOR", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys;", .constantValue.asLong = 0, 0x4019, -1, 7, -1, -1 },
    { "FORWARDER", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys;", .constantValue.asLong = 0, 0x4019, -1, 8, -1, -1 },
    { "FORWARDEE", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys;", .constantValue.asLong = 0, 0x4019, -1, 9, -1, -1 },
    { "MY_RECEIVER", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys;", .constantValue.asLong = 0, 0x4019, -1, 10, -1, -1 },
    { "IS_QUERY", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys;", .constantValue.asLong = 0, 0x4019, -1, 11, -1, -1 },
    { "CREATE_TIME", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys;", .constantValue.asLong = 0, 0x4019, -1, 12, -1, -1 },
    { "RESPONSE_CODE", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys;", .constantValue.asLong = 0, 0x4019, -1, 13, -1, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "LNSString;", &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, INITIAL_STATE), &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, RECONFIGURATORS), &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, RESPONSE_MESSAGE), &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, FAILED), &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, RECURSIVE_REDIRECT), &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, CREATOR), &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, FORWARDER), &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, FORWARDEE), &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, MY_RECEIVER), &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, IS_QUERY), &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, CREATE_TIME), &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys, RESPONSE_CODE), "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket;", "Ljava/lang/Enum<Ledu/umass/cs/reconfiguration/reconfigurationpackets/ClientReconfigurationPacket$Keys;>;" };
  static const J2ObjcClassInfo _EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys = { "Keys", "edu.umass.cs.reconfiguration.reconfigurationpackets", ptrTable, methods, fields, 7, 0x4019, 2, 12, 14, -1, -1, 15, -1 };
  return &_EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys;
}

+ (void)initialize {
  if (self == [EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 12 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    id names[] = {
      @"INITIAL_STATE", @"RECONFIGURATORS", @"RESPONSE_MESSAGE", @"FAILED", @"RECURSIVE_REDIRECT", @"CREATOR", @"FORWARDER", @"FORWARDEE", @"MY_RECEIVER", @"IS_QUERY", @"CREATE_TIME", @"RESPONSE_CODE",
    };
    for (jint i = 0; i < 12; i++) {
      (EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys_values_[i] = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
      EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys_initWithNSString_withInt_(e, names[i], i);
    }
    J2OBJC_SET_INITIALIZED(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys)
  }
}

@end

void EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys_initWithNSString_withInt_(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

IOSObjectArray *EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys_values() {
  EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys_initialize();
  return [IOSObjectArray arrayWithObjects:EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys_values_ count:12 type:EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys_class_()];
}

EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys_valueOfWithNSString_(NSString *name) {
  EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys_initialize();
  for (int i = 0; i < 12; i++) {
    EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *e = EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys *EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys_fromOrdinal(NSUInteger ordinal) {
  EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys_initialize();
  if (ordinal >= 12) {
    return nil;
  }
  return EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_Keys)

J2OBJC_INITIALIZED_DEFN(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes)

EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes *EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes_values_[7];

@implementation EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes

+ (IOSObjectArray *)values {
  return EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes_values();
}

+ (EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes *)valueOfWithNSString:(NSString *)name {
  return EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes_valueOfWithNSString_(name);
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "[LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(values);
  methods[1].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "DUPLICATE_ERROR", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes;", .constantValue.asLong = 0, 0x4019, -1, 2, -1, -1 },
    { "ACTIVE_REPLICA_EXCEPTION", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes;", .constantValue.asLong = 0, 0x4019, -1, 3, -1, -1 },
    { "NONEXISTENT_NAME_ERROR", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes;", .constantValue.asLong = 0, 0x4019, -1, 4, -1, -1 },
    { "MALFORMED_REQUEST", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes;", .constantValue.asLong = 0, 0x4019, -1, 5, -1, -1 },
    { "TIMEOUT_EXCEPTION", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes;", .constantValue.asLong = 0, 0x4019, -1, 6, -1, -1 },
    { "IO_EXCEPTION", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes;", .constantValue.asLong = 0, 0x4019, -1, 7, -1, -1 },
    { "GENERIC_EXCEPTION", "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes;", .constantValue.asLong = 0, 0x4019, -1, 8, -1, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "LNSString;", &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes, DUPLICATE_ERROR), &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes, ACTIVE_REPLICA_EXCEPTION), &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes, NONEXISTENT_NAME_ERROR), &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes, MALFORMED_REQUEST), &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes, TIMEOUT_EXCEPTION), &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes, IO_EXCEPTION), &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes, GENERIC_EXCEPTION), "LEduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket;", "Ljava/lang/Enum<Ledu/umass/cs/reconfiguration/reconfigurationpackets/ClientReconfigurationPacket$ResponseCodes;>;" };
  static const J2ObjcClassInfo _EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes = { "ResponseCodes", "edu.umass.cs.reconfiguration.reconfigurationpackets", ptrTable, methods, fields, 7, 0x4019, 2, 7, 9, -1, -1, 10, -1 };
  return &_EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes;
}

+ (void)initialize {
  if (self == [EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 7 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    id names[] = {
      @"DUPLICATE_ERROR", @"ACTIVE_REPLICA_EXCEPTION", @"NONEXISTENT_NAME_ERROR", @"MALFORMED_REQUEST", @"TIMEOUT_EXCEPTION", @"IO_EXCEPTION", @"GENERIC_EXCEPTION",
    };
    for (jint i = 0; i < 7; i++) {
      (EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes_values_[i] = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
      EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes_initWithNSString_withInt_(e, names[i], i);
    }
    J2OBJC_SET_INITIALIZED(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes)
  }
}

@end

void EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes_initWithNSString_withInt_(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

IOSObjectArray *EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes_values() {
  EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes_initialize();
  return [IOSObjectArray arrayWithObjects:EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes_values_ count:7 type:EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes_class_()];
}

EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes *EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes_valueOfWithNSString_(NSString *name) {
  EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes_initialize();
  for (int i = 0; i < 7; i++) {
    EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes *e = EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes *EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes_fromOrdinal(NSUInteger ordinal) {
  EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes_initialize();
  if (ordinal >= 7) {
    return nil;
  }
  return EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsReconfigurationReconfigurationpacketsClientReconfigurationPacket_ResponseCodes)
