//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../gig_ios/src/edu/umass/cs/reconfiguration/reconfigurationpackets/ReplicableClientRequest.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "edu/umass/cs/gigapaxos/interfaces/AppRequestParser.h"
#include "edu/umass/cs/gigapaxos/interfaces/AppRequestParserBytes.h"
#include "edu/umass/cs/gigapaxos/interfaces/ClientRequest.h"
#include "edu/umass/cs/gigapaxos/interfaces/Request.h"
#include "edu/umass/cs/nio/JSONPacket.h"
#include "edu/umass/cs/nio/interfaces/Byteable.h"
#include "edu/umass/cs/nio/interfaces/IntegerPacketType.h"
#include "edu/umass/cs/nio/interfaces/Stringifiable.h"
#include "edu/umass/cs/nio/nioutils/NIOHeader.h"
#include "edu/umass/cs/reconfiguration/interfaces/ReconfigurableRequest.h"
#include "edu/umass/cs/reconfiguration/interfaces/ReplicableRequest.h"
#include "edu/umass/cs/reconfiguration/reconfigurationpackets/ReconfigurationPacket.h"
#include "edu/umass/cs/reconfiguration/reconfigurationpackets/ReplicableClientRequest.h"
#include "edu/umass/cs/reconfiguration/reconfigurationutils/RequestParseException.h"
#include "edu/umass/cs/utils/Summarizable.h"
#include "java/io/UnsupportedEncodingException.h"
#include "java/lang/Enum.h"
#include "java/lang/Exception.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/Integer.h"
#include "java/lang/Long.h"
#include "java/lang/Math.h"
#include "java/net/InetSocketAddress.h"
#include "java/nio/ByteBuffer.h"
#include "java/util/Arrays.h"
#include "org/json/JSONObject.h"

@interface EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest () {
 @public
  JavaNetInetSocketAddress *clientAddress_;
}

- (id<EduUmassCsGigapaxosInterfacesRequest>)parseWithByteArray:(IOSByteArray *)buf
                            withEduUmassCsNioNioutilsNIOHeader:(EduUmassCsNioNioutilsNIOHeader *)header
                                                        withId:(id)parser;

- (id<EduUmassCsGigapaxosInterfacesRequest>)parseWithByteArray:(IOSByteArray *)buf
                            withEduUmassCsNioNioutilsNIOHeader:(EduUmassCsNioNioutilsNIOHeader *)header
        withEduUmassCsGigapaxosInterfacesAppRequestParserBytes:(id<EduUmassCsGigapaxosInterfacesAppRequestParserBytes>)parser;

- (id<EduUmassCsGigapaxosInterfacesRequest>)parseWithByteArray:(IOSByteArray *)buf
                            withEduUmassCsNioNioutilsNIOHeader:(EduUmassCsNioNioutilsNIOHeader *)header
             withEduUmassCsGigapaxosInterfacesAppRequestParser:(id<EduUmassCsGigapaxosInterfacesAppRequestParser>)parser;

@end

J2OBJC_FIELD_SETTER(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest, clientAddress_, JavaNetInetSocketAddress *)

inline jint EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_get_REQUEST_BYTES_OFFSET();
#define EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_REQUEST_BYTES_OFFSET 13
J2OBJC_STATIC_FIELD_CONSTANT(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest, REQUEST_BYTES_OFFSET, jint)

__attribute__((unused)) static id<EduUmassCsGigapaxosInterfacesRequest> EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_parseWithByteArray_withEduUmassCsNioNioutilsNIOHeader_withId_(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *self, IOSByteArray *buf, EduUmassCsNioNioutilsNIOHeader *header, id parser);

__attribute__((unused)) static id<EduUmassCsGigapaxosInterfacesRequest> EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_parseWithByteArray_withEduUmassCsNioNioutilsNIOHeader_withEduUmassCsGigapaxosInterfacesAppRequestParserBytes_(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *self, IOSByteArray *buf, EduUmassCsNioNioutilsNIOHeader *header, id<EduUmassCsGigapaxosInterfacesAppRequestParserBytes> parser);

__attribute__((unused)) static id<EduUmassCsGigapaxosInterfacesRequest> EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_parseWithByteArray_withEduUmassCsNioNioutilsNIOHeader_withEduUmassCsGigapaxosInterfacesAppRequestParser_(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *self, IOSByteArray *buf, EduUmassCsNioNioutilsNIOHeader *header, id<EduUmassCsGigapaxosInterfacesAppRequestParser> parser);

typedef NS_ENUM(NSUInteger, EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_Enum) {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_Enum_QID = 0,
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_Enum_QV = 1,
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_Enum_COORD = 2,
};

@interface EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys : JavaLangEnum < NSCopying >

+ (IOSObjectArray *)values;

+ (EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys *)valueOfWithNSString:(NSString *)name;

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys *EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_values_[];

inline EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys *EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_get_QID();
J2OBJC_ENUM_CONSTANT(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys, QID)

inline EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys *EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_get_QV();
J2OBJC_ENUM_CONSTANT(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys, QV)

inline EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys *EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_get_COORD();
J2OBJC_ENUM_CONSTANT(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys, COORD)

__attribute__((unused)) static void EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_initWithNSString_withInt_(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static IOSObjectArray *EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_values();

__attribute__((unused)) static EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys *EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys *EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys)

@interface EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_1 : NSObject < EduUmassCsNioInterfacesIntegerPacketType > {
 @public
  JavaNioByteBuffer *val$bbuf_;
}

- (instancetype)initWithJavaNioByteBuffer:(JavaNioByteBuffer *)capture$0;

- (jint)getInt;

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_1)

__attribute__((unused)) static void EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_1_initWithJavaNioByteBuffer_(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_1 *self, JavaNioByteBuffer *capture$0);

__attribute__((unused)) static EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_1 *new_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_1_initWithJavaNioByteBuffer_(JavaNioByteBuffer *capture$0) NS_RETURNS_RETAINED;

__attribute__((unused)) static EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_1 *create_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_1_initWithJavaNioByteBuffer_(JavaNioByteBuffer *capture$0);

@implementation EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest

+ (EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *)wrapWithEduUmassCsGigapaxosInterfacesRequest:(id<EduUmassCsGigapaxosInterfacesRequest>)request {
  return EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_wrapWithEduUmassCsGigapaxosInterfacesRequest_(request);
}

+ (EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *)wrapWithEduUmassCsGigapaxosInterfacesRequest:(id<EduUmassCsGigapaxosInterfacesRequest>)request
                                                                                                                withLong:(jlong)requestID {
  return EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_wrapWithEduUmassCsGigapaxosInterfacesRequest_withLong_(request, requestID);
}

+ (EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *)wrapWithEduUmassCsGigapaxosInterfacesRequest:(id<EduUmassCsGigapaxosInterfacesRequest>)request
                                                                                                             withBoolean:(jboolean)coord {
  return EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_wrapWithEduUmassCsGigapaxosInterfacesRequest_withBoolean_(request, coord);
}

- (instancetype)initWithEduUmassCsGigapaxosInterfacesRequest:(id<EduUmassCsGigapaxosInterfacesRequest>)request {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_(self, request);
  return self;
}

- (instancetype)initWithEduUmassCsGigapaxosInterfacesRequest:(id<EduUmassCsGigapaxosInterfacesRequest>)request
                                                 withBoolean:(jboolean)coord {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_withBoolean_(self, request, coord);
  return self;
}

- (instancetype)initWithEduUmassCsGigapaxosInterfacesRequest:(id<EduUmassCsGigapaxosInterfacesRequest>)request
                                                    withLong:(jlong)requestID {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_withLong_(self, request, requestID);
  return self;
}

- (instancetype)initWithEduUmassCsGigapaxosInterfacesRequest:(id<EduUmassCsGigapaxosInterfacesRequest>)request
                                                    withLong:(jlong)requestID
                                                 withBoolean:(jboolean)coord {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_withLong_withBoolean_(self, request, requestID, coord);
  return self;
}

- (instancetype)initWithJavaNioByteBuffer:(JavaNioByteBuffer *)bbuf
       withEduUmassCsNioNioutilsNIOHeader:(EduUmassCsNioNioutilsNIOHeader *)header
                                   withId:(id)parser {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithJavaNioByteBuffer_withEduUmassCsNioNioutilsNIOHeader_withId_(self, bbuf, header, parser);
  return self;
}

- (id<EduUmassCsGigapaxosInterfacesRequest>)parseWithByteArray:(IOSByteArray *)buf
                            withEduUmassCsNioNioutilsNIOHeader:(EduUmassCsNioNioutilsNIOHeader *)header
                                                        withId:(id)parser {
  return EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_parseWithByteArray_withEduUmassCsNioNioutilsNIOHeader_withId_(self, buf, header, parser);
}

- (id<EduUmassCsGigapaxosInterfacesRequest>)parseWithByteArray:(IOSByteArray *)buf
                            withEduUmassCsNioNioutilsNIOHeader:(EduUmassCsNioNioutilsNIOHeader *)header
        withEduUmassCsGigapaxosInterfacesAppRequestParserBytes:(id<EduUmassCsGigapaxosInterfacesAppRequestParserBytes>)parser {
  return EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_parseWithByteArray_withEduUmassCsNioNioutilsNIOHeader_withEduUmassCsGigapaxosInterfacesAppRequestParserBytes_(self, buf, header, parser);
}

- (id<EduUmassCsGigapaxosInterfacesRequest>)parseWithByteArray:(IOSByteArray *)buf
                            withEduUmassCsNioNioutilsNIOHeader:(EduUmassCsNioNioutilsNIOHeader *)header
             withEduUmassCsGigapaxosInterfacesAppRequestParser:(id<EduUmassCsGigapaxosInterfacesAppRequestParser>)parser {
  return EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_parseWithByteArray_withEduUmassCsNioNioutilsNIOHeader_withEduUmassCsGigapaxosInterfacesAppRequestParser_(self, buf, header, parser);
}

- (instancetype)initWithByteArray:(IOSByteArray *)buf
withEduUmassCsNioNioutilsNIOHeader:(EduUmassCsNioNioutilsNIOHeader *)header
withEduUmassCsGigapaxosInterfacesAppRequestParserBytes:(id<EduUmassCsGigapaxosInterfacesAppRequestParserBytes>)parser {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithByteArray_withEduUmassCsNioNioutilsNIOHeader_withEduUmassCsGigapaxosInterfacesAppRequestParserBytes_(self, buf, header, parser);
  return self;
}

- (instancetype)initWithByteArray:(IOSByteArray *)buf
withEduUmassCsGigapaxosInterfacesAppRequestParser:(id<EduUmassCsGigapaxosInterfacesAppRequestParser>)parser {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithByteArray_withEduUmassCsGigapaxosInterfacesAppRequestParser_(self, buf, parser);
  return self;
}

- (instancetype)initWithOrgJsonJSONObject:(OrgJsonJSONObject *)json {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithOrgJsonJSONObject_(self, json);
  return self;
}

- (instancetype)initWithOrgJsonJSONObject:(OrgJsonJSONObject *)json
 withEduUmassCsNioInterfacesStringifiable:(id<EduUmassCsNioInterfacesStringifiable>)unstringer {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_(self, json, unstringer);
  return self;
}

- (id<EduUmassCsGigapaxosInterfacesRequest>)getRequestWithEduUmassCsGigapaxosInterfacesAppRequestParser:(id<EduUmassCsGigapaxosInterfacesAppRequestParser>)parser {
  return self->request_ != nil ? self->request_ : [((id<EduUmassCsGigapaxosInterfacesAppRequestParser>) nil_chk(parser)) getRequestWithNSString:[NSString java_stringWithBytes:self->requestBytes_ charsetName:CHARSET_]];
}

- (id<EduUmassCsGigapaxosInterfacesRequest>)getRequest {
  return self->request_;
}

- (id<EduUmassCsGigapaxosInterfacesRequest>)getRequestWithEduUmassCsGigapaxosInterfacesAppRequestParserBytes:(id<EduUmassCsGigapaxosInterfacesAppRequestParserBytes>)parser
                                                                          withEduUmassCsNioNioutilsNIOHeader:(EduUmassCsNioNioutilsNIOHeader *)header {
  return self->request_ != nil ? self->request_ : [((id<EduUmassCsGigapaxosInterfacesAppRequestParserBytes>) nil_chk(parser)) getRequestWithByteArray:self->requestBytes_ withEduUmassCsNioNioutilsNIOHeader:header];
}

- (id<EduUmassCsNioInterfacesIntegerPacketType>)getRequestType {
  return JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsReconfigurationPacket_PacketType, REPLICABLE_CLIENT_REQUEST);
}

- (NSString *)getServiceName {
  return [((id<EduUmassCsGigapaxosInterfacesRequest>) nil_chk(self->request_)) getServiceName];
}

- (jlong)getRequestID {
  return self->requestID_;
}

- (jint)getEpochNumber {
  return [EduUmassCsReconfigurationInterfacesReconfigurableRequest_class_() isInstance:request_] ? [((id<EduUmassCsReconfigurationInterfacesReconfigurableRequest>) nil_chk(((id<EduUmassCsReconfigurationInterfacesReconfigurableRequest>) cast_check(self->request_, EduUmassCsReconfigurationInterfacesReconfigurableRequest_class_())))) getEpochNumber] : 0;
}

- (jboolean)isStop {
  return [EduUmassCsReconfigurationInterfacesReconfigurableRequest_class_() isInstance:request_] ? [((id<EduUmassCsReconfigurationInterfacesReconfigurableRequest>) nil_chk(((id<EduUmassCsReconfigurationInterfacesReconfigurableRequest>) cast_check(self->request_, EduUmassCsReconfigurationInterfacesReconfigurableRequest_class_())))) isStop] : false;
}

- (id<EduUmassCsGigapaxosInterfacesClientRequest>)getResponse {
  return [EduUmassCsGigapaxosInterfacesClientRequest_class_() isInstance:request_] ? [((id<EduUmassCsGigapaxosInterfacesClientRequest>) nil_chk(((id<EduUmassCsGigapaxosInterfacesClientRequest>) cast_check(self->request_, EduUmassCsGigapaxosInterfacesClientRequest_class_())))) getResponse] : nil;
}

- (jboolean)needsCoordination {
  return self->needsCoordination_;
}

- (OrgJsonJSONObject *)toJSONObjectImpl {
  OrgJsonJSONObject *json = create_OrgJsonJSONObject_init();
  [json putWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys, QID))) description] withLong:self->requestID_];
  [json putWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys, COORD))) description] withBoolean:self->needsCoordination_];
  [json putWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys, QV))) description] withId:[((id<EduUmassCsGigapaxosInterfacesRequest>) nil_chk(self->request_)) description]];
  return json;
}

- (IOSByteArray *)toBytes {
  IOSByteArray *reqBytes;
  @try {
    reqBytes = [EduUmassCsNioInterfacesByteable_class_() isInstance:self->request_] ? [((id<EduUmassCsNioInterfacesByteable>) nil_chk(((id<EduUmassCsNioInterfacesByteable>) cast_check(self->request_, EduUmassCsNioInterfacesByteable_class_())))) toBytes] : [((NSString *) nil_chk([((id<EduUmassCsGigapaxosInterfacesRequest>) nil_chk(self->request_)) description])) java_getBytesWithCharsetName:CHARSET_];
  }
  @catch (JavaIoUnsupportedEncodingException *e) {
    [((JavaIoUnsupportedEncodingException *) nil_chk(e)) printStackTrace];
    return nil;
  }
  IOSByteArray *buf = [IOSByteArray arrayWithLength:JavaLangInteger_BYTES + JavaLangLong_BYTES + 1 + ((IOSByteArray *) nil_chk(reqBytes))->size_];
  return [((JavaNioByteBuffer *) nil_chk([((JavaNioByteBuffer *) nil_chk([((JavaNioByteBuffer *) nil_chk([((JavaNioByteBuffer *) nil_chk([((JavaNioByteBuffer *) nil_chk(JavaNioByteBuffer_wrapWithByteArray_(buf))) putIntWithInt:[((id<EduUmassCsNioInterfacesIntegerPacketType>) nil_chk([self getRequestType])) getInt]])) putLongWithLong:self->requestID_])) putWithByte:self->needsCoordination_ ? (jbyte) 1 : (jbyte) 0])) putWithByteArray:reqBytes])) array];
}

- (EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *)setClientAddressWithJavaNetInetSocketAddress:(JavaNetInetSocketAddress *)csa {
  JreStrongAssign(&self->clientAddress_, csa);
  return self;
}

- (JavaNetInetSocketAddress *)getClientAddress {
  return self->clientAddress_;
}

- (NSString *)getRequestAsString {
  @try {
    JreAssert(((self->request_ != nil)), (@"edu/umass/cs/reconfiguration/reconfigurationpackets/ReplicableClientRequest.java:275 condition failed: assert (this.request != null);"));
    return [EduUmassCsNioInterfacesByteable_class_() isInstance:self->request_] || self->requestBytes_ == nil ? [((id<EduUmassCsGigapaxosInterfacesRequest>) nil_chk(self->request_)) description] : [NSString java_stringWithBytes:self->requestBytes_ charsetName:CHARSET_];
  }
  @catch (JavaIoUnsupportedEncodingException *e) {
    [((JavaIoUnsupportedEncodingException *) nil_chk(e)) printStackTrace];
  }
  return [((id<EduUmassCsGigapaxosInterfacesRequest>) nil_chk(self->request_)) description];
}

- (NSString *)description {
  return [self getRequestAsString];
}

- (jboolean)isEqual:(id)o {
  if (!([EduUmassCsGigapaxosInterfacesClientRequest_class_() isInstance:o])) return false;
  return self->requestID_ == [((id<EduUmassCsGigapaxosInterfacesClientRequest>) nil_chk(((id<EduUmassCsGigapaxosInterfacesClientRequest>) cast_check(o, EduUmassCsGigapaxosInterfacesClientRequest_class_())))) getRequestID] && (self->needsCoordination_ == ([EduUmassCsReconfigurationInterfacesReplicableRequest_class_() isInstance:o] && [((id<EduUmassCsReconfigurationInterfacesReplicableRequest>) nil_chk(((id<EduUmassCsReconfigurationInterfacesReplicableRequest>) cast_check(o, EduUmassCsReconfigurationInterfacesReplicableRequest_class_())))) needsCoordination])) && ([((id<EduUmassCsGigapaxosInterfacesRequest>) nil_chk(self->request_)) isEqual:o] || ([o isKindOfClass:[EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest class]] && ([self->request_ isEqual:((EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *) nil_chk(((EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *) cast_chk(o, [EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest class]))))->request_] || JavaUtilArrays_equalsWithByteArray_withByteArray_(self->requestBytes_, ((EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *) nil_chk(((EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *) cast_chk(o, [EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest class]))))->requestBytes_))));
}

- (void)setNeedsCoordinationWithBoolean:(jboolean)arg0 {
  EduUmassCsReconfigurationInterfacesReplicableRequest_setNeedsCoordinationWithBoolean_(self, arg0);
}

- (id)getSummary {
  return EduUmassCsReconfigurationInterfacesReconfigurableRequest_getSummary(self);
}

- (id)getSummaryWithBoolean:(jboolean)arg0 {
  return EduUmassCsUtilsSummarizable_getSummaryWithBoolean_(self, arg0);
}

- (void)dealloc {
  RELEASE_(request_);
  RELEASE_(clientAddress_);
  RELEASE_(requestBytes_);
  RELEASE_(CHARSET_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LEduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest;", 0x9, 0, 1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest;", 0x9, 0, 2, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest;", 0x9, 0, 3, -1, -1, -1, -1 },
    { NULL, NULL, 0x0, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x0, -1, 3, -1, -1, -1, -1 },
    { NULL, NULL, 0x0, -1, 2, -1, -1, -1, -1 },
    { NULL, NULL, 0x0, -1, 4, -1, -1, -1, -1 },
    { NULL, NULL, 0x0, -1, 5, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsGigapaxosInterfacesRequest;", 0x2, 6, 7, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsGigapaxosInterfacesRequest;", 0x2, 6, 8, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsGigapaxosInterfacesRequest;", 0x2, 6, 9, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 8, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 10, -1, -1, -1, -1 },
    { NULL, NULL, 0x0, -1, 11, 12, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 13, 12, 14, -1, -1 },
    { NULL, "LEduUmassCsGigapaxosInterfacesRequest;", 0x1, 15, 16, 17, -1, -1, -1 },
    { NULL, "LEduUmassCsGigapaxosInterfacesRequest;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsGigapaxosInterfacesRequest;", 0x1, 15, 18, 17, -1, -1, -1 },
    { NULL, "LEduUmassCsNioInterfacesIntegerPacketType;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "J", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsGigapaxosInterfacesClientRequest;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgJsonJSONObject;", 0x4, -1, -1, 19, -1, -1, -1 },
    { NULL, "[B", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest;", 0x1, 20, 21, -1, -1, -1, -1 },
    { NULL, "LJavaNetInetSocketAddress;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 22, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 23, 24, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(wrapWithEduUmassCsGigapaxosInterfacesRequest:);
  methods[1].selector = @selector(wrapWithEduUmassCsGigapaxosInterfacesRequest:withLong:);
  methods[2].selector = @selector(wrapWithEduUmassCsGigapaxosInterfacesRequest:withBoolean:);
  methods[3].selector = @selector(initWithEduUmassCsGigapaxosInterfacesRequest:);
  methods[4].selector = @selector(initWithEduUmassCsGigapaxosInterfacesRequest:withBoolean:);
  methods[5].selector = @selector(initWithEduUmassCsGigapaxosInterfacesRequest:withLong:);
  methods[6].selector = @selector(initWithEduUmassCsGigapaxosInterfacesRequest:withLong:withBoolean:);
  methods[7].selector = @selector(initWithJavaNioByteBuffer:withEduUmassCsNioNioutilsNIOHeader:withId:);
  methods[8].selector = @selector(parseWithByteArray:withEduUmassCsNioNioutilsNIOHeader:withId:);
  methods[9].selector = @selector(parseWithByteArray:withEduUmassCsNioNioutilsNIOHeader:withEduUmassCsGigapaxosInterfacesAppRequestParserBytes:);
  methods[10].selector = @selector(parseWithByteArray:withEduUmassCsNioNioutilsNIOHeader:withEduUmassCsGigapaxosInterfacesAppRequestParser:);
  methods[11].selector = @selector(initWithByteArray:withEduUmassCsNioNioutilsNIOHeader:withEduUmassCsGigapaxosInterfacesAppRequestParserBytes:);
  methods[12].selector = @selector(initWithByteArray:withEduUmassCsGigapaxosInterfacesAppRequestParser:);
  methods[13].selector = @selector(initWithOrgJsonJSONObject:);
  methods[14].selector = @selector(initWithOrgJsonJSONObject:withEduUmassCsNioInterfacesStringifiable:);
  methods[15].selector = @selector(getRequestWithEduUmassCsGigapaxosInterfacesAppRequestParser:);
  methods[16].selector = @selector(getRequest);
  methods[17].selector = @selector(getRequestWithEduUmassCsGigapaxosInterfacesAppRequestParserBytes:withEduUmassCsNioNioutilsNIOHeader:);
  methods[18].selector = @selector(getRequestType);
  methods[19].selector = @selector(getServiceName);
  methods[20].selector = @selector(getRequestID);
  methods[21].selector = @selector(getEpochNumber);
  methods[22].selector = @selector(isStop);
  methods[23].selector = @selector(getResponse);
  methods[24].selector = @selector(needsCoordination);
  methods[25].selector = @selector(toJSONObjectImpl);
  methods[26].selector = @selector(toBytes);
  methods[27].selector = @selector(setClientAddressWithJavaNetInetSocketAddress:);
  methods[28].selector = @selector(getClientAddress);
  methods[29].selector = @selector(getRequestAsString);
  methods[30].selector = @selector(description);
  methods[31].selector = @selector(isEqual:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "request_", "LEduUmassCsGigapaxosInterfacesRequest;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "requestID_", "J", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "needsCoordination_", "Z", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "clientAddress_", "LJavaNetInetSocketAddress;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "requestBytes_", "[B", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "DEFAULT_COORDINATION_MODE", "Z", .constantValue.asBOOL = EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_DEFAULT_COORDINATION_MODE, 0x19, -1, -1, -1, -1 },
    { "CHARSET_", "LNSString;", .constantValue.asLong = 0, 0x11, -1, -1, -1, -1 },
    { "REQUEST_BYTES_OFFSET", "I", .constantValue.asInt = EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_REQUEST_BYTES_OFFSET, 0x1a, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "wrap", "LEduUmassCsGigapaxosInterfacesRequest;", "LEduUmassCsGigapaxosInterfacesRequest;J", "LEduUmassCsGigapaxosInterfacesRequest;Z", "LEduUmassCsGigapaxosInterfacesRequest;JZ", "LJavaNioByteBuffer;LEduUmassCsNioNioutilsNIOHeader;LNSObject;", "parse", "[BLEduUmassCsNioNioutilsNIOHeader;LNSObject;", "[BLEduUmassCsNioNioutilsNIOHeader;LEduUmassCsGigapaxosInterfacesAppRequestParserBytes;", "[BLEduUmassCsNioNioutilsNIOHeader;LEduUmassCsGigapaxosInterfacesAppRequestParser;", "[BLEduUmassCsGigapaxosInterfacesAppRequestParser;", "LOrgJsonJSONObject;", "LOrgJsonJSONException;LJavaIoUnsupportedEncodingException;", "LOrgJsonJSONObject;LEduUmassCsNioInterfacesStringifiable;", "(Lorg/json/JSONObject;Ledu/umass/cs/nio/interfaces/Stringifiable<*>;)V", "getRequest", "LEduUmassCsGigapaxosInterfacesAppRequestParser;", "LJavaIoUnsupportedEncodingException;LEduUmassCsReconfigurationReconfigurationutilsRequestParseException;", "LEduUmassCsGigapaxosInterfacesAppRequestParserBytes;LEduUmassCsNioNioutilsNIOHeader;", "LOrgJsonJSONException;", "setClientAddress", "LJavaNetInetSocketAddress;", "toString", "equals", "LNSObject;", "LEduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys;" };
  static const J2ObjcClassInfo _EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest = { "ReplicableClientRequest", "edu.umass.cs.reconfiguration.reconfigurationpackets", ptrTable, methods, fields, 7, 0x1, 32, 8, -1, 25, -1, -1, -1 };
  return &_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest;
}

@end

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_wrapWithEduUmassCsGigapaxosInterfacesRequest_(id<EduUmassCsGigapaxosInterfacesRequest> request) {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initialize();
  return create_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_(request);
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_wrapWithEduUmassCsGigapaxosInterfacesRequest_withLong_(id<EduUmassCsGigapaxosInterfacesRequest> request, jlong requestID) {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initialize();
  return create_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_withLong_(request, requestID);
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_wrapWithEduUmassCsGigapaxosInterfacesRequest_withBoolean_(id<EduUmassCsGigapaxosInterfacesRequest> request, jboolean coord) {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initialize();
  return create_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_withBoolean_(request, coord);
}

void EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *self, id<EduUmassCsGigapaxosInterfacesRequest> request) {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_withBoolean_(self, request, [EduUmassCsReconfigurationInterfacesReplicableRequest_class_() isInstance:request] ? [((id<EduUmassCsReconfigurationInterfacesReplicableRequest>) nil_chk(((id<EduUmassCsReconfigurationInterfacesReplicableRequest>) cast_check(request, EduUmassCsReconfigurationInterfacesReplicableRequest_class_())))) needsCoordination] : EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_DEFAULT_COORDINATION_MODE);
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *new_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_(id<EduUmassCsGigapaxosInterfacesRequest> request) {
  J2OBJC_NEW_IMPL(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest, initWithEduUmassCsGigapaxosInterfacesRequest_, request)
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *create_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_(id<EduUmassCsGigapaxosInterfacesRequest> request) {
  J2OBJC_CREATE_IMPL(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest, initWithEduUmassCsGigapaxosInterfacesRequest_, request)
}

void EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_withBoolean_(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *self, id<EduUmassCsGigapaxosInterfacesRequest> request, jboolean coord) {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_withLong_withBoolean_(self, request, [EduUmassCsGigapaxosInterfacesClientRequest_class_() isInstance:request] ? [((id<EduUmassCsGigapaxosInterfacesClientRequest>) nil_chk(((id<EduUmassCsGigapaxosInterfacesClientRequest>) cast_check(request, EduUmassCsGigapaxosInterfacesClientRequest_class_())))) getRequestID] : JreFpToLong((JavaLangMath_random() * JavaLangLong_MAX_VALUE)), coord);
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *new_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_withBoolean_(id<EduUmassCsGigapaxosInterfacesRequest> request, jboolean coord) {
  J2OBJC_NEW_IMPL(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest, initWithEduUmassCsGigapaxosInterfacesRequest_withBoolean_, request, coord)
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *create_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_withBoolean_(id<EduUmassCsGigapaxosInterfacesRequest> request, jboolean coord) {
  J2OBJC_CREATE_IMPL(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest, initWithEduUmassCsGigapaxosInterfacesRequest_withBoolean_, request, coord)
}

void EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_withLong_(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *self, id<EduUmassCsGigapaxosInterfacesRequest> request, jlong requestID) {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_withLong_withBoolean_(self, request, requestID, [EduUmassCsReconfigurationInterfacesReplicableRequest_class_() isInstance:request] ? [((id<EduUmassCsReconfigurationInterfacesReplicableRequest>) nil_chk(((id<EduUmassCsReconfigurationInterfacesReplicableRequest>) cast_check(request, EduUmassCsReconfigurationInterfacesReplicableRequest_class_())))) needsCoordination] : EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_DEFAULT_COORDINATION_MODE);
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *new_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_withLong_(id<EduUmassCsGigapaxosInterfacesRequest> request, jlong requestID) {
  J2OBJC_NEW_IMPL(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest, initWithEduUmassCsGigapaxosInterfacesRequest_withLong_, request, requestID)
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *create_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_withLong_(id<EduUmassCsGigapaxosInterfacesRequest> request, jlong requestID) {
  J2OBJC_CREATE_IMPL(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest, initWithEduUmassCsGigapaxosInterfacesRequest_withLong_, request, requestID)
}

void EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_withLong_withBoolean_(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *self, id<EduUmassCsGigapaxosInterfacesRequest> request, jlong requestID, jboolean coord) {
  EduUmassCsNioJSONPacket_initWithEduUmassCsNioInterfacesIntegerPacketType_(self, [((id<EduUmassCsGigapaxosInterfacesRequest>) nil_chk(request)) getRequestType]);
  JreStrongAssign(&self->clientAddress_, nil);
  JreStrongAssign(&self->CHARSET_, @"ISO-8859-1");
  JreStrongAssign(&self->request_, request);
  self->requestID_ = requestID;
  JreStrongAssign(&self->requestBytes_, nil);
  self->needsCoordination_ = coord;
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *new_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_withLong_withBoolean_(id<EduUmassCsGigapaxosInterfacesRequest> request, jlong requestID, jboolean coord) {
  J2OBJC_NEW_IMPL(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest, initWithEduUmassCsGigapaxosInterfacesRequest_withLong_withBoolean_, request, requestID, coord)
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *create_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithEduUmassCsGigapaxosInterfacesRequest_withLong_withBoolean_(id<EduUmassCsGigapaxosInterfacesRequest> request, jlong requestID, jboolean coord) {
  J2OBJC_CREATE_IMPL(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest, initWithEduUmassCsGigapaxosInterfacesRequest_withLong_withBoolean_, request, requestID, coord)
}

void EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithJavaNioByteBuffer_withEduUmassCsNioNioutilsNIOHeader_withId_(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *self, JavaNioByteBuffer *bbuf, EduUmassCsNioNioutilsNIOHeader *header, id parser) {
  EduUmassCsNioJSONPacket_initWithEduUmassCsNioInterfacesIntegerPacketType_(self, create_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_1_initWithJavaNioByteBuffer_(bbuf));
  JreStrongAssign(&self->clientAddress_, nil);
  JreStrongAssign(&self->CHARSET_, @"ISO-8859-1");
  self->requestID_ = [((JavaNioByteBuffer *) nil_chk(bbuf)) getLong];
  self->needsCoordination_ = [bbuf get] == 0 ? false : true;
  JreStrongAssign(&self->requestBytes_, JavaUtilArrays_copyOfRangeWithByteArray_withInt_withInt_([bbuf array], EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_REQUEST_BYTES_OFFSET, ((IOSByteArray *) nil_chk([bbuf array]))->size_));
  JreStrongAssign(&self->request_, EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_parseWithByteArray_withEduUmassCsNioNioutilsNIOHeader_withId_(self, self->requestBytes_, header, parser));
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *new_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithJavaNioByteBuffer_withEduUmassCsNioNioutilsNIOHeader_withId_(JavaNioByteBuffer *bbuf, EduUmassCsNioNioutilsNIOHeader *header, id parser) {
  J2OBJC_NEW_IMPL(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest, initWithJavaNioByteBuffer_withEduUmassCsNioNioutilsNIOHeader_withId_, bbuf, header, parser)
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *create_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithJavaNioByteBuffer_withEduUmassCsNioNioutilsNIOHeader_withId_(JavaNioByteBuffer *bbuf, EduUmassCsNioNioutilsNIOHeader *header, id parser) {
  J2OBJC_CREATE_IMPL(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest, initWithJavaNioByteBuffer_withEduUmassCsNioNioutilsNIOHeader_withId_, bbuf, header, parser)
}

id<EduUmassCsGigapaxosInterfacesRequest> EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_parseWithByteArray_withEduUmassCsNioNioutilsNIOHeader_withId_(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *self, IOSByteArray *buf, EduUmassCsNioNioutilsNIOHeader *header, id parser) {
  return [EduUmassCsGigapaxosInterfacesAppRequestParserBytes_class_() isInstance:parser] ? EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_parseWithByteArray_withEduUmassCsNioNioutilsNIOHeader_withEduUmassCsGigapaxosInterfacesAppRequestParserBytes_(self, buf, header, (id<EduUmassCsGigapaxosInterfacesAppRequestParserBytes>) cast_check(parser, EduUmassCsGigapaxosInterfacesAppRequestParserBytes_class_())) : EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_parseWithByteArray_withEduUmassCsNioNioutilsNIOHeader_withEduUmassCsGigapaxosInterfacesAppRequestParser_(self, buf, header, (id<EduUmassCsGigapaxosInterfacesAppRequestParser>) cast_check(parser, EduUmassCsGigapaxosInterfacesAppRequestParser_class_()));
}

id<EduUmassCsGigapaxosInterfacesRequest> EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_parseWithByteArray_withEduUmassCsNioNioutilsNIOHeader_withEduUmassCsGigapaxosInterfacesAppRequestParserBytes_(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *self, IOSByteArray *buf, EduUmassCsNioNioutilsNIOHeader *header, id<EduUmassCsGigapaxosInterfacesAppRequestParserBytes> parser) {
  @try {
    return [((id<EduUmassCsGigapaxosInterfacesAppRequestParserBytes>) nil_chk(parser)) getRequestWithByteArray:buf withEduUmassCsNioNioutilsNIOHeader:header];
  }
  @catch (EduUmassCsReconfigurationReconfigurationutilsRequestParseException *e) {
    [((EduUmassCsReconfigurationReconfigurationutilsRequestParseException *) nil_chk(e)) printStackTrace];
    return nil;
  }
}

id<EduUmassCsGigapaxosInterfacesRequest> EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_parseWithByteArray_withEduUmassCsNioNioutilsNIOHeader_withEduUmassCsGigapaxosInterfacesAppRequestParser_(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *self, IOSByteArray *buf, EduUmassCsNioNioutilsNIOHeader *header, id<EduUmassCsGigapaxosInterfacesAppRequestParser> parser) {
  @try {
    return [((id<EduUmassCsGigapaxosInterfacesAppRequestParser>) nil_chk(parser)) getRequestWithNSString:[NSString java_stringWithBytes:buf charsetName:self->CHARSET_]];
  }
  @catch (JavaIoUnsupportedEncodingException *e) {
    [((JavaLangException *) nil_chk(e)) printStackTrace];
    return nil;
  }
  @catch (EduUmassCsReconfigurationReconfigurationutilsRequestParseException *e) {
    [((JavaLangException *) nil_chk(e)) printStackTrace];
    return nil;
  }
}

void EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithByteArray_withEduUmassCsNioNioutilsNIOHeader_withEduUmassCsGigapaxosInterfacesAppRequestParserBytes_(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *self, IOSByteArray *buf, EduUmassCsNioNioutilsNIOHeader *header, id<EduUmassCsGigapaxosInterfacesAppRequestParserBytes> parser) {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithJavaNioByteBuffer_withEduUmassCsNioNioutilsNIOHeader_withId_(self, JavaNioByteBuffer_wrapWithByteArray_(buf), header, parser);
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *new_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithByteArray_withEduUmassCsNioNioutilsNIOHeader_withEduUmassCsGigapaxosInterfacesAppRequestParserBytes_(IOSByteArray *buf, EduUmassCsNioNioutilsNIOHeader *header, id<EduUmassCsGigapaxosInterfacesAppRequestParserBytes> parser) {
  J2OBJC_NEW_IMPL(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest, initWithByteArray_withEduUmassCsNioNioutilsNIOHeader_withEduUmassCsGigapaxosInterfacesAppRequestParserBytes_, buf, header, parser)
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *create_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithByteArray_withEduUmassCsNioNioutilsNIOHeader_withEduUmassCsGigapaxosInterfacesAppRequestParserBytes_(IOSByteArray *buf, EduUmassCsNioNioutilsNIOHeader *header, id<EduUmassCsGigapaxosInterfacesAppRequestParserBytes> parser) {
  J2OBJC_CREATE_IMPL(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest, initWithByteArray_withEduUmassCsNioNioutilsNIOHeader_withEduUmassCsGigapaxosInterfacesAppRequestParserBytes_, buf, header, parser)
}

void EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithByteArray_withEduUmassCsGigapaxosInterfacesAppRequestParser_(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *self, IOSByteArray *buf, id<EduUmassCsGigapaxosInterfacesAppRequestParser> parser) {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithJavaNioByteBuffer_withEduUmassCsNioNioutilsNIOHeader_withId_(self, JavaNioByteBuffer_wrapWithByteArray_(buf), nil, parser);
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *new_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithByteArray_withEduUmassCsGigapaxosInterfacesAppRequestParser_(IOSByteArray *buf, id<EduUmassCsGigapaxosInterfacesAppRequestParser> parser) {
  J2OBJC_NEW_IMPL(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest, initWithByteArray_withEduUmassCsGigapaxosInterfacesAppRequestParser_, buf, parser)
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *create_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithByteArray_withEduUmassCsGigapaxosInterfacesAppRequestParser_(IOSByteArray *buf, id<EduUmassCsGigapaxosInterfacesAppRequestParser> parser) {
  J2OBJC_CREATE_IMPL(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest, initWithByteArray_withEduUmassCsGigapaxosInterfacesAppRequestParser_, buf, parser)
}

void EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithOrgJsonJSONObject_(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *self, OrgJsonJSONObject *json) {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_(self, json, nil);
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *new_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithOrgJsonJSONObject_(OrgJsonJSONObject *json) {
  J2OBJC_NEW_IMPL(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest, initWithOrgJsonJSONObject_, json)
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *create_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithOrgJsonJSONObject_(OrgJsonJSONObject *json) {
  J2OBJC_CREATE_IMPL(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest, initWithOrgJsonJSONObject_, json)
}

void EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *self, OrgJsonJSONObject *json, id<EduUmassCsNioInterfacesStringifiable> unstringer) {
  EduUmassCsNioJSONPacket_initWithOrgJsonJSONObject_(self, json);
  JreStrongAssign(&self->clientAddress_, nil);
  JreStrongAssign(&self->CHARSET_, @"ISO-8859-1");
  self->requestID_ = [((OrgJsonJSONObject *) nil_chk(json)) getLongWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys, QID))) description]];
  JreStrongAssign(&self->request_, nil);
  self->needsCoordination_ = [json hasWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys, COORD))) description]] ? [json getBooleanWithNSString:[JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys, COORD) description]] : false;
  JreStrongAssign(&self->requestBytes_, [((NSString *) nil_chk([json getStringWithNSString:[((EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys *) nil_chk(JreLoadEnum(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys, QV))) description]])) java_getBytesWithCharsetName:self->CHARSET_]);
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *new_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_(OrgJsonJSONObject *json, id<EduUmassCsNioInterfacesStringifiable> unstringer) {
  J2OBJC_NEW_IMPL(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest, initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_, json, unstringer)
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest *create_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_(OrgJsonJSONObject *json, id<EduUmassCsNioInterfacesStringifiable> unstringer) {
  J2OBJC_CREATE_IMPL(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest, initWithOrgJsonJSONObject_withEduUmassCsNioInterfacesStringifiable_, json, unstringer)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest)

J2OBJC_INITIALIZED_DEFN(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys)

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys *EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_values_[3];

@implementation EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys

+ (IOSObjectArray *)values {
  return EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_values();
}

+ (EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys *)valueOfWithNSString:(NSString *)name {
  return EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_valueOfWithNSString_(name);
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "[LEduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(values);
  methods[1].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "QID", "LEduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys;", .constantValue.asLong = 0, 0x4019, -1, 2, -1, -1 },
    { "QV", "LEduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys;", .constantValue.asLong = 0, 0x4019, -1, 3, -1, -1 },
    { "COORD", "LEduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys;", .constantValue.asLong = 0, 0x4019, -1, 4, -1, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "LNSString;", &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys, QID), &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys, QV), &JreEnum(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys, COORD), "LEduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest;", "Ljava/lang/Enum<Ledu/umass/cs/reconfiguration/reconfigurationpackets/ReplicableClientRequest$Keys;>;" };
  static const J2ObjcClassInfo _EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys = { "Keys", "edu.umass.cs.reconfiguration.reconfigurationpackets", ptrTable, methods, fields, 7, 0x401a, 2, 3, 5, -1, -1, 6, -1 };
  return &_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys;
}

+ (void)initialize {
  if (self == [EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 3 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    id names[] = {
      @"QID", @"QV", @"COORD",
    };
    for (jint i = 0; i < 3; i++) {
      (EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_values_[i] = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
      EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_initWithNSString_withInt_(e, names[i], i);
    }
    J2OBJC_SET_INITIALIZED(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys)
  }
}

@end

void EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_initWithNSString_withInt_(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

IOSObjectArray *EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_values() {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_initialize();
  return [IOSObjectArray arrayWithObjects:EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_values_ count:3 type:EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_class_()];
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys *EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_valueOfWithNSString_(NSString *name) {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_initialize();
  for (int i = 0; i < 3; i++) {
    EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys *e = EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys *EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_fromOrdinal(NSUInteger ordinal) {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_initialize();
  if (ordinal >= 3) {
    return nil;
  }
  return EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_Keys)

@implementation EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_1

- (instancetype)initWithJavaNioByteBuffer:(JavaNioByteBuffer *)capture$0 {
  EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_1_initWithJavaNioByteBuffer_(self, capture$0);
  return self;
}

- (jint)getInt {
  return [((JavaNioByteBuffer *) nil_chk(val$bbuf_)) getInt];
}

- (void)dealloc {
  RELEASE_(val$bbuf_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithJavaNioByteBuffer:);
  methods[1].selector = @selector(getInt);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "val$bbuf_", "LJavaNioByteBuffer;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LEduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest;", "initWithJavaNioByteBuffer:withEduUmassCsNioNioutilsNIOHeader:withId:" };
  static const J2ObjcClassInfo _EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_1 = { "", "edu.umass.cs.reconfiguration.reconfigurationpackets", ptrTable, methods, fields, 7, 0x8008, 2, 1, 0, -1, 1, -1, -1 };
  return &_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_1;
}

@end

void EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_1_initWithJavaNioByteBuffer_(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_1 *self, JavaNioByteBuffer *capture$0) {
  JreStrongAssign(&self->val$bbuf_, capture$0);
  NSObject_init(self);
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_1 *new_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_1_initWithJavaNioByteBuffer_(JavaNioByteBuffer *capture$0) {
  J2OBJC_NEW_IMPL(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_1, initWithJavaNioByteBuffer_, capture$0)
}

EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_1 *create_EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_1_initWithJavaNioByteBuffer_(JavaNioByteBuffer *capture$0) {
  J2OBJC_CREATE_IMPL(EduUmassCsReconfigurationReconfigurationpacketsReplicableClientRequest_1, initWithJavaNioByteBuffer_, capture$0)
}
