//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../src/edu/umass/cs/gnsserver/main/OldHackyConstants.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "edu/umass/cs/gnsserver/main/OldHackyConstants.h"
#include "java/lang/Deprecated.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/annotation/Annotation.h"

__attribute__((unused)) static IOSObjectArray *EduUmassCsGnsserverMainOldHackyConstants__Annotations$0();

__attribute__((unused)) static void EduUmassCsGnsserverMainOldHackyConstants_PortType_initWithInt_withNSString_withInt_(EduUmassCsGnsserverMainOldHackyConstants_PortType *self, jint offset, NSString *__name, jint __ordinal);

__attribute__((unused)) static IOSObjectArray *EduUmassCsGnsserverMainOldHackyConstants_PortType__Annotations$0();

@implementation EduUmassCsGnsserverMainOldHackyConstants

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  EduUmassCsGnsserverMainOldHackyConstants_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "DEFAULT_STARTING_PORT", "I", .constantValue.asInt = EduUmassCsGnsserverMainOldHackyConstants_DEFAULT_STARTING_PORT, 0x19, -1, -1, -1, 0 },
  };
  static const void *ptrTable[] = { (void *)&EduUmassCsGnsserverMainOldHackyConstants__Annotations$0, "LEduUmassCsGnsserverMainOldHackyConstants_PortType;" };
  static const J2ObjcClassInfo _EduUmassCsGnsserverMainOldHackyConstants = { "OldHackyConstants", "edu.umass.cs.gnsserver.main", ptrTable, methods, fields, 7, 0x1, 1, 1, -1, 1, -1, -1, -1 };
  return &_EduUmassCsGnsserverMainOldHackyConstants;
}

@end

void EduUmassCsGnsserverMainOldHackyConstants_init(EduUmassCsGnsserverMainOldHackyConstants *self) {
  NSObject_init(self);
}

EduUmassCsGnsserverMainOldHackyConstants *new_EduUmassCsGnsserverMainOldHackyConstants_init() {
  J2OBJC_NEW_IMPL(EduUmassCsGnsserverMainOldHackyConstants, init)
}

EduUmassCsGnsserverMainOldHackyConstants *create_EduUmassCsGnsserverMainOldHackyConstants_init() {
  J2OBJC_CREATE_IMPL(EduUmassCsGnsserverMainOldHackyConstants, init)
}

IOSObjectArray *EduUmassCsGnsserverMainOldHackyConstants__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaLangDeprecated() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsGnsserverMainOldHackyConstants)

J2OBJC_INITIALIZED_DEFN(EduUmassCsGnsserverMainOldHackyConstants_PortType)

EduUmassCsGnsserverMainOldHackyConstants_PortType *EduUmassCsGnsserverMainOldHackyConstants_PortType_values_[6];

@implementation EduUmassCsGnsserverMainOldHackyConstants_PortType

+ (jint)maxOffset {
  return EduUmassCsGnsserverMainOldHackyConstants_PortType_maxOffset();
}

- (jint)getOffset {
  return offset_;
}

+ (IOSObjectArray *)values {
  return EduUmassCsGnsserverMainOldHackyConstants_PortType_values();
}

+ (EduUmassCsGnsserverMainOldHackyConstants_PortType *)valueOfWithNSString:(NSString *)name {
  return EduUmassCsGnsserverMainOldHackyConstants_PortType_valueOfWithNSString_(name);
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "I", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[LEduUmassCsGnsserverMainOldHackyConstants_PortType;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduUmassCsGnsserverMainOldHackyConstants_PortType;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(maxOffset);
  methods[1].selector = @selector(getOffset);
  methods[2].selector = @selector(values);
  methods[3].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "ACTIVE_REPLICA_PORT", "LEduUmassCsGnsserverMainOldHackyConstants_PortType;", .constantValue.asLong = 0, 0x4019, -1, 2, -1, -1 },
    { "RECONFIGURATOR_PORT", "LEduUmassCsGnsserverMainOldHackyConstants_PortType;", .constantValue.asLong = 0, 0x4019, -1, 3, -1, -1 },
    { "NS_TCP_PORT", "LEduUmassCsGnsserverMainOldHackyConstants_PortType;", .constantValue.asLong = 0, 0x4019, -1, 4, -1, -1 },
    { "NS_ADMIN_PORT", "LEduUmassCsGnsserverMainOldHackyConstants_PortType;", .constantValue.asLong = 0, 0x4019, -1, 5, -1, -1 },
    { "CCP_PORT", "LEduUmassCsGnsserverMainOldHackyConstants_PortType;", .constantValue.asLong = 0, 0x4019, -1, 6, -1, -1 },
    { "CCP_ADMIN_PORT", "LEduUmassCsGnsserverMainOldHackyConstants_PortType;", .constantValue.asLong = 0, 0x4019, -1, 7, -1, -1 },
    { "offset_", "I", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "LNSString;", &JreEnum(EduUmassCsGnsserverMainOldHackyConstants_PortType, ACTIVE_REPLICA_PORT), &JreEnum(EduUmassCsGnsserverMainOldHackyConstants_PortType, RECONFIGURATOR_PORT), &JreEnum(EduUmassCsGnsserverMainOldHackyConstants_PortType, NS_TCP_PORT), &JreEnum(EduUmassCsGnsserverMainOldHackyConstants_PortType, NS_ADMIN_PORT), &JreEnum(EduUmassCsGnsserverMainOldHackyConstants_PortType, CCP_PORT), &JreEnum(EduUmassCsGnsserverMainOldHackyConstants_PortType, CCP_ADMIN_PORT), "LEduUmassCsGnsserverMainOldHackyConstants;", "Ljava/lang/Enum<Ledu/umass/cs/gnsserver/main/OldHackyConstants$PortType;>;", (void *)&EduUmassCsGnsserverMainOldHackyConstants_PortType__Annotations$0 };
  static const J2ObjcClassInfo _EduUmassCsGnsserverMainOldHackyConstants_PortType = { "PortType", "edu.umass.cs.gnsserver.main", ptrTable, methods, fields, 7, 0x4019, 4, 7, 8, -1, -1, 9, 10 };
  return &_EduUmassCsGnsserverMainOldHackyConstants_PortType;
}

+ (void)initialize {
  if (self == [EduUmassCsGnsserverMainOldHackyConstants_PortType class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 6 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    (JreEnum(EduUmassCsGnsserverMainOldHackyConstants_PortType, ACTIVE_REPLICA_PORT) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    EduUmassCsGnsserverMainOldHackyConstants_PortType_initWithInt_withNSString_withInt_(e, 0, @"ACTIVE_REPLICA_PORT", 0);
    (JreEnum(EduUmassCsGnsserverMainOldHackyConstants_PortType, RECONFIGURATOR_PORT) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    EduUmassCsGnsserverMainOldHackyConstants_PortType_initWithInt_withNSString_withInt_(e, 1, @"RECONFIGURATOR_PORT", 1);
    (JreEnum(EduUmassCsGnsserverMainOldHackyConstants_PortType, NS_TCP_PORT) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    EduUmassCsGnsserverMainOldHackyConstants_PortType_initWithInt_withNSString_withInt_(e, 3, @"NS_TCP_PORT", 2);
    (JreEnum(EduUmassCsGnsserverMainOldHackyConstants_PortType, NS_ADMIN_PORT) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    EduUmassCsGnsserverMainOldHackyConstants_PortType_initWithInt_withNSString_withInt_(e, 4, @"NS_ADMIN_PORT", 3);
    (JreEnum(EduUmassCsGnsserverMainOldHackyConstants_PortType, CCP_PORT) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    EduUmassCsGnsserverMainOldHackyConstants_PortType_initWithInt_withNSString_withInt_(e, 6, @"CCP_PORT", 4);
    (JreEnum(EduUmassCsGnsserverMainOldHackyConstants_PortType, CCP_ADMIN_PORT) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    EduUmassCsGnsserverMainOldHackyConstants_PortType_initWithInt_withNSString_withInt_(e, 7, @"CCP_ADMIN_PORT", 5);
    J2OBJC_SET_INITIALIZED(EduUmassCsGnsserverMainOldHackyConstants_PortType)
  }
}

@end

void EduUmassCsGnsserverMainOldHackyConstants_PortType_initWithInt_withNSString_withInt_(EduUmassCsGnsserverMainOldHackyConstants_PortType *self, jint offset, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
  self->offset_ = offset;
}

jint EduUmassCsGnsserverMainOldHackyConstants_PortType_maxOffset() {
  EduUmassCsGnsserverMainOldHackyConstants_PortType_initialize();
  jint result = 0;
  {
    IOSObjectArray *a__ = EduUmassCsGnsserverMainOldHackyConstants_PortType_values();
    EduUmassCsGnsserverMainOldHackyConstants_PortType * const *b__ = ((IOSObjectArray *) nil_chk(a__))->buffer_;
    EduUmassCsGnsserverMainOldHackyConstants_PortType * const *e__ = b__ + a__->size_;
    while (b__ < e__) {
      EduUmassCsGnsserverMainOldHackyConstants_PortType *p = *b__++;
      if (((EduUmassCsGnsserverMainOldHackyConstants_PortType *) nil_chk(p))->offset_ > result) {
        result = p->offset_;
      }
    }
  }
  return result;
}

IOSObjectArray *EduUmassCsGnsserverMainOldHackyConstants_PortType_values() {
  EduUmassCsGnsserverMainOldHackyConstants_PortType_initialize();
  return [IOSObjectArray arrayWithObjects:EduUmassCsGnsserverMainOldHackyConstants_PortType_values_ count:6 type:EduUmassCsGnsserverMainOldHackyConstants_PortType_class_()];
}

EduUmassCsGnsserverMainOldHackyConstants_PortType *EduUmassCsGnsserverMainOldHackyConstants_PortType_valueOfWithNSString_(NSString *name) {
  EduUmassCsGnsserverMainOldHackyConstants_PortType_initialize();
  for (int i = 0; i < 6; i++) {
    EduUmassCsGnsserverMainOldHackyConstants_PortType *e = EduUmassCsGnsserverMainOldHackyConstants_PortType_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

EduUmassCsGnsserverMainOldHackyConstants_PortType *EduUmassCsGnsserverMainOldHackyConstants_PortType_fromOrdinal(NSUInteger ordinal) {
  EduUmassCsGnsserverMainOldHackyConstants_PortType_initialize();
  if (ordinal >= 6) {
    return nil;
  }
  return EduUmassCsGnsserverMainOldHackyConstants_PortType_values_[ordinal];
}

IOSObjectArray *EduUmassCsGnsserverMainOldHackyConstants_PortType__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaLangDeprecated() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsGnsserverMainOldHackyConstants_PortType)
