//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../src/edu/umass/cs/gnsclient/client/util/Password.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsGnsclientClientUtilPassword")
#ifdef RESTRICT_EduUmassCsGnsclientClientUtilPassword
#define INCLUDE_ALL_EduUmassCsGnsclientClientUtilPassword 0
#else
#define INCLUDE_ALL_EduUmassCsGnsclientClientUtilPassword 1
#endif
#undef RESTRICT_EduUmassCsGnsclientClientUtilPassword

#if !defined (EduUmassCsGnsclientClientUtilPassword_) && (INCLUDE_ALL_EduUmassCsGnsclientClientUtilPassword || defined(INCLUDE_EduUmassCsGnsclientClientUtilPassword))
#define EduUmassCsGnsclientClientUtilPassword_

@interface EduUmassCsGnsclientClientUtilPassword : NSObject

#pragma mark Public

- (instancetype)init;

+ (NSString *)encryptAndEncodePasswordWithNSString:(NSString *)password
                                      withNSString:(NSString *)alias;

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsGnsclientClientUtilPassword)

FOUNDATION_EXPORT void EduUmassCsGnsclientClientUtilPassword_init(EduUmassCsGnsclientClientUtilPassword *self);

FOUNDATION_EXPORT EduUmassCsGnsclientClientUtilPassword *new_EduUmassCsGnsclientClientUtilPassword_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGnsclientClientUtilPassword *create_EduUmassCsGnsclientClientUtilPassword_init();

FOUNDATION_EXPORT NSString *EduUmassCsGnsclientClientUtilPassword_encryptAndEncodePasswordWithNSString_withNSString_(NSString *password, NSString *alias);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsGnsclientClientUtilPassword)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsGnsclientClientUtilPassword")
