//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../gig_ios/src/edu/umass/cs/gigapaxos/async/RequestCallbackFuture.java
//

#include "J2ObjC_source.h"
#include "edu/umass/cs/gigapaxos/async/RequestCallbackFuture.h"
#include "edu/umass/cs/gigapaxos/interfaces/Callback.h"
#include "edu/umass/cs/gigapaxos/interfaces/Request.h"
#include "java/lang/Exception.h"
#include "java/lang/InterruptedException.h"
#include "java/lang/Long.h"
#include "java/util/concurrent/ExecutionException.h"
#include "java/util/concurrent/TimeUnit.h"
#include "java/util/concurrent/TimeoutException.h"

@interface EduUmassCsGigapaxosAsyncRequestCallbackFuture () {
 @public
  id<EduUmassCsGigapaxosInterfacesRequest> request_;
  id<EduUmassCsGigapaxosInterfacesCallback> callback_;
  id<EduUmassCsGigapaxosInterfacesRequest> response_;
  JavaLangException *exception_;
  jboolean processResponseInvoked_;
}

- (id)waitResponseWithJavaLangLong:(JavaLangLong *)timeout
    withJavaUtilConcurrentTimeUnit:(JavaUtilConcurrentTimeUnit *)unit;

- (id)waitResponse;

@end

J2OBJC_FIELD_SETTER(EduUmassCsGigapaxosAsyncRequestCallbackFuture, request_, id<EduUmassCsGigapaxosInterfacesRequest>)
J2OBJC_FIELD_SETTER(EduUmassCsGigapaxosAsyncRequestCallbackFuture, callback_, id<EduUmassCsGigapaxosInterfacesCallback>)
J2OBJC_FIELD_SETTER(EduUmassCsGigapaxosAsyncRequestCallbackFuture, response_, id<EduUmassCsGigapaxosInterfacesRequest>)
J2OBJC_FIELD_SETTER(EduUmassCsGigapaxosAsyncRequestCallbackFuture, exception_, JavaLangException *)

__attribute__((unused)) static id EduUmassCsGigapaxosAsyncRequestCallbackFuture_waitResponseWithJavaLangLong_withJavaUtilConcurrentTimeUnit_(EduUmassCsGigapaxosAsyncRequestCallbackFuture *self, JavaLangLong *timeout, JavaUtilConcurrentTimeUnit *unit);

__attribute__((unused)) static id EduUmassCsGigapaxosAsyncRequestCallbackFuture_waitResponse(EduUmassCsGigapaxosAsyncRequestCallbackFuture *self);

@implementation EduUmassCsGigapaxosAsyncRequestCallbackFuture

- (instancetype)initWithEduUmassCsGigapaxosInterfacesRequest:(id<EduUmassCsGigapaxosInterfacesRequest>)request
                   withEduUmassCsGigapaxosInterfacesCallback:(id<EduUmassCsGigapaxosInterfacesCallback>)callback {
  EduUmassCsGigapaxosAsyncRequestCallbackFuture_initWithEduUmassCsGigapaxosInterfacesRequest_withEduUmassCsGigapaxosInterfacesCallback_(self, request, callback);
  return self;
}

- (id)waitResponseWithJavaLangLong:(JavaLangLong *)timeout
    withJavaUtilConcurrentTimeUnit:(JavaUtilConcurrentTimeUnit *)unit {
  return EduUmassCsGigapaxosAsyncRequestCallbackFuture_waitResponseWithJavaLangLong_withJavaUtilConcurrentTimeUnit_(self, timeout, unit);
}

- (id)waitResponse {
  return EduUmassCsGigapaxosAsyncRequestCallbackFuture_waitResponse(self);
}

- (jboolean)isDone {
  @try {
    return EduUmassCsGigapaxosAsyncRequestCallbackFuture_waitResponse(self) != nil;
  }
  @catch (JavaUtilConcurrentExecutionException *e) {
    return true;
  }
}

- (id)get {
  return EduUmassCsGigapaxosAsyncRequestCallbackFuture_waitResponse(self);
}

- (id)getWithLong:(jlong)timeout
withJavaUtilConcurrentTimeUnit:(JavaUtilConcurrentTimeUnit *)unit {
  id response = EduUmassCsGigapaxosAsyncRequestCallbackFuture_waitResponseWithJavaLangLong_withJavaUtilConcurrentTimeUnit_(self, JavaLangLong_valueOfWithLong_(timeout), unit);
  if (!self->processResponseInvoked_) @throw create_JavaUtilConcurrentTimeoutException_initWithNSString_(JreStrcat("$@$J$", @"Request ", [((id<EduUmassCsGigapaxosInterfacesRequest>) nil_chk(request_)) getSummary], @" timed out after ", [((JavaUtilConcurrentTimeUnit *) nil_chk(unit)) toMillisWithLong:timeout], @"ms"));
  return response;
}

- (id<EduUmassCsGigapaxosInterfacesRequest>)getRequest {
  return self->request_;
}

- (id)processResponseWithId:(id<EduUmassCsGigapaxosInterfacesRequest>)response {
  id retval = nil;
  self->processResponseInvoked_ = true;
  if (self->callback_ != nil) @try {
    retval = [self->callback_ processResponseWithId:response];
  }
  @catch (JavaLangException *e) {
    JreStrongAssign(&self->exception_, e);
  }
  @synchronized(self) {
    JreStrongAssign(&self->response_, response);
    [self java_notify];
  }
  return retval;
}

- (void)dealloc {
  RELEASE_(request_);
  RELEASE_(callback_);
  RELEASE_(response_);
  RELEASE_(exception_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, 1, -1, -1 },
    { NULL, "LNSObject;", 0x2, 2, 3, 4, 5, -1, -1 },
    { NULL, "LNSObject;", 0x2, -1, -1, 4, 6, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, 7, 6, -1, -1 },
    { NULL, "LNSObject;", 0x1, 8, 9, 10, 11, -1, -1 },
    { NULL, "LEduUmassCsGigapaxosInterfacesRequest;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 12, 13, -1, 14, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithEduUmassCsGigapaxosInterfacesRequest:withEduUmassCsGigapaxosInterfacesCallback:);
  methods[1].selector = @selector(waitResponseWithJavaLangLong:withJavaUtilConcurrentTimeUnit:);
  methods[2].selector = @selector(waitResponse);
  methods[3].selector = @selector(isDone);
  methods[4].selector = @selector(get);
  methods[5].selector = @selector(getWithLong:withJavaUtilConcurrentTimeUnit:);
  methods[6].selector = @selector(getRequest);
  methods[7].selector = @selector(processResponseWithId:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "request_", "LEduUmassCsGigapaxosInterfacesRequest;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "callback_", "LEduUmassCsGigapaxosInterfacesCallback;", .constantValue.asLong = 0, 0x12, -1, -1, 15, -1 },
    { "response_", "LEduUmassCsGigapaxosInterfacesRequest;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "exception_", "LJavaLangException;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "processResponseInvoked_", "Z", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LEduUmassCsGigapaxosInterfacesRequest;LEduUmassCsGigapaxosInterfacesCallback;", "(Ledu/umass/cs/gigapaxos/interfaces/Request;Ledu/umass/cs/gigapaxos/interfaces/Callback<Ledu/umass/cs/gigapaxos/interfaces/Request;TV;>;)V", "waitResponse", "LJavaLangLong;LJavaUtilConcurrentTimeUnit;", "LJavaUtilConcurrentExecutionException;", "(Ljava/lang/Long;Ljava/util/concurrent/TimeUnit;)TV;", "()TV;", "LJavaLangInterruptedException;LJavaUtilConcurrentExecutionException;", "get", "JLJavaUtilConcurrentTimeUnit;", "LJavaUtilConcurrentExecutionException;LJavaUtilConcurrentTimeoutException;", "(JLjava/util/concurrent/TimeUnit;)TV;", "processResponse", "LEduUmassCsGigapaxosInterfacesRequest;", "(Ledu/umass/cs/gigapaxos/interfaces/Request;)TV;", "Ledu/umass/cs/gigapaxos/interfaces/Callback<Ledu/umass/cs/gigapaxos/interfaces/Request;TV;>;", "<V:Ljava/lang/Object;>Ljava/lang/Object;Ledu/umass/cs/gigapaxos/interfaces/Callback<Ledu/umass/cs/gigapaxos/interfaces/Request;TV;>;Ledu/umass/cs/gigapaxos/interfaces/RequestFuture<TV;>;" };
  static const J2ObjcClassInfo _EduUmassCsGigapaxosAsyncRequestCallbackFuture = { "RequestCallbackFuture", "edu.umass.cs.gigapaxos.async", ptrTable, methods, fields, 7, 0x1, 8, 5, -1, -1, -1, 16, -1 };
  return &_EduUmassCsGigapaxosAsyncRequestCallbackFuture;
}

@end

void EduUmassCsGigapaxosAsyncRequestCallbackFuture_initWithEduUmassCsGigapaxosInterfacesRequest_withEduUmassCsGigapaxosInterfacesCallback_(EduUmassCsGigapaxosAsyncRequestCallbackFuture *self, id<EduUmassCsGigapaxosInterfacesRequest> request, id<EduUmassCsGigapaxosInterfacesCallback> callback) {
  NSObject_init(self);
  self->processResponseInvoked_ = false;
  JreStrongAssign(&self->request_, request);
  JreStrongAssign(&self->callback_, callback);
}

EduUmassCsGigapaxosAsyncRequestCallbackFuture *new_EduUmassCsGigapaxosAsyncRequestCallbackFuture_initWithEduUmassCsGigapaxosInterfacesRequest_withEduUmassCsGigapaxosInterfacesCallback_(id<EduUmassCsGigapaxosInterfacesRequest> request, id<EduUmassCsGigapaxosInterfacesCallback> callback) {
  J2OBJC_NEW_IMPL(EduUmassCsGigapaxosAsyncRequestCallbackFuture, initWithEduUmassCsGigapaxosInterfacesRequest_withEduUmassCsGigapaxosInterfacesCallback_, request, callback)
}

EduUmassCsGigapaxosAsyncRequestCallbackFuture *create_EduUmassCsGigapaxosAsyncRequestCallbackFuture_initWithEduUmassCsGigapaxosInterfacesRequest_withEduUmassCsGigapaxosInterfacesCallback_(id<EduUmassCsGigapaxosInterfacesRequest> request, id<EduUmassCsGigapaxosInterfacesCallback> callback) {
  J2OBJC_CREATE_IMPL(EduUmassCsGigapaxosAsyncRequestCallbackFuture, initWithEduUmassCsGigapaxosInterfacesRequest_withEduUmassCsGigapaxosInterfacesCallback_, request, callback)
}

id EduUmassCsGigapaxosAsyncRequestCallbackFuture_waitResponseWithJavaLangLong_withJavaUtilConcurrentTimeUnit_(EduUmassCsGigapaxosAsyncRequestCallbackFuture *self, JavaLangLong *timeout, JavaUtilConcurrentTimeUnit *unit) {
  if (self->exception_ != nil) @throw create_JavaUtilConcurrentExecutionException_initWithNSException_(self->exception_);
  @synchronized(self) {
    if (self->response_ == nil) @try {
      if (timeout != nil) [self java_waitWithLong:[((JavaUtilConcurrentTimeUnit *) nil_chk(unit)) toMillisWithLong:[timeout longLongValue]]];
      else [self java_wait];
    }
    @catch (JavaLangInterruptedException *e) {
      [((JavaLangInterruptedException *) nil_chk(e)) printStackTrace];
    }
  }
  return self->response_;
}

id EduUmassCsGigapaxosAsyncRequestCallbackFuture_waitResponse(EduUmassCsGigapaxosAsyncRequestCallbackFuture *self) {
  return EduUmassCsGigapaxosAsyncRequestCallbackFuture_waitResponseWithJavaLangLong_withJavaUtilConcurrentTimeUnit_(self, nil, JreLoadEnum(JavaUtilConcurrentTimeUnit, MILLISECONDS));
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsGigapaxosAsyncRequestCallbackFuture)
