//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../src/edu/umass/cs/gnsserver/nodeconfig/GNSNodeConfig.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsGnsserverNodeconfigGNSNodeConfig")
#ifdef RESTRICT_EduUmassCsGnsserverNodeconfigGNSNodeConfig
#define INCLUDE_ALL_EduUmassCsGnsserverNodeconfigGNSNodeConfig 0
#else
#define INCLUDE_ALL_EduUmassCsGnsserverNodeconfigGNSNodeConfig 1
#endif
#undef RESTRICT_EduUmassCsGnsserverNodeconfigGNSNodeConfig

#if !defined (EduUmassCsGnsserverNodeconfigGNSNodeConfig_) && (INCLUDE_ALL_EduUmassCsGnsserverNodeconfigGNSNodeConfig || defined(INCLUDE_EduUmassCsGnsserverNodeconfigGNSNodeConfig))
#define EduUmassCsGnsserverNodeconfigGNSNodeConfig_

#define RESTRICT_EduUmassCsGnsserverNodeconfigGNSInterfaceNodeConfig 1
#define INCLUDE_EduUmassCsGnsserverNodeconfigGNSInterfaceNodeConfig 1
#include "edu/umass/cs/gnsserver/nodeconfig/GNSInterfaceNodeConfig.h"

#define RESTRICT_EduUmassCsGnsserverUtilsGNSShutdownable 1
#define INCLUDE_EduUmassCsGnsserverUtilsGNSShutdownable 1
#include "edu/umass/cs/gnsserver/utils/GNSShutdownable.h"

#define RESTRICT_EduUmassCsNioNioutilsInterfaceDelayEmulator 1
#define INCLUDE_EduUmassCsNioNioutilsInterfaceDelayEmulator 1
#include "edu/umass/cs/nio/nioutils/InterfaceDelayEmulator.h"

@class EduUmassCsGnsserverMainOldHackyConstants_PortType;
@class JavaNetInetAddress;
@class OrgJsonJSONArray;
@protocol JavaUtilSet;

@interface EduUmassCsGnsserverNodeconfigGNSNodeConfig : NSObject < EduUmassCsGnsserverNodeconfigGNSInterfaceNodeConfig, EduUmassCsGnsserverUtilsGNSShutdownable, EduUmassCsNioNioutilsInterfaceDelayEmulator >

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)hostsFile
                          withId:(id)nameServerID;

- (id<JavaUtilSet>)getActiveReplicas;

- (jint)getAdminPortWithId:(id)id_;

- (JavaNetInetAddress *)getBindAddressWithId:(id)id_;

- (jint)getCcpAdminPortWithId:(id)id_;

- (jint)getCcpPortWithId:(id)id_;

- (id)getClosestServer;

- (id)getClosestServerWithJavaUtilSet:(id<JavaUtilSet>)servers;

- (id)getClosestServerWithJavaUtilSet:(id<JavaUtilSet>)serverIds
                      withJavaUtilSet:(id<JavaUtilSet>)excludeServers;

- (jlong)getEmulatedDelayWithId:(id)node2;

- (JavaNetInetAddress *)getNodeAddressWithId:(id)id_;

- (id<JavaUtilSet>)getNodeIDs;

- (jint)getNodePortWithId:(id)id_;

- (jint)getNumberOfNodes;

- (jlong)getPingLatencyWithId:(id)id_;

- (jint)getPortForTopLevelNodeWithId:(id)nameServerId
withEduUmassCsGnsserverMainOldHackyConstants_PortType:(EduUmassCsGnsserverMainOldHackyConstants_PortType *)portType;

- (id)getReconfiguratorNodeIdForTopLevelNodeWithId:(id)id_;

- (id<JavaUtilSet>)getReconfigurators;

- (id)getReplicaNodeIdForTopLevelNodeWithId:(id)id_;

- (id<JavaUtilSet>)getValuesFromJSONArrayWithOrgJsonJSONArray:(OrgJsonJSONArray *)array;

- (id<JavaUtilSet>)getValuesFromStringSetWithJavaUtilSet:(id<JavaUtilSet>)strNodes;

- (jlong)getVersion;

- (jboolean)isActiveReplicaWithId:(id)id_;

- (jboolean)nodeExistsWithId:(id)id_;

- (void)shutdown;

- (NSString *)description;

- (void)updatePingLatencyWithId:(id)id_
                       withLong:(jlong)responseTime;

- (id)valueOfWithNSString:(NSString *)nodeAsString;

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsGnsserverNodeconfigGNSNodeConfig)

inline jlong EduUmassCsGnsserverNodeconfigGNSNodeConfig_get_INVALID_PING_LATENCY();
#define EduUmassCsGnsserverNodeconfigGNSNodeConfig_INVALID_PING_LATENCY -1LL
J2OBJC_STATIC_FIELD_CONSTANT(EduUmassCsGnsserverNodeconfigGNSNodeConfig, INVALID_PING_LATENCY, jlong)

inline jint EduUmassCsGnsserverNodeconfigGNSNodeConfig_get_INVALID_PORT();
#define EduUmassCsGnsserverNodeconfigGNSNodeConfig_INVALID_PORT -1
J2OBJC_STATIC_FIELD_CONSTANT(EduUmassCsGnsserverNodeconfigGNSNodeConfig, INVALID_PORT, jint)

FOUNDATION_EXPORT void EduUmassCsGnsserverNodeconfigGNSNodeConfig_init(EduUmassCsGnsserverNodeconfigGNSNodeConfig *self);

FOUNDATION_EXPORT EduUmassCsGnsserverNodeconfigGNSNodeConfig *new_EduUmassCsGnsserverNodeconfigGNSNodeConfig_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGnsserverNodeconfigGNSNodeConfig *create_EduUmassCsGnsserverNodeconfigGNSNodeConfig_init();

FOUNDATION_EXPORT void EduUmassCsGnsserverNodeconfigGNSNodeConfig_initWithNSString_withId_(EduUmassCsGnsserverNodeconfigGNSNodeConfig *self, NSString *hostsFile, id nameServerID);

FOUNDATION_EXPORT EduUmassCsGnsserverNodeconfigGNSNodeConfig *new_EduUmassCsGnsserverNodeconfigGNSNodeConfig_initWithNSString_withId_(NSString *hostsFile, id nameServerID) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGnsserverNodeconfigGNSNodeConfig *create_EduUmassCsGnsserverNodeconfigGNSNodeConfig_initWithNSString_withId_(NSString *hostsFile, id nameServerID);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsGnsserverNodeconfigGNSNodeConfig)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsGnsserverNodeconfigGNSNodeConfig")
