//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../src/edu/umass/cs/gnsserver/gnsapp/packet/BasicPacketWithClientAddress.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress")
#ifdef RESTRICT_EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress
#define INCLUDE_ALL_EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress 0
#else
#define INCLUDE_ALL_EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress 1
#endif
#undef RESTRICT_EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress

#if !defined (EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress_) && (INCLUDE_ALL_EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress || defined(INCLUDE_EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress))
#define EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress_

#define RESTRICT_EduUmassCsGnsserverGnsappPacketBasicPacket 1
#define INCLUDE_EduUmassCsGnsserverGnsappPacketBasicPacket 1
#include "edu/umass/cs/gnsserver/gnsapp/packet/BasicPacket.h"

@class JavaNetInetSocketAddress;
@class OrgJsonJSONObject;
@protocol EduUmassCsGigapaxosInterfacesClientRequest;

@interface EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress : EduUmassCsGnsserverGnsappPacketBasicPacket {
 @public
  id<EduUmassCsGigapaxosInterfacesClientRequest> response_;
}

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithOrgJsonJSONObject:(OrgJsonJSONObject *)json;

- (void)addToJSONObjectWithOrgJsonJSONObject:(OrgJsonJSONObject *)json;

- (JavaNetInetSocketAddress *)getClientAddress;

- (EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress *)setResponseWithEduUmassCsGigapaxosInterfacesClientRequest:(id<EduUmassCsGigapaxosInterfacesClientRequest>)response;

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress)

J2OBJC_FIELD_SETTER(EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress, response_, id<EduUmassCsGigapaxosInterfacesClientRequest>)

FOUNDATION_EXPORT void EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress_init(EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress *self);

FOUNDATION_EXPORT void EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress_initWithOrgJsonJSONObject_(EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress *self, OrgJsonJSONObject *json);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsGnsserverGnsappPacketBasicPacketWithClientAddress")
