//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../src/edu/umass/cs/gnsserver/gnsapp/packet/PacketInterface.java
//

#include "J2ObjC_source.h"
#include "edu/umass/cs/gnsserver/gnsapp/packet/PacketInterface.h"

@interface EduUmassCsGnsserverGnsappPacketPacketInterface : NSObject

@end

@implementation EduUmassCsGnsserverGnsappPacketPacketInterface

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LOrgJsonJSONObject;", 0x401, -1, -1, 0, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(toJSONObject);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LOrgJsonJSONException;" };
  static const J2ObjcClassInfo _EduUmassCsGnsserverGnsappPacketPacketInterface = { "PacketInterface", "edu.umass.cs.gnsserver.gnsapp.packet", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_EduUmassCsGnsserverGnsappPacketPacketInterface;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(EduUmassCsGnsserverGnsappPacketPacketInterface)
