//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../src/edu/umass/cs/gnscommon/exceptions/client/AclException.java
//

#include "J2ObjC_source.h"
#include "edu/umass/cs/gnscommon/ResponseCode.h"
#include "edu/umass/cs/gnscommon/exceptions/client/AclException.h"
#include "edu/umass/cs/gnscommon/exceptions/client/ClientException.h"

inline jlong EduUmassCsGnscommonExceptionsClientAclException_get_serialVersionUID();
#define EduUmassCsGnscommonExceptionsClientAclException_serialVersionUID 7789779657368481702LL
J2OBJC_STATIC_FIELD_CONSTANT(EduUmassCsGnscommonExceptionsClientAclException, serialVersionUID, jlong)

@implementation EduUmassCsGnscommonExceptionsClientAclException

- (instancetype)initWithEduUmassCsGnscommonResponseCode:(EduUmassCsGnscommonResponseCode *)code
                                           withNSString:(NSString *)message {
  EduUmassCsGnscommonExceptionsClientAclException_initWithEduUmassCsGnscommonResponseCode_withNSString_(self, code, message);
  return self;
}

- (instancetype)initWithNSString:(NSString *)message {
  EduUmassCsGnscommonExceptionsClientAclException_initWithNSString_(self, message);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithEduUmassCsGnscommonResponseCode:withNSString:);
  methods[1].selector = @selector(initWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "J", .constantValue.asLong = EduUmassCsGnscommonExceptionsClientAclException_serialVersionUID, 0x1a, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LEduUmassCsGnscommonResponseCode;LNSString;", "LNSString;" };
  static const J2ObjcClassInfo _EduUmassCsGnscommonExceptionsClientAclException = { "AclException", "edu.umass.cs.gnscommon.exceptions.client", ptrTable, methods, fields, 7, 0x1, 2, 1, -1, -1, -1, -1, -1 };
  return &_EduUmassCsGnscommonExceptionsClientAclException;
}

@end

void EduUmassCsGnscommonExceptionsClientAclException_initWithEduUmassCsGnscommonResponseCode_withNSString_(EduUmassCsGnscommonExceptionsClientAclException *self, EduUmassCsGnscommonResponseCode *code, NSString *message) {
  EduUmassCsGnscommonExceptionsClientClientException_initWithEduUmassCsGnscommonResponseCode_withNSString_(self, code, message);
}

EduUmassCsGnscommonExceptionsClientAclException *new_EduUmassCsGnscommonExceptionsClientAclException_initWithEduUmassCsGnscommonResponseCode_withNSString_(EduUmassCsGnscommonResponseCode *code, NSString *message) {
  J2OBJC_NEW_IMPL(EduUmassCsGnscommonExceptionsClientAclException, initWithEduUmassCsGnscommonResponseCode_withNSString_, code, message)
}

EduUmassCsGnscommonExceptionsClientAclException *create_EduUmassCsGnscommonExceptionsClientAclException_initWithEduUmassCsGnscommonResponseCode_withNSString_(EduUmassCsGnscommonResponseCode *code, NSString *message) {
  J2OBJC_CREATE_IMPL(EduUmassCsGnscommonExceptionsClientAclException, initWithEduUmassCsGnscommonResponseCode_withNSString_, code, message)
}

void EduUmassCsGnscommonExceptionsClientAclException_initWithNSString_(EduUmassCsGnscommonExceptionsClientAclException *self, NSString *message) {
  EduUmassCsGnscommonExceptionsClientClientException_initWithEduUmassCsGnscommonResponseCode_withNSString_(self, JreLoadEnum(EduUmassCsGnscommonResponseCode, ACCESS_ERROR), message);
}

EduUmassCsGnscommonExceptionsClientAclException *new_EduUmassCsGnscommonExceptionsClientAclException_initWithNSString_(NSString *message) {
  J2OBJC_NEW_IMPL(EduUmassCsGnscommonExceptionsClientAclException, initWithNSString_, message)
}

EduUmassCsGnscommonExceptionsClientAclException *create_EduUmassCsGnscommonExceptionsClientAclException_initWithNSString_(NSString *message) {
  J2OBJC_CREATE_IMPL(EduUmassCsGnscommonExceptionsClientAclException, initWithNSString_, message)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUmassCsGnscommonExceptionsClientAclException)
