#!/bin/bash

# The first argument must be a GNSCommandProtocol type and the second
# must be a GNSProtocol type. The words GNSCommandProtocol and
# GNSProtocol should not be prefixed. The script will automatically
# check in case type2 does not exist in GNSProtocol. It is important
# to first refactor type1 to be really unique, e.g., "xyz_SET_xyz"
# instead of just "SET", otherwise bad transformations can happen. The
# directory tmp/ must exist in the local directory. 

if [[ -z $1 || -z $2 ]]; then 
  echo "Usage: replace_type type1 type2 "
  exit
fi

# Removed as it is unclear what this does or why it is needed - mdews
#if [[ ! -e $moddir ]]; then
#  echo "tmp/ subdirectory must exist"
#  exit
#fi 

prefix="GNSCommandProtocol."
old=$1
new="GNSProtocol.$2"
moddir=tmp

present=`cat src/edu/umass/cs/gnscommon/GNSProtocol.java \
|grep "[^a-zA-Z]$2("`
if [[ -z $present ]]; then
  echo "$new not present in GNSProtocol"
  exit
fi

for i in `grep -R $old src/edu/umass/cs|sed s/:.*//g| \
grep -v GNSCommandProtocol.java`; 
do 
echo "working on $i"
mkdir -p "${moddir}/${i%/*}"
cat $i|grep -v "import static.*.$prefix$old;"| \
grep -v "String *$old *="| \
sed s/"$prefix$old"/"$new.toString\(\)"/g | \
sed s/"$old"/"$new.toString\(\)"/g > $moddir/$i;

echo "modified $i and stored it in $moddir/$i"
cp $moddir/$i $i; 
done

# also do test hierarchy
for i in `grep -R $old test/edu/umass/cs|sed s/:.*//g| \
grep -v GNSCommandProtocol.java`; 
do 
echo "working on $i"
mkdir -p "${moddir}/${i%/*}"
cat $i|grep -v "import static.*.$prefix$old;"| \
grep -v "String *$old *="| \
sed s/"$prefix$old"/"$new.toString\(\)"/g | \
sed s/"$old"/"$new.toString\(\)"/g > $moddir/$i;

echo "modified $i and stored it in $moddir/$i"
cp $moddir/$i $i; 
done

