//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../gig_ios/src/edu/umass/cs/protocoltask/ProtocolEvent.java
//

#include "J2ObjC_source.h"
#include "edu/umass/cs/protocoltask/ProtocolEvent.h"

@interface EduUmassCsProtocoltaskProtocolEvent : NSObject

@end

@implementation EduUmassCsProtocoltaskProtocolEvent

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSObject;", 0x401, -1, -1, -1, 0, -1, -1 },
    { NULL, "LNSObject;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 1, 2, -1, 3, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(getType);
  methods[1].selector = @selector(getMessage);
  methods[2].selector = @selector(setKeyWithId:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "()TEventType;", "setKey", "LNSObject;", "(TKeyType;)V", "<EventType:Ljava/lang/Object;KeyType:Ljava/lang/Object;>Ljava/lang/Object;Ledu/umass/cs/utils/Keyable<TKeyType;>;" };
  static const J2ObjcClassInfo _EduUmassCsProtocoltaskProtocolEvent = { "ProtocolEvent", "edu.umass.cs.protocoltask", ptrTable, methods, NULL, 7, 0x609, 3, 0, -1, -1, -1, 4, -1 };
  return &_EduUmassCsProtocoltaskProtocolEvent;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(EduUmassCsProtocoltaskProtocolEvent)
