//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../gig_ios/src/edu/umass/cs/reconfiguration/interfaces/ReconfiguratorDB.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsReconfigurationInterfacesReconfiguratorDB")
#ifdef RESTRICT_EduUmassCsReconfigurationInterfacesReconfiguratorDB
#define INCLUDE_ALL_EduUmassCsReconfigurationInterfacesReconfiguratorDB 0
#else
#define INCLUDE_ALL_EduUmassCsReconfigurationInterfacesReconfiguratorDB 1
#endif
#undef RESTRICT_EduUmassCsReconfigurationInterfacesReconfiguratorDB

#if !defined (EduUmassCsReconfigurationInterfacesReconfiguratorDB_) && (INCLUDE_ALL_EduUmassCsReconfigurationInterfacesReconfiguratorDB || defined(INCLUDE_EduUmassCsReconfigurationInterfacesReconfiguratorDB))
#define EduUmassCsReconfigurationInterfacesReconfiguratorDB_

@class EduUmassCsReconfigurationReconfigurationpacketsDemandReport;
@class EduUmassCsReconfigurationReconfigurationutilsReconfigurationRecord;
@class EduUmassCsReconfigurationReconfigurationutilsReconfigurationRecord_RCStates;
@class IOSObjectArray;
@class JavaNetInetSocketAddress;
@protocol EduUmassCsReconfigurationInterfacesReconfiguratorCallback;
@protocol JavaUtilMap;
@protocol JavaUtilSet;

@protocol EduUmassCsReconfigurationInterfacesReconfiguratorDB < JavaObject >

- (EduUmassCsReconfigurationReconfigurationutilsReconfigurationRecord *)getReconfigurationRecordWithNSString:(NSString *)name;

- (EduUmassCsReconfigurationReconfigurationutilsReconfigurationRecord *)createReconfigurationRecordWithEduUmassCsReconfigurationReconfigurationutilsReconfigurationRecord:(EduUmassCsReconfigurationReconfigurationutilsReconfigurationRecord *)record;

- (jboolean)createReconfigurationRecordsWithJavaUtilMap:(id<JavaUtilMap>)nameStates
                                        withJavaUtilSet:(id<JavaUtilSet>)newActives;

- (jboolean)deleteReconfigurationRecordWithNSString:(NSString *)name
                                            withInt:(jint)epoch;

- (jboolean)markDeleteReconfigurationRecordWithNSString:(NSString *)name
                                                withInt:(jint)epoch;

- (jboolean)updateDemandStatsWithEduUmassCsReconfigurationReconfigurationpacketsDemandReport:(EduUmassCsReconfigurationReconfigurationpacketsDemandReport *)report;

- (NSString *)getDemandStatsWithNSString:(NSString *)name;

- (jboolean)setStateWithNSString:(NSString *)name
                         withInt:(jint)epoch
withEduUmassCsReconfigurationReconfigurationutilsReconfigurationRecord_RCStates:(EduUmassCsReconfigurationReconfigurationutilsReconfigurationRecord_RCStates *)state;

- (jboolean)setStateInitReconfigurationWithNSString:(NSString *)name
                                            withInt:(jint)epoch
withEduUmassCsReconfigurationReconfigurationutilsReconfigurationRecord_RCStates:(EduUmassCsReconfigurationReconfigurationutilsReconfigurationRecord_RCStates *)state
                                    withJavaUtilSet:(id<JavaUtilSet>)newActives;

- (jboolean)setStateInitReconfigurationWithJavaUtilMap:(id<JavaUtilMap>)nameStates
                                               withInt:(jint)epoch
withEduUmassCsReconfigurationReconfigurationutilsReconfigurationRecord_RCStates:(EduUmassCsReconfigurationReconfigurationutilsReconfigurationRecord_RCStates *)state
                                       withJavaUtilSet:(id<JavaUtilSet>)newActives;

- (IOSObjectArray *)getPendingReconfigurations;

- (void)removePendingWithNSString:(NSString *)name;

- (id<JavaUtilMap>)getRCGroups;

- (id<JavaUtilSet>)getRCGroupNames;

- (jboolean)addReconfiguratorWithId:(id)node
       withJavaNetInetSocketAddress:(JavaNetInetSocketAddress *)sockAddr
                            withInt:(jint)version_;

- (jboolean)addActiveReplicaWithId:(id)node
      withJavaNetInetSocketAddress:(JavaNetInetSocketAddress *)sockAddr
                           withInt:(jint)version_;

- (jboolean)garbageCollectOldReconfiguratorsWithInt:(jint)version_;

- (jboolean)mergeStateWithNSString:(NSString *)name
                           withInt:(jint)epoch
                      withNSString:(NSString *)mergee
                           withInt:(jint)mergeeEpoch
                      withNSString:(NSString *)state;

- (jboolean)mergeIntentWithNSString:(NSString *)name
                            withInt:(jint)epoch
                       withNSString:(NSString *)mergee;

- (jboolean)setStateMergeWithNSString:(NSString *)name
                              withInt:(jint)epoch
withEduUmassCsReconfigurationReconfigurationutilsReconfigurationRecord_RCStates:(EduUmassCsReconfigurationReconfigurationutilsReconfigurationRecord_RCStates *)state
                      withJavaUtilSet:(id<JavaUtilSet>)newActives
                      withJavaUtilSet:(id<JavaUtilSet>)mergees;

- (jboolean)setStateMergeWithJavaUtilMap:(id<JavaUtilMap>)nameStates
                                 withInt:(jint)epoch
withEduUmassCsReconfigurationReconfigurationutilsReconfigurationRecord_RCStates:(EduUmassCsReconfigurationReconfigurationutilsReconfigurationRecord_RCStates *)state
                         withJavaUtilSet:(id<JavaUtilSet>)newActives;

- (void)delayedDeleteComplete;

- (void)clearMergedWithNSString:(NSString *)name
                        withInt:(jint)epoch;

- (void)setRCEpochsWithEduUmassCsReconfigurationReconfigurationutilsReconfigurationRecord:(EduUmassCsReconfigurationReconfigurationutilsReconfigurationRecord *)ncRecord;

- (void)garbageCollectedDeletedNodeWithId:(id)node;

- (jboolean)initiateReadActiveRecordsWithId:(id)active OBJC_METHOD_FAMILY_NONE;

- (EduUmassCsReconfigurationReconfigurationutilsReconfigurationRecord *)readNextActiveRecord;

- (jboolean)closeReadActiveRecords;

- (NSString *)fetchAndAggregateMergeeStatesWithJavaUtilMap:(id<JavaUtilMap>)finalStates
                                              withNSString:(NSString *)mergerGroup
                                                   withInt:(jint)epoch;

- (void)setCallbackWithEduUmassCsReconfigurationInterfacesReconfiguratorCallback:(id<EduUmassCsReconfigurationInterfacesReconfiguratorCallback>)callback;

- (void)close;

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsReconfigurationInterfacesReconfiguratorDB)

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsReconfigurationInterfacesReconfiguratorDB)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsReconfigurationInterfacesReconfiguratorDB")
